### ISSUE TITLE
reactSprings and delay?

### ISSUE THREAD

**Issue by dboydor** [react-spring/react-spring#1001]
Does the "delay" prop work with useSprings()?   The docs indicate it should.

Here's a sandbox that demonstrates the issue:
https://codesandbox.io/s/jovial-mirzakhani-rejmh

The useSprings() version only works when you set delay to 0, or omit it.

My goal is to have a random delay for each spring within a range.

useTrails() works but it was too slow.  When I set "duration", it didn't really look so good anymore.

**Comment by aleclarson** [comment]
Two things:
- You cannot call `set` while rendering, so wrap it with `React.useEffect`
- Pass `delay` to the `set` call, instead of returning from the props function

```jsx
  React.useEffect(() => {
    set({ value: 1, delay });
  },[])
```

**Comment by aleclarson** [comment]
If you need the `index` to calculate the delay, do this:
```jsx
set(index => ({ value: 1, delay: delay * index }))
```

**Comment by dboydor** [comment]
Thank you!  Both of those worked great.

I did have to do this, for the function version of set() because there doesn't appear to be a typescript definition for that form.

```
const [springs, set] = useSprings(circles.length, () => ({value: 0})) as any;
set(offset => {
    return { value: 1, delay: Math.random() * 250 };
});
```

**Comment by aleclarson** [comment]
v9 has proper type defs. Give it a try ;) #985
