### ISSUE TITLE
FrameLoop does not stop requesting animation frames

### ISSUE THREAD

**Issue by DPangerl** [react-spring/react-spring#1002]
## 🐛 Bug Report

I'm using `react-spring@9.0.0-rc.3` in a gatsby project. 
Using the `useSpring` hook there are several calls of `requestAnimationFrame()` during the animation (`FrameLoop.js`). 

After the animation has finished, `requestAnimationFrame()` gets called infinitely until i refresh the browser. 

This behaviour also infinitely triggers  `window.visualViewport.onscroll`, which I have to use within my project. 

With `react-spring@8.0.27` this behaviour does not occure. 

## To Reproduce

Use `useSpring` from `react-spring@9.0.0-rc.3`
Create any animation and trigger it. 

## Expected behavior

`requestAnimationFrame()` should stop beeing called after the animation has finished.  

## Link to repro (highly encouraged)

This is one of your examples from [react-spring.io](https://www.react-spring.io/) with `react-spring@9.0.0-rc.3`
https://codesandbox.io/s/adoring-shadow-o7k53

Just check the preformance tab in chrome dev-tools.

## Environment

- `react-spring` v9.0.0-rc.3 (possible 9.x.x)
- `react` v16.8.x (also 16.13)

**Comment by aleclarson** [comment]
The frameloop was made continuous to prevent frame drops with async `to` functions, but that change might only be beneficial to `@react-spring/native` (where enough latency is created by the native bridge to easily drop frames). I'll see if `@react-spring/web` is vulnerable to frame drops in the same way.

I've not heard of `visualViewport` until now. You're saying its `onscroll` event is triggered by rAF calls?

**Comment by DPangerl** [comment]
Yes it is… I tried to reproduce this in a "clean" environment.
With a minimal react setup with react-spring v9.0.0-rc.2 on an iOS device i could reproduce the behaviour… 

Here is a screencast i made. 
https://streamable.com/l5jtfp

I think `visualViewport` might only exist on mobile devices, but on these it is a rather important to handle all those overlays. Maybe this is caused by a poor implementation of this feature in iOS Safari (😬 How dare I!)

However, I will be glad to help with additional information…

**Comment by aleclarson** [comment]
Have you tried using `addEventListener` instead of `onscroll`?

```js
visualViewport.addEventListener('scroll', () => {...});
```

**Comment by DPangerl** [comment]
Sorry, here is the code…
Yes i have. I've just used `onscroll` for the output text.
```js

import React, { useEffect, useState } from 'react';
import { animated, useSpring } from 'react-spring';

const Start = () => {
  const [circles, setCircles] = useState(0);
  const [trigger, set] = useState(false);
  const spring = useSpring({
    opacity: trigger ? 0 : 1,
  });

  useEffect(() => {
    const test = () => {
      setCircles((prev) => prev + 1);
    };
    window.visualViewport.addEventListener('scroll', test);
    return () => {
      window.visualViewport.removeEventListener('scroll', test);
    };
  }, []);
  if (loading) return 'loading…';

  return (
    <StartView>
      <div style={{ border: '2px solid black', padding: '1rem' }}>
        <button onClick={() => set(true)}>START ANIMATION</button>
        <div>
          <code>window.visualViewport.onscroll</code> is called
          <strong> {circles} </strong>times
        </div>
      </div>
      <animated.p style={spring}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam atque
        velit doloremque at architecto perspiciatis, recusandae quas quae
        officia ipsa! Voluptatibus, debitis. Nulla dignissimos itaque quae
        sapiente quisquam repellendus tempore?
      </animated.p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam atque
        velit doloremque at architecto perspiciatis, recusandae quas quae
        officia ipsa! Voluptatibus, debitis. Nulla dignissimos itaque quae
        sapiente quisquam repellendus tempore?
      </p>
```

**Comment by aleclarson** [comment]
Great, now put that in a working sandbox for me. Thanks. 👍

**Comment by DPangerl** [comment]
Here you go:
https://codesandbox.io/s/mystifying-blackburn-omei2?file=/src/App.js

**Comment by aleclarson** [comment]
The visual viewport isn't emitting `scroll` events when I start the animation in Chrome. This leads me to believe this is an issue with WebKit, so consider reporting it [here](https://bugs.webkit.org/).
