### ISSUE TITLE
how to get more controll over animations?

### ISSUE THREAD

**Issue by kurosh-z** [react-spring/react-spring#1004]
## 🤓 Question
Hi, 
Thank you for this amazing library! I'm trying to make a math animation. User should be able to play and pause the animation or make some changes. As an example I should be able to control three different springs (to animate vector u and w, and one for play button).
![1anim](https://user-images.githubusercontent.com/32224317/81730241-83c13b80-948d-11ea-8f67-c8405014f95b.gif)
I have following problems:
1. Using onRest callback causing next animation to be triggered immediately because spring runs the from props automatically as component mounts. this way I should define extra state for every animation to be sure it's not  triggered after component mounts.
2. I figured out, if I use ref for the animation I can access to controllers and with ref its not going to start animation until I run start, however the controller's stop function doesn't cause animation to stop! sandbox: https://codesandbox.io/s/clever-yonath-9rnos?file=/src/App.tsx:607-893

``` typescript
 const styles = useSpring({
    ref: springRef,
    config: { friction: 190, mass: 100, tension: 120 },
    from: { width: 0 },
    to: { width: 400 }
  });

 useEffect(() => {
    const controllers = springRef.current.controllers;
    controllers[0].start(() => {
      console.log("started");
    });

    window.setTimeout(() => {
      console.log("stop it!");
      controllers[0].stop(() => console.log("stoped"));
    }, 1200);
  }, []);
```
3.  Using function in useSpring cause controller.start() not to work at all!
```typescript
 use function to get set and stop!
  const [styles, setStyles, stopanim] = useSpring(() => ({
    ref: springRef,
    config: { friction: 190, mass: 100, tension: 120 },
    width: 0
  }));
  setStyles({width:200})
   useEffect(()=>{
      const controllers = springRef.current.controllers;
      controllers[0].start()
   }, [])
```
I'm trying to write something like:
```typescript
  const [spring1, setSpring1, pauseSpring1] = useSpring(() => ...
  const [spring2, setSpring2, pauseSpring2] = useSpring(() => ...

  const [styles, setStyles, stopanim] = useSpring(() => ({
    ref: springRef,
    config: { friction: 190, mass: 100, tension: 120 },
    width: 0, 
    onEnd: async () => {
    await setSpring1({opacity: 1, color: '#ffaaee'})
    await setSpring2({width: 400, color: 'rgb(14,26,19)'})
    .
    .
    .
  },

    }

  }));

```
then onPause store the current values and velocities somewhere to be able to continue if it get unpaused again. 
Would something like this or similar possible in current version of react-spring?

**Comment by aleclarson** [comment]
Which versions have you tried?

LMK if 9.0.0-rc.3 works for you: #985

**Comment by kurosh-z** [comment]
> Which versions have you tried?
> 
> LMK if 9.0.0-rc.3 works for you: #985

I checked the new version out. It's exactly what I needed. Be able to use async  is really helpful.   
I have a question thought! I couldn't still find an unpusing function. Right now I store the last Velocity and use it to continue the animation. 
sandbox: https://codesandbox.io/s/admiring-franklin-idefm?file=/src/App.tsx
Is it the right way to think about it or there is still a better solution for that?
Otherwise this new version seems to made everything perfect! Thank you for dedicating your time and energy into this.

**Comment by aleclarson** [comment]
@kurosh-z Glad to hear it! For pausing and resuming, you can use the `pause` prop.

So instead of..

```jsx
pause
  ? stop(["width", "height"])
  : anim({
      to: { width: 200 },
      config: { velocity: lastVel }
    });
```

..do this..

```jsx
anim({ width: 200, default: { pause } })
```

In the next version, you won't need a `default` object. You'll be able to do this:

```jsx
anim({ width: 200, pause })
```

The difference with using a `default` object is that future updates are also paused. When you define `pause` without a `default` object, it only affects the current animation and the update it's defined in.

**Comment by aleclarson** [comment]
Side note: Your example uncovered a bug, where `onRest` is called twice (once per animated value), even though it should only be called once (after all animated values are done animating).

**Comment by kurosh-z** [comment]
> @kurosh-z Glad to hear it! For pausing and resuming, you can use the `pause` prop.
> 
> So instead of..
> 
> ```js-jsx
> pause
>   ? stop(["width", "height"])
>   : anim({
>       to: { width: 200 },
>       config: { velocity: lastVel }
>     });
> ```
> 
> ..do this..
> 
> ```js-jsx
> anim({ width: 200, default: { pause } })
> ```
> 
> In the next version, you won't need a `default` object. You'll be able to do this:
> 
> ```js-jsx
> anim({ width: 200, pause })
> ```
> 
> The difference with using a `default` object is that future updates are also paused. When you define `pause` without a `default` object, it only affects the current animation and the update it's defined in.

wow! that makes everything so simple right now.

**Comment by kurosh-z** [comment]
> Side note: Your example uncovered a bug, where `onRest` is called twice (once per animated value), even though it should only be called once (after all animated values are done animating).

Oh I thought it's the default behavior now and I have to pass keys or something to prevent it.
Thank you again for the amazing library!

**Comment by kurosh-z** [comment]
> Side note: Your example uncovered a bug, where `onRest` is called twice (once per animated value), even though it should only be called once (after all animated values are done animating).

There is similar bug with onStart when using "to" in useSpring! sandbox: (https://codesandbox.io/s/agitated-buck-nmwdu?file=/src/App.tsx)
Expected:
red box's to-prop has two transform animations like this=> to: [{transform1}  , {transform2}]. 
green box should move to (0,50) as red box starts (as transform1 starts) .
Actual:
green box gets started only after transform2 starts.
