### ISSUE TITLE
pausing two or more springs 

### ISSUE THREAD

**Issue by kurosh-z** [react-spring/react-spring#1006]
## 🐛 Bug Report

In case of two springs or more, pausing just works for the first one. For example if you use the callback function below (animCallback) as click handler, it stops the first animation but the second one continues regardless of the pause state. 

## To Reproduce
``` typescript
const [pause, toggle]= useState(false)
 const animCallback= useCallback(async () => {
    await setGreen({
      width: 200,
      default: { pause },
      })
    await setBrown({
      transform: "translate(400px, -300px)",
      default: { pause }
    });
  }, [pause, setGreen, setBrown]);
``` 

## Expected behavior
All animations defined in animCallback should be stoped if puase is true. 

## Link to repro 
Codesandbox: https://codesandbox.io/s/pausing-second-spring-not-working-2mndx?file=/src/App.tsx

## Workaround
If you use spring ref and  pause all of them in useEffect it works as expected!
Sandbox: https://codesandbox.io/s/spring-pause-with-ref-e29v7?file=/src/App.tsx

## Environment

- `react-spring` web@9.0.0-rc.3
- `react` v16.12.0

**Comment by aleclarson** [comment]
When the pause button is pressed while the `setBrown` animation is going, your `animCallback` gets stalled on the `setGreen` call because `pause` is true. I think you want something like this:

```jsx
await Promise.all([
  setGreen({
    width: 200,
    default: { pause },
  }),
  setBrown({
    transform: "translate(400px, -300px)",
    default: { pause }
  }),
]);
```

**Comment by aleclarson** [comment]
Oh, I suppose you want to call `setBrown` *after* the `setGreen` animation is finished?

In that case, you'll want to send pausing/resuming updates separately.

So, remove `default: {pause}` from your `animCB` function, and change your `onClick` handler to do this:

```jsx
setGreen({ default: {pause} })
setBrown({ default: {pause} })
if (!pause) {
  animCB();
}
toggle(!pause);
```
