### ISSUE TITLE
[v9.0.0-rc.3] Animation never reaches the goal value

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring#1007]
Hi,

I just upgraded to rc3 and have a found a small change that messes with some of my code. I am animating springs to 0, and then in their onChange handlers triggering functions once the spring value passed into the handler displays 0. I think the reason for this was in a previous canary version onRest was not being successfully triggered for some reason, this was my way around this. What actually ends up happening is the spring gets progressively closer to 0 without actually reaching it. I think maybe there is a spring config property that maybe I'm missing or has changed?

Thanks,

_Originally posted by @HQ92 in https://github.com/react-spring/react-spring/issues/985#issuecomment-628678446_

**Comment by aleclarson** [comment]
@HQ92 Provide a minimal repro please. You can fork [this sandbox](https://codesandbox.io/s/react-spring-v9-template-8ebn2) if you'd like.

**Comment by HQ92** [comment]
I've tried reproducing it on codesandbox, haven't succeeded yet so you can close this at the moment and I'll let you know if i can reproduce it. It might just be something in my code messing with it. Thanks anyways!
