### ISSUE TITLE
How can i use advanced api of `useTransition` in Typescript?

### ISSUE THREAD

**Issue by moonrailgun** [react-spring/react-spring#1011]
## 🤓 Question

How can i replay `MessageHub` case in Typescript? Its looks like type of this API is not completed.

type definition provider in v8 is not support async config like 
```javascript
enter: item => async next => await next({ opacity: 1, height: refMap.get(item).offsetHeight }),
```

https://codesandbox.io/s/messagehub-in-typescript-1pkg7

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next -E
```

**Comment by moonrailgun** [comment]
Hi @aleclarson 

Is v9 is a stable version for production env?
Its looks like have some break change from v8. Can i simply upgrade it and just fix its break change? Or maybe should have a type definition patch in stable version?

Thanks for you reply.

**Comment by aleclarson** [comment]
v9 is more stable than v8 now. 👍 

Breaking changes are listed [here](https://aleclarson.github.io/react-spring/v9/breaking-changes/).

**Comment by moonrailgun** [comment]
Well, thanks for you reply.

I will try to migrate from v8 to v9. and close this issue.

**Comment by wendellhu95** [comment]
> v9 is more stable than v8 now. 👍
> 
> Breaking changes are listed [here](https://aleclarson.github.io/react-spring/v9/breaking-changes/).

Keep that good work!
