### ISSUE TITLE
react-native 0.62 requires useNativeDriver to be explicitly set

### ISSUE THREAD

**Issue by benvp** [react-spring/react-spring#1014]
## 🐛 Bug Report

In the latest react-native version (0.62) the property `useNativeDriver` needs to be explicitly set. Currently this causes every animation frame to emit a warning which says:

> [Mon May 18 2020 17:05:53.670]  WARN     Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

## To Reproduce

Run any animation using react-native.

## Expected behavior

No warning at all. I expect that it would only be required to set `useNativeDriver` to `false` as it's not fully supported by react-spring, isn't it?

## Environment

- `react-spring` v8.x.x / 9.x.x
- `react-native` v0.62`

**Comment by aleclarson** [comment]
react-spring has its own fork of Animated (found [here](https://github.com/react-spring/react-spring/tree/v9/packages/animated)), so I don't think this has anything to do with react-spring, but if you can make a git repo that reproduces the issue, I'll take a look. 👍

**Comment by benvp** [comment]
Thanks for pointing this out. I did set-up a minimal example and can confirm that the warning does not occur. So this is an issue somewhere in the project I'm working on. Sorry for bothering 😛
