### ISSUE TITLE
`useSpring` function API typings do not match documentation

### ISSUE THREAD

**Issue by fetherolfjd** [react-spring/react-spring#1015]
## 🐛 Bug Report

The documentation indicates `useSpring` has the pictured API:
![image](https://user-images.githubusercontent.com/5353258/82362944-63800800-99ca-11ea-9804-4b410ee098a0.png)

If used in a Typescript project, the `stop` item of the tuple is undefined, as can be seen in the [typings](https://github.com/react-spring/react-spring/blob/master/types/web.d.ts#L128):
```typescript
// there's a third value in the tuple but it's not public API (?)
export function useSpring<DS extends object>(
  values: UseSpringProps<Merge<DS, CSSProperties>>
): AnimatedValue<ForwardedProps<OverwriteKeys<DS, CSSProperties>>>
export function useSpring<DS extends object>(
  getProps: () => UseSpringProps<Merge<DS, CSSProperties>>
): [AnimatedValue<ForwardedProps<OverwriteKeys<DS, CSSProperties>>>, SetUpdateFn<OverwriteKeys<DS, CSSProperties>>]
```

## To Reproduce

Attempt to use the documented `useSpring` API in a Typescript project.

## Expected behavior

The `stop` tuple item is not `undefined`.

## Link to repro (highly encouraged)

Not created because it seems unnecessary; let me know if you'd like one anyways and I can throw something together. 😄 

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.12.0

**Comment by aleclarson** [comment]
The types were rewritten in v9.

The latest types are here: https://github.com/react-spring/react-spring/tree/v9/packages/core/src

**Comment by fetherolfjd** [comment]
Ah, brilliant. Though I'm using the v9.0.0-rc.3 package; maybe the old typings managed to stay in the TS compiler or something?

Thanks anyways!

**Comment by aleclarson** [comment]
When you right-click `useSpring` and click "Go to Definition", you should see something like this: 

https://github.com/react-spring/react-spring/blob/17d2749b290f9e7e586a52e4b8709bc75dcc09e4/packages/core/src/hooks/useSpring.ts#L35-L44

If you're still seeing an error, put together a [CodeSandbox](https://codesandbox.io/s/winter-wood-w37vz) that reproduces it. 👍

**Comment by fetherolfjd** [comment]
Yep, I blew away my node_modules and re-installed and I've got the expected typings now. Thanks!
