### ISSUE TITLE
New onRest behavior in rc3 with from property

### ISSUE THREAD

**Issue by Krispy3000** [react-spring/react-spring#1017]
If a spring is set to a new value before it has finished animation for the previous value, and one of those sets has a from property, the onRest for both set functions will execute in rc3. The old behavior in 808.17 was that only the onRest from the final set function would execute.

This behavior can be seen here by quickly toggling the button twice: https://codesandbox.io/s/infallible-khayyam-48zim?file=/src/App.js
In the console you should see both onRest open and close execute. If you change react-spring to 808.17 then only onRest open will execute if you toggle twice quickly.

For comparison, here is the same code but the 'from' property removed: https://codesandbox.io/s/magical-mendeleev-bg5hz?file=/src/App.js
Here it works as expected with only the onRest open executing when quickly toggled twice.

I don't know if this is an intentional change, but I was relying on this behavior for a modal.

**Comment by aleclarson** [comment]
The `onRest` prop receives an `AnimationResult` object, which is described [here](https://aleclarson.github.io/react-spring/v9/#Animation-results).

You can check `result.finished` (or destructure the `result` if you prefer):
```jsx
onRest(res) {
  if (res.finished) {
    // the animation completed
  } else {
    // the animation was interrupted
  }
}
```

**Comment by Krispy3000** [comment]
Thank you, that works perfectly.
