### ISSUE TITLE
[v9.0.0-rc.3] TypeScript syntax error when bundling for React Native

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring#1028]
Hi, the syntax for typescript incorrect in `@react-spring/core@9.0.0-rc.3` at `ReactNative` environment.

The error report is below:
![image](https://user-images.githubusercontent.com/6964737/82909205-8ba7d200-9f9b-11ea-865f-2ab04e445d1b.png)
if I change to 
```typescript
export { AnimationResult } from './AnimationResult'
export { UnknownProps } from './types/common'
```

It works.

What should i do or how can i resolve it?

_Originally posted by @moonrailgun in https://github.com/react-spring/react-spring/issues/985#issuecomment-634048743_

**Comment by TrySound** [comment]
Maybe the problem is old typescript version? This syntax is introduced in one of the latest versions, right?

**Comment by aleclarson** [comment]
The TypeScript compiler in Metro is outdated. It needs [this commit](https://github.com/babel/babel/commit/740260b23625c86850b3d451c9901f85d19ea941#diff-b927af16ccd5c06377b32400f8eb774f) for `export type` syntax to work, which was released in `@babel/plugin-transform-typescript@7.9.0`.

https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/package.json#L55



Please open an issue/PR over there. 👍

**Comment by aleclarson** [comment]
Actually, if you regenerate your lockfile, the new `@babel/plugin-transform-typescript` should be installed.

**Comment by moonrailgun** [comment]
This problem still alive.

Although i install `@babel/plugin-transform-typescript@latest` by myself .
- Checked `node_modules` folder and ensure its `@babel/plugin-transform-typescript` is `7.9.6`.
- Checked `node_modules/metro-react-native-babel-preset` to ensure its have not own `node_modules`
- Even print `require("@babel/plugin-transform-typescript/package.json")` in `node_modules\metro-react-native-babel-preset\src\configs\main.js` ensure require right module and check the version of it is correct.

What else I forget to do? 

Can you help me to resolve it? Thanks for a lot.

**Comment by aleclarson** [comment]
Try `--reset-cache` when starting the react-native dev server.

**Comment by moonrailgun** [comment]
Oh i resolve it. Its looks like alse dependent on other core package. Just upgrade `@babel/core` and `@babel/runtime`. And everything looks well

https://github.com/facebook/metro/issues/537#issuecomment-630190299
