### ISSUE TITLE
Memory leaks on page refresh

### ISSUE THREAD

**Issue by aiyer07** [react-spring/react-spring#1034]
## 🐛 Bug Report
When refreshing a page that is using useSpring or Spring renderprop I'm noticing a memory leak 

## To Reproduce
1. Go to https://codesandbox.io/s/cocky-smoke-v6x9y for a simple count up example
2. Open browser incognito and open memory tab. Using heap timeline and snapshots, notice the memory steadily increases even after forcing garbage collection
3. Comment out Spring and there is no memory increase

## Expected behavior
Expected memory to be garbage collected on refresh

## Environment
Although I am running react-spring 9 i have noticed the same issue on the latest react-spring

- `react-spring` v9.0.0-beta.34
- `react` v16.13.1 (latest)
- `next` v9.4.4  (latest)

**Comment by aleclarson** [comment]
Please try `v9.0.0-rc.3` #985 👍

**Comment by aiyer07** [comment]
> Please try `v9.0.0-rc.3` #985 👍

I updated the codesandbox to be v9.0.0-rc.3. Same issue. Here's a heap allocation timeline while I refresh the app

![Screen Recording 2020-05-31 at 01 25 PM](https://user-images.githubusercontent.com/3598276/83362032-f9108580-a342-11ea-96c4-535076ee1573.gif)

**Comment by aleclarson** [comment]
You can reproduce outside of CodeSandbox?

**Comment by aiyer07** [comment]
Yes I can. I am actually doing something very similar (a simple count up animation) in a next.js app. 

Simply creating a spring using `useSpring` causes the leak in my components. Specifically seems to be a problem on page refresh

**Comment by aleclarson** [comment]
Ah, I looked over the detail that you're using NextJS. See here: #778

**Comment by aiyer07** [comment]
@aleclarson Thanks for that link I'm following that thread now. One thing that might be worth noting is that the codesandbox is not actually using ssr/nextjs, although i did discover the issue initially in a next app.
