### ISSUE TITLE
[v9.0.0-rc.3] useTransition doesn't update "transform" when leaving

### ISSUE THREAD

**Issue by abdullahsari** [react-spring/react-spring#1035]
## 🐛 Bug Report

React-spring fails to update the transform property before unmounting if the unmount has been triggered **after** the mounting animation has finished ([see this video](https://i.gyazo.com/10128c14fd73aaf8c254800a63e1ba38.mp4)). I'm not sure if there are other props affected by this, but as you can see opacity works just fine as expected.

##  Example 

```javascript
const Menu = ({ open }) => {
    const t = useTransition(open, {
        from: { opacity: 0, transform: 'translateX(100%)' },
        enter: { opacity: 1, transform: 'translateX(0)' },
        leave: { opacity: 0, transform: 'translateX(100%)' },
        config: { duration: 250 },
    });

    return t(
        (style, item) =>
            item && (
                <animated.aside
                    style={style}
                    className="...">
                   { /* some content */ }
                </animated.aside>
            )
    );
};
```

## Link to repro (highly encouraged)

Could not reproduce it on CSB, occurs in my current project though.
Did not happen in v8 with the old useTransition signature.

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.13.1

**Comment by aleclarson** [comment]
Try changing `translateX(0)` to `translateX(0%)`

**Comment by abdullahsari** [comment]
Indeed, the '%' was the culprit. It was working just fine in v8 that's why I did not suspect anything regarding the absence of the percent symbol. Thank you!

**Comment by selrond** [comment]
@aleclarson I have the same exact problem, percent symbol thing doesn't help:
https://codesandbox.io/s/react-spring-dialogs-mqukl

**Comment by aleclarson** [comment]
@selrond Probably not the same issue then. Try using v9, then open a new issue. Thanks 👍
