### ISSUE TITLE
[9.0.0-rc.3] useSpring | cannot interpolate value

### ISSUE THREAD

**Issue by aamorozov** [react-spring/react-spring#1039]
## 🐛 Bug Report

It seems to be a breaking change between `react-spring@9.0.0-beta.5` and `react-spring@next`. 
The range of the scale is not being interpolated from 1 to 1.2(see sandbox demo link below) and the animation instantly updates to the end range of 1.2s. 

## Expected behavior

The animation works in both versions or a clear error message is shown describing why the value is not/cannot be interpolated.

## Link to repro (highly encouraged)

https://codesandbox.io/s/quiet-sunset-02sjn?file=/src/components/link.js

To reproduce, toggle between react-spring versions noted above.

## Environment

- `react-spring v9.0.0-rc.3`(next)
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by b2whats** [comment]
I create normal example and all works - https://codesandbox.io/s/pedantic-bell-mhvpp

**Comment by aleclarson** [comment]
@aamorozov You don't need the `from` object. Move the `scale` property into the object that `from` is defined in.

**Comment by aamorozov** [comment]
Thank you, it worked! Closing the issue
