### ISSUE TITLE
[9.0.0-rc.3] useSprings not behaving properly

### ISSUE THREAD

**Issue by christianvonlehe** [react-spring/react-spring#1047]
## 🐛 Bug Report

When trying to implement a simple useSprings example I am unable to mimic other examples. I don't know if this is because the way to use it has changed with the newest rc.

## To Reproduce

Use useSprings like I have in the sandbox

## Expected behavior

Have the items transition based off of their index values

## Link to repro 

[CodeSandbox](https://codesandbox.io/s/priceless-meadow-dj8fd?file=/src/App.js)

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.12

**Comment by aleclarson** [comment]
When you pass a function to `useSprings`, it wraps the array of springs in a tuple that includes an `animate` function and a `stop` function. Pretty sure that's how v8 works, too.

```jsx
const [springs, animate, stop] = useSprings(3, i => ({ ... }))
```
