### ISSUE TITLE
useTransition does not update enter values

### ISSUE THREAD

**Issue by arackaf** [react-spring/react-spring#1056]
## To Reproduce

```js
//const [selectedBookTransitions] = useTransition(
const selectedBookTransitions = useTransition(
  selectedBooks,
  {
    config: { ...config.molasses },
    keys: book => book._id,
    from: { opacity: 0, transform: "translate3d(-25%, 0px, 0px)" },
    // from: (book, b) => {
    //   console.log("from", book._id, b);
    //   return { opacity: 0, transform: "translate3d(-25%, 0px, 0px)" };
    // },
    enter: selectedBooks.map((book, b) => {
      console.log("ENTER", book._id, b, displaySizes[book._id]);
      return { opacity: 1, height: displaySizes[book._id], transform: "translate3d(0%, 0px, 0px)" };
    }),
    leave: (book, b) => {
      console.log("leave", book._id, b);
      return { opacity: 0, height: 0, transform: "translate3d(25%, 0px, 0px)" };
    }
  },
  //[selectedBooks, displaySizes]
);
```

I know there's some implementation details missing, but this appears to work perfectly. After adding one item, in the console I can see "ENTER" logging with updated, correct values. However, the animated item does NOT have the new, updated height. Its height style attribute is empty in the dom.

![image](https://user-images.githubusercontent.com/11261266/84574981-b18cef00-ad6f-11ea-8672-55ad62febb47.png)

That said, if I add other items to the `selectedBooks` array, they work perfectly, and show up with the correct height values.

As you can see from the commented out code, I've also tried this with the dep arrays, but I've never quite been able to get that to work, either.

Is this a bug, or do I in fact need dep arrays for this to work, and have just been using them incorrectly. I know the return values change when you use a dep array, and there seems to be an update function returned as the second value in the array, but I haven't quite been able to get that to work, and the few docs I saw on them

https://aleclarson.github.io/react-spring/v9/#Dependency-arrays

were limited to useSpring.

## Expected behavior

enter values would update appropriately.

## Link to repro (highly encouraged)

None yet but I can make one if absolutely needed.

## Environment

- `react-spring` v9 rc3
- `react` v0.0.0-experimental-33c3af284

**Comment by aleclarson** [comment]
Sounds like you need the `update` prop. Did you try that?

```jsx
update: book => {
  console.log("UPDATE", book._id, displaySizes[book._id]);
  return { height: displaySizes[book._id] };
}),
```

**Comment by arackaf** [comment]
Works perfectly. Thank you SO much. I'm loving react-spring more and more.
