### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by zurez** [react-spring/react-spring#1081]
## 🤓 Question
I have created 20 springs using the useSprings hook from an array of 20 elements. Then I attached gesture , and tranisition3d property to these 20 springs. But this causes performance issues in mobile phones , especially Android.

Then I thought of other solutions, 
just make 3 elements of that array ( which is passed as a prop) then , show the next 3 when the transition on the first has finished through prop update. This does not work.

Then I sliced the array of 20 springs to only show 3 springs at a time 
springs.slice(0,3).map(props => //dosomething) 
this also does not work.

What should I do ? How do I resolve this ? I am stuck at this for so long.

Package.json
	"dependencies": {
		"@material-ui/core": "^4.9.7",
		"@material-ui/icons": "latest",
		"@material-ui/lab": "^4.0.0-alpha.46",
		"@types/react-transition-group": "^4.2.4",
		"@welldone-software/why-did-you-render": "^4.2.2",
		"aws-amplify": "^2.2.7",
		"classnames": "^2.2.6",
		"connected-next-router": "^2.0.0-alpha.3",
		"dotenv": "^8.2.0",
		"firebase": "^7.14.2",
		"next": "^9.3.6",
		"next-cookies": "^2.0.3",
		"next-pwa": "^2.6.0",
		"next-redux-saga": "^4.1.2",
		"next-redux-wrapper": "^4.0.1",
		"react": "^16.13.1",
		"react-dom": "^16.13.1",
		"react-keyboard-event-handler": "^1.5.4",
		"react-keydown": "^1.9.12",
		"react-otp-input": "^1.0.1",
		"react-redux": "^7.2.0",
		"react-share": "^4.1.0",
		"react-spring": "^9.0.0-rc.3",
		"react-spring-carousel": "0.0.4",
		"react-use-gesture": "^7.0.15",
		"redux": "^4.0.5",
		"redux-persist": "^6.0.0",
		"redux-persist-transform-filter": "0.0.20",
		"redux-responsive": "^4.3.8",
		"redux-saga": "^1.1.3",
		"styled-components": "^5.0.1",
		"typesocket": "^1.0.0",
		"url-loader": "^3.0.0",
		"uuid": "^7.0.2"
	},

**Comment by RafalFilipek** [comment]
Can you provide some example via https://codesandbox.io/?

**Comment by aleclarson** [comment]
Closing until a repro is provided 👍
