### ISSUE TITLE
Goo Blobs not working in Safari

### ISSUE THREAD

**Issue by allroundexperts** [react-spring/react-spring#1084]
## 🐛 Bug Report
Goo Blobs are not working in Safari.

## To Reproduce
Open https://www.react-spring.io/docs/hooks/use-trail in Safari. Goo Blobs appear to be buggy.

<img width="1436" alt="Screenshot 2020-07-16 at 3 11 01 AM" src="https://user-images.githubusercontent.com/30054992/87604901-fe1e6e00-c711-11ea-8354-670315e0e63d.png">

## Expected behavior
Must be same like chrome.

## Link
Checkout the blob example in Safari.
https://www.react-spring.io/docs/hooks/use-trail

## Environment

- One used in the documentation

**Comment by aleclarson** [comment]
Probably related to this:
https://bugs.webkit.org/show_bug.cgi?id=184601

> The issue here is that WebKit doesn't support references to SVG filters when doing "accelerated" filters.
