### ISSUE TITLE
useTransition notification-hub example doesn't work with v9.0rc3

### ISSUE THREAD

**Issue by gvocale** [react-spring/react-spring#1095]
I have upgraded react-spring to v9rc3 in the MessageHub example https://codesandbox.io/s/messagehub-lrxrb and it stopped working with the error:
```
Cannot read property 'life' of undefined
```

**Comment by aleclarson** [comment]
The v9-compatible version of that example is found here:
https://github.com/react-spring/react-spring-examples/blob/v9/demos/hooks/notification-hub/index.js
