### ISSUE TITLE
Setting State in onStart starts animation again

### ISSUE THREAD

**Issue by arturhenryy** [react-spring/react-spring#1111]
So i have an animation for a button that should turn into a loading bar which has multiple steps of animations implemented with useString. Once the step happens which animates the loading bar from initial width to 100% width there should be a an animation inside the button happening which is a counter for the % which gets interpolated from the width of the button.
this animation of the percent should only be visible when this animation starts. So i assumed i set a state for that in the onStart Callback, but this causes the animation to start again once onStart is called. What am i doing wrong and would there be a smarter way to do trigger that animation of the counter once the width animation starts? Thx

```
  const [showPercentAnimation, setShowPercentAnimation] = useState(false);

  const buttonAnimationProps = useSpring({
    ref: buttonSpringRef,
    to: async (next) => {
      await next({ width: `${31}%`, backgroundColor: "#739FBC", config: { duration: 350 } });
      await next({ width: `${5}%`, backgroundColor: "#0B64A0", config: { duration: 250 } });
      await next({ left: "0%", config: { tension: 1050, friction: 100 } });
      await next({
        width: `${100}%`,
        onStart: () => setShowPercentAnimation(true),
        config: { tension: 200, friction: 180 },
      });
    },
    from: { width: "25.5%", left: "100%", backgroundColor: "#0B64A0" },
  });
```

```
 <AnimatedButton
          css={[styles.btn(), vinBtn]}
          onClick={() => onClickSearchVin()}
          onKeyUp={(e) => onKeyUpEnterSearchVin(e)}
          variant={EButtonVariant.BlueBlue}
          style={buttonAnimationProps}
        >
          <div css={styles.btnContentContainer()}>
            <animated.div css={styles.vinBtnCounter()}>
              {showPercentAnimation && buttonAnimationProps.width.interpolate((val) => Math.floor(parseFloat(val)))}
            </animated.div>
          </div>
</AnimatedButton>
```

**Comment by aleclarson** [comment]
In v9, you can wrap the `to` function with `useCallback` to prevent re-renders from restarting the animation.

**Comment by arturhenryy** [comment]
Ok thanks for the info, i think this part of the changelog is misleading than

"Additionally, async animations are no longer cancelled when the props are updated. Async chains (eg: to: [{}, {}]) are never cancelled, even if another chain begins. Async scripts (eg: to: async () => {}) are only interrupted when another script or chain begins."

**Comment by aleclarson** [comment]
Indeed thank you for pointing that out!

**Comment by arturhenryy** [comment]
@aleclarson can you point me to some documentation regarding that useCallback usage with react-spring in v9?

**Comment by aleclarson** [comment]
That's another part that I forgot to include. Here's an explanation from another issue:

> In v9, that example will call the async `to` function on every render (even if `reset: true` is removed), because your `to` prop is a new function each time. To avoid that, you can do one of these 3 things:
> 
>   * wrap the `to` prop with `useCallback`
> 
>   * pass a props function to `useSpring` (instead of a props object)
> 
>   * pass an array of dependencies that tells `useSpring` when to update its animation
> 
> 
> ```ts
> // with useCallback:
> const { ... } = useSpring({
>   to: useCallback(async next => {...}, []),
> })
> 
> // with a props function:
> const [{ ... }] = useSpring(() => ({
>   to: async next => {...},
> }))
> 
> // with dependencies:
> const { ... } = useSpring({
>   to: async next => {...},
> }, [])
> ```
> 
> ## Examples
> 
> To animate **once** from 0 radians to 2π radians, use this:
> 
> ```ts
> const { radians } = useSpring({
>   to: { radians: 2 * Math.PI },
>   from: { radians: 0 },
>   config: { duration: 7000 },
> })
> ```
> 
>  
> 
> To animate **on every render** from 0 radians to 2π radians, add `reset: true` to the previous example:
> 
> ```ts
> const { radians } = useSpring({
>   to: { radians: 2 * Math.PI },
>   from: { radians: 0 },
>   config: { duration: 7000 },
>   reset: true,
> })
> ```
> 
>  
> 
> To animate **repeatedly** from 0 radians to 2π radians, use this:
> 
> ```ts
> const { radians } = useSpring({
>   to: useCallback(async next => {
>     while (true) {
>       await next({ 
>         radians: 2 * Math.PI,
>         reset: true,
>       })
>     }
>   }, []),
>   from: { radians: 0 },
>   config: { duration: 7000 },
> })
> ```
> 
> ### `useLoop` hook
> 
> If you're using `while` loops in `to` functions a lot, you could make a `useLoop` hook:
> 
> ```js
> const useLoop = (to, deps = []) =>
>   useCallback(async next => {
>     while ((await to(next)) !== false) {}
>   }, deps)
> 
> const { radians } = useSpring({
>   to: useLoop(async next => {
>     await next({ 
>       radians: 2 * Math.PI,
>       reset: true,
>     })
> 
>     // Return false to stop the loop. (optional)
>     return false
>   }),
>   from: { radians: 0 },
>   config: { duration: 7000 },
> })
> ```
> 
> With a little more code, the `useLoop` hook could take a props object or an array of props:
> 
> ```js
> // Animate from 0 radians to 2π radians forever.
> to: useLoop({
>   radians: 2 * Math.PI,
>   reset: true,
> })
> 
> // Animate between "blue" and "red" forever.
> to: useLoop([
>   { color: 'blue' }, 
>   { color: 'red' },
> ])
> ```

**Comment by arturhenryy** [comment]
thanks for clarification. One last question. This seems to not work when
there is a parent Component which updates the state.
 In the parent component i do something like this:

  const setEntries = useCallback(() => {
    setTimeout(() => {
      setDatabaseEntries(["Apples"]);
    }, 2000);
    setTimeout(() => {
      setDatabaseEntries(["Bananas"]);
    }, 2000);
  }, []);

to trigger a useTransition when one of the springs is starting.
  const headlinePropsAlternative = useSpring({
    from: { opacity: 0 },
    onStart: () => setEntries(),
    to: useCallback(
      async (next) => {
        await next({ opacity: animationToggled ? 1 : 0, delay: 1100 });
      },
      [animationToggled]
    ),
  });

Although all springs in the child component have their to method wrapped in
useCallback, the change of state inside setEntries cause a restart of the
animation.

Am Di., 11. Aug. 2020 um 15:27 Uhr schrieb Alec Larson <
notifications@github.com>:
