### ISSUE TITLE
Probably a bug on mobile Chrome

### ISSUE THREAD

**Issue by Vini98br** [react-spring/react-spring#1112]
![4a1j4t](https://user-images.githubusercontent.com/48522066/89718081-c44c2a80-d992-11ea-8e7c-12d11d3aa302.gif)

White space on the bottom of the page when I scroll down.

Someone know do i can fix that?

**Comment by aleclarson** [comment]
I don't think this is the fault of `react-spring`?

You could try asking on the new Discord server:
https://twitter.com/0xca0a/status/1292188915668062210
