### ISSUE TITLE
useTransition initial config

### ISSUE THREAD

**Issue by nicolazj** [react-spring/react-spring#1117]
## 🐛 Bug Report

i want to use useTransition , and also skip animation for initial element, so i pass initial:null to config,
the first animation will be buggy. however animations after that work fine.

## To Reproduce

https://codesandbox.io/s/dazzling-rain-x5sdi?file=/src/App.js

click on "1" to trigger animation.

<img width="355" alt="Screen Shot 2020-08-17 at 4 29 41 PM" src="https://user-images.githubusercontent.com/1446380/90357773-3a921080-e0a8-11ea-9bb8-8c5e6e3ed9ca.png">

## Expected behavior

"1" should slide out to the left while "2" slides in

**Comment by nicolazj** [comment]
just found a workaround/hack

adding opacity fixes this issue.

```
from: { opacity: 0, transform: forward ? 'translate3d(100%,0,0)' : 'translate3d(-100%,0,0)' },
   enter: { opacity: 1, transform: 'translate3d(0,0,0)' },
    leave: { opacity: 0, transform: forward ? 'translate3d(-100%,0,0)' : 'translate3d(100%,0,0)' },
```

**Comment by aleclarson** [comment]
> dont know why % matters.

Because animating between different units is unsupported (#643).
