### ISSUE TITLE
Message Hub: after migration from Transition usage to useTransition issue with infinity rerendering

### ISSUE THREAD

**Issue by Gorett** [react-spring/react-spring#1120]
## 🤓 Question

I'm trying to update my react-spring version. I faced with infinity re-rendering issue. Does anyone know what can be the reason? It happens only when I show second notification. First one works correctly.

`export default { show: () => {} };`

`const MessageHub = ({ children }) => {
	const [cancelMap, setCancelMap] = useState({});
	const [items, setItems] = useState([]);

	useEffect(
		() => children(message => setItems([...items, { key: Math.random(), ...message }])),
		[],
	);

	const remove = item => setItems(items.filter(i => i.key !== get(item, 'key')));
	const myConfig = (item, state) =>
		state === 'leave' ? [{ duration: 5000 }, spring, spring] : spring;
	const leave = item => async (next, cancel) => {
		setCancelMap({ ...cancelMap, [item.key]: cancel });
		await next({ life: 0 });
		await next({ opacity: 0 });
		await next({ height: 0 }, true);
	};

	const handleCancelClick = item => {
		if (cancelMap[item.key]) {
			cancelMap[item.key]();
		}
	};

	const transitions = useTransition(items, item => item.key, {
		from: { opacity: 0, height: 0, life: 1 },
		enter: { opacity: 1, height: 'auto' },
		leave,
		onRest: remove,
		config: myConfig,
	});

	return (
		<div className={styles.container}>
			{transitions.map(({ key, item, props: { life, ...style } }) => (
				<animated.div key={key} className={styles.message} style={style}>
					<div className={`${styles.content} ${styles[item.type]}`}>
						<animated.div
							className={styles.life}
							style={{ right: life.interpolate(l => `calc(${l * 100}%)`) }}
						/>
						<p>{item.text}</p>
						<button className={styles.button} onClick={() => handleCancelClick(item)}>
							<CloseIcon height="20" width="20" />
						</button>
					</div>
				</animated.div>
			))}
		</div>
	);
};`

`const MessageHubHOC = () => {
	const ref = useRef(null);
	notifications.show = message => ref.current(message);

	return (
		<MessageHub>
			{elem => {
				ref.current = elem;
			}}
		</MessageHub>
	);
};`

**Comment by TriStarGod** [comment]
@Gorett I got it working by replacing the config function with config: `(item, state) => state === 'leave' ? {...config, duration: timeout } : config;` I don't even understand how the previous array config was suppose to be used based on the src code. 

 - https://codesandbox.io/s/react-spring-messagehub-048q1?file=/src/index.js
