### ISSUE TITLE
useSpring returns an empty object when passing a ref.

### ISSUE THREAD

**Issue by Artmann** [react-spring/react-spring#1137]
## 🐛 Bug Report

When passing a ref to the `useSpring` hook, the object returned from the hook is empty.

## To Reproduce

```
const ref = useRef();
const props = useSpring({
  opacity: 1,
  ref
});

// props => {}
```

## Expected behavior

```
const ref = useRef();
const props = useSpring({
  opacity: 1,
  ref
});

// props => { opacity: AnimateValue }
```

## Link to repro (highly encouraged)

https://codesandbox.io/s/floral-water-ev31v?file=/src/App.js

## Environment

- `react-spring` v8.0.27
- `react` v16.13.1

**Comment by aleclarson** [comment]
This is likely fixed in v9: #985
