### ISSUE TITLE
Question about `1 - 0.998` in the source code.

### ISSUE THREAD

**Issue by facundocabrera** [react-spring/react-spring#1138]
Hey! First, thanks for reading ❤️

I'm taking a look on the code to see how it works and I found no documentation about the following operation:

https://github.com/react-spring/react-spring/blob/10999a996a5007f16c1e95f44c0cc8055215e525/src/animated/FrameLoop.ts#L61

Is there any implementation detail regarding `1 - 0.998`? I guess it is just a number precision thing, but I'm not 100% sure about it.

Any help will be really appreciated.

**Comment by aleclarson** [comment]
That's for decay animations (think scrolling deceleration).

Its purpose is more obvious in the v9 codebase:
https://github.com/react-spring/react-spring/blob/e53fbfb55e2fc9856bc8fe92ffa9c6f0e27fd1ca/packages/core/src/SpringValue.ts#L182-L192

**Comment by facundocabrera** [comment]
Thanks a lot for your time answering my question ❤️
