### ISSUE TITLE
[v9.0.0-rc.3] useTransition - Getting a Cannot destructure property 'ref' of 'props' as it is null.

### ISSUE THREAD

**Issue by tcherokee** [react-spring/react-spring#1139]
## 🐛 Bug Report

When I trying to use useTransition with react-spring v9 RC3 to animate a background, however, I keep getting a `Cannot destructure property 'ref' of 'props' as it is null.`.

## To Reproduce

See link in the Repro section

## Expected behavior

I expected the useTransition animation to run to at the minimum for the code to compile without errors.

## Link to repro (highly encouraged)

[My CodeSandbox demo](https://codesandbox.io/s/confident-leavitt-5fxej)

## Environment

- `react-spring` v9.0.0-RC.3
- `react` v16.13.1

**Comment by Manuel-777** [comment]
Same here, is there a workaround? tested on rc2 and it is the same, going back to v8 is too breaking to rollback.

**Comment by aleclarson** [comment]
The `useTransition` hook has changed in how you use it. See here: https://aleclarson.github.io/react-spring/v9/breaking-changes/
