### ISSUE TITLE
Statics prevents tree-shaking

### ISSUE THREAD

**Issue by Andarist** [react-spring/react-spring#206]
While all statics prevent the tree-shaking at the moment I plan to change that in the near future by tweaking the babel transforms, I have already an old PR for this - https://github.com/babel/babel/pull/6963 but I need to revive it.

That being said it only has a chance to solve this problem for statics created with class properties syntax. I consider any other top-level static properties to be sort of an anti-pattern.

So in my opinion those:
```js
Keyframes.Spring = Keyframes.create(Spring)
Keyframes.Spring.to = states => Keyframes.Spring(states, interpolateTo)
Keyframes.Trail = Keyframes.create(Trail)
Keyframes.Trail.to = states => Keyframes.Trail(states, interpolateTo)
Keyframes.Transition = Keyframes.create(Transition)
```
should be refactored and exposed as separate exports, not attached to the `Keyframes` class.

**Comment by drcmda** [comment]
This could be a new major release. I wonder though how, you mean KeyFramesSpring, KeyFramesSpringTo, KeyFramesTrail, KeyFramesTrailTo, etc?

Or should be simply expose the create function and be done with it?

**Comment by Andarist** [comment]
> This could be a new major release. I wonder though how, you mean KeyFramesSpring, KeyFramesSpringTo, KeyFramesTrail, KeyFramesTrailTo, etc?

That is definitely one way to go. This would imho be "the best" option because the users would be able to just pick what they import and wouldnt get the whole Keyframes "bundle" by default.

> Or should we simply expose the create function and be done with it?

I guess that would increase the complexity (for the user) quite a bit.

Alternatively if you like the current API you might want to experiment with smth like this:
```js
class Keyframes extends React.PureComponent {
  static create = primitive => (states, filter = states => states) => {
    if (typeof states === 'function' || Array.isArray(states))
      states = { [DEFAULT]: states }
    const fn = props => (
      <Keyframes
        primitive={primitive}
        states={states}
        filter={filter}
        {...props}
      />
    )
    fn.to = states => primitive(states, interpolateTo)
    return fn
  }
  
  static Spring = Keyframes.create(Spring)
  static Trail = Keyframes.create(Spring)
  static Transition = Keyframes.create(Transition)
}
```

**Comment by drcmda** [comment]
i think it even used to be like that, but one rollup version couldn't compile it, so i changed it. Maybe it was just a fluke - but i'd gladly pick that solution.

**Comment by aleclarson** [comment]
Closing since the `Keyframes` API is deprecated
