### ISSUE TITLE
Implement Transitions Hook

### ISSUE THREAD

**Issue by ruggedy** [react-spring/react-spring#320]

**Comment by drcmda** [comment]
I was trying to get issuehunt to fund this ... still am :-)

**Comment by tpae** [comment]
when is this going to be available?

**Comment by drcmda** [comment]
Today, and not just transitions ... :-)

We'll announce this stuff later this day: https://twitter.com/0xca0a and Johns https://twitter.com/johnadetutu93

**Comment by yuchi** [comment]
This can definitely be closed :)
