### ISSUE TITLE
width: 'auto' -> Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by dschu-lab** [react-spring/react-spring#346]
Hi,
I'm using `styled-components` in combination with `react-spring`, which works great, except when I want animate `auto`.

## Reproduction

https://codesandbox.io/s/zklq7qp3j4

## Expected Behavior
Animated width property

## Actual Behavior
React crashes with `Cannot read property 'style' of undefined`

**Comment by drcmda** [comment]
That is strange indeed. I think styled-components use ref forwarding now, so it could have something to do with that one. Will look into it.

**Comment by drcmda** [comment]
@dschu-lab  sorry it took so long, the reason wasn't styled-components, you returned an array in the transition and fixAuto couldn't handle that case, it was expecting a node. It's fixed, will make a release later on, for now: react-spring@7.2.8-beta.1

**Comment by dschu-lab** [comment]
@drcmda Thank you for taking the time debugging this!
