### ISSUE TITLE
Runtime error with d3.arc generated path

### ISSUE THREAD

**Issue by nerik** [react-spring/react-spring#347]
See example: 
https://codesandbox.io/s/xop230om1q

There are two tests datasets that go through a d3 arc layout to generate a SVG path instructions string. Both render correctly individually, but transitioning between SVG shapes (click on the chart to test) produces the following error:
```
Uncaught TypeError: Cannot read property 'push' of undefined
```
Emitted at this line, I believe: 
https://github.com/drcmda/react-spring/blob/1e8753ff72fa8a686f4d81dba3f6bd4ae53612aa/src/shared/interpolation.js#L51

As far as I see the path instruction strings are valid (no NaN values or anything). 

Sorry if I'm missing anything obvious. And keep up the good work, this is an amazing lib 🙏

**Comment by drcmda** [comment]
Checked the data and it looks fine to me as well. Interpolating svg paths only works though if the structure is the exact same, meaning same amount of points. If that isn't the case you should get a dedicated svg interpolator like d3's or flubber and use it in react-springs interpolate.

**Comment by nerik** [comment]
Thanks for the answer and sorry for the delay. I wasn't aware that a d3 path generator could generate shapes with a different number of points depending on the input value. In my case that was fixed by ensuring that the `outerRadius` of a `d3.arc` is always superior to its `innerRadius`:

https://codesandbox.io/s/9j482pp3no
