### ISSUE TITLE
Typescript react-spring/dist/addons

### ISSUE THREAD

**Issue by smdern** [react-spring/react-spring#357]
This isn't an issue, but I wanted to add a solution for getting typescript to resolve Parallax or any other addons that may live in `dist/addons` in the future.

Declare the following in `global.d.ts` at your project root or you can do what I did, which was create `types/react-spring-addons.d.ts`, and then include the file in `tsconfig.json` e.g. `"files": ["types/react-spring-addons.d.ts"]
`

```
declare module 'react-spring/dist/addons' {
  import { Parallax, ParallaxLayer } from 'react-spring'
  export { Parallax, ParallaxLayer }
}
```

**Comment by Kovensky** [comment]
I am working on a PR for types for the hooks and I had to solve this problem as well while doing it, so if I get this thing to work it'll probably be fixed in react-spring soon 👍

**Comment by Kovensky** [comment]
It's fixed as of the currently published version (can import `react-spring/addons`) :tada:

**Comment by smdern** [comment]
Oh that's awesome! I'm going to close this issue then since it should just work according to the existing docs.
