### ISSUE TITLE
onRest is not called for immediate animations

### ISSUE THREAD

**Issue by jacobrask** [react-spring/react-spring#362]
I would expect either neither onStart or onRest, or both, be called with an immediate animation. Instead only onStart is called. This causes some issues in our application because I want to render the content slightly differently (lower quality images) if we are currently in an active animation. If I `setState({ isAnimating: true })` in `onStart` it will not be reset if the animation is was in `immediate` mode.

    <Spring
      immediate
      from={{ height: 10 }}
      to={{ height: 100 }}
      onStart={() => console.log("start")}
      onRest={() => console.log("rest")}
    >
      {({ height }) => <div style={{ background: "hotpink", height }} />}
    </Spring>

[![Edit 8lzp570382](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8lzp570382)

**Comment by drcmda** [comment]
That's generally a hard call, theres some async stuff that relies on a started spring to conclude, for instance keyframes or now useChain. If a spring could just "do nothing" when started, promises would potentionally never finish. Do you need it for something particular?
