### ISSUE TITLE
items not dismounted in useTransition

### ISSUE THREAD

**Issue by einarlove** [react-spring/react-spring#377]
Encountered some bugs trying to convert my `<Transition>` to `useTransition`. Tried to remove most of my code to find the bug but couldn't make it behave correctly. (Un)luckily it seems it's also failing in the CodeSandbox examples.

https://codesandbox.io/embed/1y3yyqpq7q

If you look in the DOM, the pages are not dismounted. Just fades to opacity: 0 while more and more pages are mounted.

**Comment by drcmda** [comment]
This was fixed today (7.1.1).

**Comment by einarlove** [comment]
I'm no `react-spring@7.1.1` 😭

**Comment by einarlove** [comment]
I forked and updated the CodeSandbox to use `7.1.1`. Does not work. https://codesandbox.io/s/vvlx67m375

**Comment by drcmda** [comment]
You're right ... weird. We just had this issue. Hand in there. :-) 

CC @ruggedy

**Comment by ruggedy** [comment]
Gonna have a look

**Comment by drcmda** [comment]
Thanks @ruggedy ! Released a patch: 7.1.2

**Comment by ruggedy** [comment]
resolved by #378

**Comment by desmap** [comment]
@drcmda @ruggedy this bug seems to be back, check https://codesandbox.io/s/98j711344o and observe `class='bg'` in the Inspector. It doesn't get unmounted. I bumped react-spring to v7.2.7 in this Sandbox.
