### ISSUE TITLE
react-spring needs a logo, help wanted

### ISSUE THREAD

**Issue by drcmda** [react-spring/react-spring#379]
If anyone with some design skills would like to help out making the react-spring brand look good we would love to credit/link you on the GH front for it.

**Comment by afnizarnur** [comment]
Hi @drcmda! I'm interested to help to design the react-spring brand.
Can you please tell me brief of the logo?

**Comment by will-stone** [comment]
Here's my first attempt:

<img src="https://user-images.githubusercontent.com/654103/50047060-658fba00-00a6-11e9-81f4-9989e560513b.png" width="100" height="199.5" />

Let me know if you'd like the SVG/Affinity-Designer files.

**Comment by drcmda** [comment]
@afnizarnur It would be totally up to your creativity. I've tried lots of variations in Sketch but couldn't find a single one. I guess if it's a cool looking, simplistic icon, maybe has some meaning, and looks good next to the react-spring name, that'll be perfect.

@afnizarnur good start! that has me thinking ... how about doing the react logo with a slinky forming the atom shape?

**Comment by drcmda** [comment]
@mcernusca i really dig the second (grey one). I previously wrote something to the effect of "how about the react icon made with slinkies", but removed it because i tried in sketch and it looked like hell. But this might actually work ... 😄

**Comment by afnizarnur** [comment]
Hi @drcmda, this is what I have until now.

**Option 1**
What I first thought about react-spring, is that an animation that so smooth and fluid like water, and come up with this one.

![artboard](https://user-images.githubusercontent.com/4648648/50057995-d9b08780-01a4-11e9-86cd-a78cda328f60.png)

**Option 2**
Another iteration that come up in my mind is, keyword "spring", zig-zag, and the letter "S". Font is Overpass, which is used by Red Hat and open source.

![artboard copy](https://user-images.githubusercontent.com/4648648/50058019-26945e00-01a5-11e9-9973-acaed6cbfebf.png)

Let me know what you think! Hope you like the color 😅

**Comment by drcmda** [comment]
@afnizarnur i do! the colors are nice, too!

**Comment by afnizarnur** [comment]
Let me know what option you want to go ahead, 
then I'll provide the logo assets for you :)

**Comment by haikyuu** [comment]
@mcernusca i think your logos are awesome. And don't worry about animating them, it's possible to animate `SVG` 😄

**Comment by haikyuu** [comment]
take a look at https://codesandbox.io/embed/4zppn84yj4 for example

**Comment by drcmda** [comment]
that's a cool idea! @mcernusca could i get the svg for this?

**Comment by mcernusca** [comment]
@haikyuu good thought! 

@drcmda sure thing:
[react-spring-logo.zip](https://github.com/react-spring/react-spring/files/2695691/react-spring-logo.zip)
contains: react-spring-logo.sketch and react-spring-logo-icon.svg

Font for sketch file is InterUI https://rsms.me/inter 

As mentioned earlier this was just a conceptual sketch. Happy to play around with treatment, colors etc if we move in this direction. Others can feel free to take these files and play around too!

**Comment by drcmda** [comment]
I must say i dig the direction. I love @afnizarnur 's, too - but the idea of crossing a slinky with Reacts atom dot rings a bell. Not sure how @ruggedy feels about this, but i'd love to explore this with some drafts/colors. Or maybe even merge these ideas, like the typographic that @afnizarnur did (the slanted text looks nice)

**Comment by will-stone** [comment]
I thought I'd have another go. I hope you don't mind, @afnizarnur, but I took your designs for inspiration and incorporated them with my first idea.

![react-spring-2](https://user-images.githubusercontent.com/654103/50239207-751a4600-03b9-11e9-8e98-bcc9d0e8d7c3.png)

**Comment by amannn** [comment]
I also wanted to give it a go 🙂. It's based on the idea of @mcernusca that positions the nucleus of React in the middle of an actual spring.

![artboard copy 5](https://user-images.githubusercontent.com/4038316/50295941-93e01180-0479-11e9-8869-87b4696c3d23.png)

Here's another color variation:

![artboard copy 6](https://user-images.githubusercontent.com/4038316/50295942-9478a800-0479-11e9-9f09-9afbb3e5db33.png)

The font is [Ubuntu](https://design.ubuntu.com/font/).

**Comment by desmap** [comment]
Pls find below a quick black and white draft. **COLORS ARE MISSING!**. Setting the right color palette and finalizing the logo would be still a lot of work. Also missing: Motion lines, a light version, a dark version, the right font, the font's positioning and perfecting all shapes and proportions. If this a direction you could imagine, let me know and I would work on the missing stuff...

![image](https://user-images.githubusercontent.com/43666255/50344343-e62d3b00-052a-11e9-8a67-fb03af43a0bf.png)

**Comment by desmap** [comment]
Played around with some colors, it's super hard, I haven't found the palette where I am happy. Tested following color pair with a contrast of 3 (I think it's still too flat). But I'd tend to opt for a dark-background theme. IDK, maybe it's because it's about animation/motion (anime.js chose also a dark-background theme and it looks damn slick). 
However, whatever logo/design/key colors you guys choose, you need think about a new/consistent CI/CD which reflect this and covers the entire website, So, just changing the logo won't work.

![image](https://user-images.githubusercontent.com/43666255/50353410-79c13480-0548-11e9-98a7-328a52d07e23.png)

**Comment by picnich** [comment]
Hey everyone! Here’s my take on a logo for react-spring. I felt it was important to make the logo as simple and playful as possible, as I think it would help with approachability of the project. Hope you like it! 
![react-spring-logo-final](https://user-images.githubusercontent.com/12835863/50407118-082ef380-079f-11e9-84af-ebc84b5f51bd.png)

**Comment by mcernusca** [comment]
@drcmda Sorry this took so long. I finally had some time today to revisit the logo and try to merge some of the ideas and feedback presented so far. Here is where I landed:

![optb1](https://user-images.githubusercontent.com/31384/51132976-bad3fe00-1801-11e9-9087-389b5e5b0d6d.png)
I beefed up the strokes and the size of the nucleus so it can scale down comfortably and still be recognizable. If we prefer the smaller nucleus I think it should be fine to have different variations for different sizes too.

Some potential rendering and colors:
![optb2](https://user-images.githubusercontent.com/31384/51132974-bad3fe00-1801-11e9-8365-344749ea252a.png)
I couldn't find any way to invert the spring and still have it look good so we need some sort of container shape. I kind of dig keeping the existing vivid red brand color but if you're going to use that as a primary color on the website then maybe we should use a complementary color in the logo itself.

**Comment by drcmda** [comment]
@mcernusca i like it, simple and clean, has the react atom dot and a spring - let's go with it!

**Comment by JABedford** [comment]
Awesome work @mcernusca !! Love the coloured two on the right-hand side.

**Comment by mcernusca** [comment]
Hi all, I had a go at making this logo interactive. Feel free to fork and have a play:

[<img width="517" alt="screen shot 2019-01-22 at 3 15 51 pm" src="https://user-images.githubusercontent.com/31384/51562790-ad99bd80-1e58-11e9-95df-6bdfdfb82443.png">](https://codesandbox.io/s/l5mmo0kp7m)

Sketch file: [react-spring-logo-2.zip](https://github.com/react-spring/react-spring/files/2784418/react-spring-logo-2.zip)

**Comment by drcmda** [comment]
@mcernusca thats a cool idea! where can i reach you, do you twitter?

**Comment by brunolemos** [comment]
@mcernusca looks super cool man, great work!

I'm not sure if I prefer the text at the left or the bottom:

![react-spring-logo.gif](https://user-images.githubusercontent.com/619186/51572201-d12a2b80-1e8b-11e9-91d8-8621179f21a7.gif)

**Comment by mcernusca** [comment]
@brunolemos thanks! I agree, especially in this context. Updated link! Also included some feedback from Paul about limiting by radius instead of boxing the nucleus in which feels much better. That gave us a few extra pixels to move in so I made it bouncier to take advantage :)

**Comment by ahmedu007** [comment]
I love the fact we have a logo now. It does seem like a great idea to also animate it. It looks so nice on the gitHub page as well. I was thinking it would be cool if we can create something like:

`https://github.com/juliangarnier/anime/`

That globe is such a huge WOW factor 🕺

**Comment by mcernusca** [comment]
Good idea @ahmedu007 I'll play around with that and see what I can come up with!
