### ISSUE TITLE
Latest build (7.2.0) breaks server-side rendering

### ISSUE THREAD

**Issue by cecchi** [react-spring/react-spring#385]
Hi, it looks as though the latest build introduced debug code that relies on the DOM in `src/animated/FrameLoop.js`: https://github.com/react-spring/react-spring/commit/5af3f6bb1623cc3b36733518cdf71b8bf3e669db#diff-ca0fe0482065f1abd8b878839eb281ad

This is breaks server-side rendering/Node compatibility, as the package attempts to write to `window` at import time, resulting in this error:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/cecchi/Code/deal/consumer-app/node_modules/react-spring/web.cjs.js:1222:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

**Comment by drcmda** [comment]
whoops, that's left over debug code, released a small patch version to take this out

**Comment by cecchi** [comment]
🎉  Thank you!
