### ISSUE TITLE
TypeScript: SpringProps doesn't inherit from SpringBaseProps

### ISSUE THREAD

**Issue by bhollis** [react-spring/react-spring#386]
`SpringProps` (which is used from `Spring`) doesn't inherit from `SpringBaseProps`, and thus doesn't include properties like `native`. 

Code: https://github.com/react-spring/react-spring/blob/master/types/universal.d.ts#L67

**Comment by vpicone** [comment]
Now that this is set up, components that allow spring props (Trail, Keyframes and Transition) should all extend SpringProps. As it is now, these components can't use props that aren't SpringBaseProps (after, etc.)
![Trail props don't include after](https://user-images.githubusercontent.com/4078018/52136126-ff86d400-260c-11e9-8c08-7df61cad905a.png)

**Comment by aleclarson** [comment]
Fixed by e622f17471c49926424033d8c46c2f3c9e78059a
