### ISSUE TITLE
Error in UMD libary

### ISSUE THREAD

**Issue by du5rte** [react-spring/react-spring#388]
Hey, I've come across this error when using [web.umd.js](https://unpkg.com/react-spring@7.2.1/web.umd.js)

```
Uncaught ReferenceError: process is not defined
```

I'm guessing it caused by using `process.env.NODE_ENV`
```js
if (process.env.NODE_ENV !== 'production' && (v[0] < 16 || v[1] < 4)) {
  console.warn('Please consider upgrading to react/react-dom 16.4.x or higher! Older React versions break getDerivedStateFromProps, see https://github.com/facebook/react/issues/12898');
}
```

Found in these lines:
https://github.com/react-spring/react-spring/blob/48f8a3ab9e6a56ab29ee8a0c9c64a993ddc89e03/src/Spring.js#L9
https://github.com/react-spring/react-spring/blob/0219e9235fd79e79db5aa00baf5141a15b957e99/src/animated/AnimatedWithChildren.js#L16

This can be seen on my [codepen example](https://codepen.io/du5rte/pen/KrGjEm) where I had to insert a script in the header to fake the existance of a `process.env` .

```html
<script>
  window.process = {
    env: {
      NODEENV: 'development'
    }
  }
</script>
```

Is there a safer way to use `process.env` that won't break code when using the libary in the browser?

**Comment by drcmda** [comment]
Should be fixed in @7.2.2
