### ISSUE TITLE
Does react-spring uses FLIP animations?

### ISSUE THREAD

**Issue by desmap** [react-spring/react-spring#395]
Just found out that react-posed uses so called FLIP animations [1] for performance reasons. You can turn them off because it can create glitches (check this issue: https://github.com/Popmotion/popmotion/issues/672).

So, ...
1. Does react-spring also uses FLIP? I guess not, because the animation from issue above works flawlessly with react-spring, right?
2. Is FLIP worth, so does it really helps re performance or are there smarter ways?

[1] https://aerotwist.com/blog/flip-your-animations/

**Comment by drcmda** [comment]
In your case all you need to animate is opacity, there's nothing that would make it faster unless you set classNames raw in css.

As for flip in general, i'm kinda opposed to having too much magic in the lib. Height: "auto" is probably the most it'll do. Magic is great, in a demo, but then you run into edge cases. I would like to go the explicit route with react-spring, in the end you should know what you do and how it affects your views, without surprises. I guess it's a preference ...

**Comment by drcmda** [comment]
PS. That doesn't mean i'd ignore a proposal if there's one. If you have ideas and if it warrants a new primitive, shoot - we'll always listen.

**Comment by desmap** [comment]
Hey @drcmda, sorry for my late response and I agree with you: It's too much magic, I don't need such a feature. Just wanted to know your opinion on this topic. I'll close this now and if anyone wants FLIP they can open a new issue.

**Comment by morgs32** [comment]
@desmap we wrote a tiny library on `react-spring` to have FLIP animations. Just sharing: [react-spring-flip](https://github.com/stackshirts/react-spring-flip)
