### ISSUE TITLE
Adding CONTRIBUTE.md

### ISSUE THREAD

**Issue by WebDeg-Brian** [react-spring/react-spring#397]
Hi, I really want to contribute to this repo, but don't really know how to. Perhaps a CONTRIBUTE.md would help?
Thank you :)

**Comment by drcmda** [comment]
Sure, we're looking for contributions - what do you have in mind? There's no real guidelines for now, you can clone the repo and make PRs.

**Comment by WebDeg-Brian** [comment]
Sure thing @drcmda
