### ISSUE TITLE
useTransition loses track of element position when it's being removed

### ISSUE THREAD

**Issue by Kovensky** [react-spring/react-spring#399]
`useTransition` seems to lose track of item positions when they are removed and can apparently only deal with "first" and "not first". If any other element gets removed, it gets moved to the 2nd position and then transitioned to "leave".

Sandbox: https://codesandbox.io/s/r0onjmnwjm -- click on any button that's not one of the first two being displayed.

**Comment by drcmda** [comment]
@ruggedy could you take a look? Must be useTransition.js:calculateDiffInItems that's going off track somewhere.

**Comment by ruggedy** [comment]
already pushed a fix. should be available in the next patch.

**Comment by drcmda** [comment]
released as @7.2.5

**Comment by drcmda** [comment]
Looks godd, it works :-)

**Comment by Kovensky** [comment]
Looks like the fix for this broke something else 😆

Bug report incoming
