### ISSUE TITLE
useTransition with trail applies trail based on absolute item index instead of change index

### ISSUE THREAD

**Issue by Kovensky** [react-spring/react-spring#404]
Codesandbox: https://codesandbox.io/s/k5vnj04xor

Clicking element n1 starts its animation immediately, but clicking element n7 takes around 3s to animate. It's as if the `trail` is animating all elements, it's just that the non-affected elements have a "do nothing" animation.

However, if you click "add item" and then click on the freshly added items to remove them, they animate immediately. So I assume the elements on the first batch of 7 elements are, for some reason, saving their original trail delay and not recomputing for the next animation batch.

**Comment by Kovensky** [comment]
Yeah, they probably need to be computed from scratch on each update.

(Another potential neat feature (somewhat similar to regular spring/trail `reverse`?) is to have just the _direction_ of the trail be reverted. For example, if you do add 5 items and then remove 5 items, it could be useful to start the trail from the end.)

**Comment by ruggedy** [comment]
This has been resolved in 7.2.6
