### ISSUE TITLE
Need help with having a fixed navbar on a page with Parallax

### ISSUE THREAD

**Issue by laluvjohntx** [react-spring/react-spring#407]
I have a navbar that sits outside of Parallax. Currently, I am seeing two scroll bars appear on my browser with my navbar and the parallax section. Is it possible to have a navbar under Parallax that can stay fixed up top while the rest of the page scrolls down?

**Comment by deadaxis** [comment]
Here is the issue:
![image](https://user-images.githubusercontent.com/1617629/50463621-81bb1300-0952-11e9-8554-deea33cd42f6.png)

**Comment by drcmda** [comment]
Could you pour that into a codesandbox? Would be easier to inspect.

**Comment by laluvjohntx** [comment]
Hey, apologies for the delay, I was away from computers for a while haha. 
Here's the issue I am talking about:
https://codesandbox.io/s/6xv24w613

**Comment by laluvjohntx** [comment]
On chrome developer tools, if you switch that to a mobile view, you'll see that the jumbotrons would overlap. I am pursuing a solution where I could figure out what  the viewport is, and based on that, change the number of pages, and offset dynamically. Does that sound like an overkill for this one?

**Comment by drcmda** [comment]
yep, i think there's nothing else you can do. offset/parallax works with precise deltas, and once content keeps on pushing stuff out of a 100vh it will overlap. especially lengthy text content is hard to control responsively.

**Comment by laluvjohntx** [comment]
Thanks for the help! Closing this issue. Keep up the awesome work on this library!!
