### ISSUE TITLE
Transition works in dev when but fails silently in prod

### ISSUE THREAD

**Issue by stan-sack** [react-spring/react-spring#413]
I'm using a `<Transition />` component to animate the screens in a navigator for a create-react-app project. It all works fine when I run the project locally using `npm start` but when I build and deploy it to S3 there are no transitions between screens and no errors in the console.

Im using:
- `react@16.7.0`
- `react-dom@16.7.0`
- `react-spring@7.2.7`

The transition looks like this:

```
                <Transition
                    items={descriptor.getComponent()}
                    from={{ opacity: 0 }}
                    enter={{ opacity: 1 }}
                    leave={{ opacity: 0 }}
                >
                    {item => props => (
                        <div
                            style={{
                                opacity: props.opacity,
                                position: "absolute",
                                top: 0,
                                left: 0,
                                right: 0,
                                minHeight: "100%",
                                marginLeft: "64px"
                            }}
                        >
                            <SceneView
                                navigation={descriptor.navigation}
                                component={item}
                            />
                        </div>
                    )}
                </Transition>
``` 

I understand that you want a CSB but I don't see a lot of value given that the problem only occurs in production builds. Feel free to close this if you don't think it belongs here.

**Comment by ruggedy** [comment]
Hi, what happens when you run you production build on your computer, does it not work either?

**Comment by stan-sack** [comment]
@ruggedy yes, production build doesn't work on my computer either.

**Comment by ruggedy** [comment]
@stan-sack alright, can you help me out and create a minimum reproducible project on GitHub if possible, Because this sounds more like a build pipeline issue than an issue directly relating to the project. But just in case, I'll try debugging it for you.🙂🙂
