### ISSUE TITLE
How do I animate two different buttons depending upon state?

### ISSUE THREAD

**Issue by ankur1163** [react-spring/react-spring#414]
Hi, 
    I want to animate start/stop button in my app. Both are entirely different buttons. I want both to fade in when they appear. So, when i click start button, i want start button to disappear and stop button to appear with fade in animation. I have state which controls this button. 

I know that I have to use transition. But I am confused about toggle. I dont have items or array. Can someone tell me how do i do this?

```
<Transition
 
  from={{ position: 'absolute', opacity: 0 }}
  enter={{ opacity: 1 }}
  leave={{ opacity: 0 }}>
  {toggle =>
    this.state.startButton
      ? props => <div style={props}>😄</div>
      : props => <div style={props}>🤪</div>
  }
</Transition>
```
This only change smileys but with no animation

**Comment by drcmda** [comment]
Transition takes items, this can be a single object, a flag, whatever, or an array. The same object you give it above you will receive as a render prop below.
