### ISSUE TITLE
Ref for component inside <animated.div> is set to null at the end of show transition

### ISSUE THREAD

**Issue by donysukardi** [react-spring/react-spring#416]
I simulated spamming of toggle button click with a set of setTimeout. Eventually, when the component is shown, the ref for the children component inside the `<animated.div>` is set to `null` instead.

https://codesandbox.io/s/5kry5mlq2p

Nobody sane would probably do what I did 😁 , but I'd expect the ref to be reliably assigned at the end of transition.

**Comment by drcmda** [comment]
You can't use ref like that since you're dealing with a list, it will overwrite your value and since elements will unmount it will be null - as a racing condition. If you must keep track of items in React using useRef, the only way is using a set or a weakmap: https://codesandbox.io/embed/7mqy09jyq
