### ISSUE TITLE
Wrong height with auto and flexbox

### ISSUE THREAD

**Issue by Fakkio** [react-spring/react-spring#417]
Hi,

I have a strange behavior with auto height. As you can see in the codesandbox below, the height computation is wrong (I deliberately slowed down the animation to highlight the error) and then settle down at the end of the animation, when the value is actually set to `'auto'`. The strangest thing is that the issue comes and goes according to the text that is inserted in the `<h2>` tag.

https://codesandbox.io/embed/2zj3o3450p

**Comment by drcmda** [comment]
Easy fix, your auto-margin-3 class is too loosely defined for auto. Do this: `from={{ width: '100%', ` and it will work. Explanation: http://react-spring.surge.sh/gotchas#animating-auto

**Comment by Fakkio** [comment]
No no, that isn't the problem, that class shouldn't even be there. I've just removed it and the problem still there..

**Comment by drcmda** [comment]
i mean, you can give it a width: 100%, you can either do it by setting a class or dumping it into "from". Like so: https://codesandbox.io/s/31z8w5o0w5

**Comment by Fakkio** [comment]
Ah ok, so the problem was the parent missing the width property. I should have read your link before, sorry.
Problem solved.
