### ISSUE TITLE
Looping animations with "useKeyframes" does not work

### ISSUE THREAD

**Issue by AndreasFaust** [react-spring/react-spring#418]
Looping animations with "useKeyframes" does not work anymore in version 7.2.7.
The working example "KEYFRAMES RESET SCRIPT" (https://codesandbox.io/s/k2p403pkl5) uses version 7.1.0.

**Comment by taikn** [comment]
I've also noticed that using arrays in Keyframes doesn't interpolate values in latest version at all:
https://codesandbox.io/s/z3yrwxnjw3

**Comment by drcmda** [comment]
Still looking, btw, it works if you put reset and from into initialprops (useKeyframes.spring(fn, initialProps), but setting it in the function should also work of course.

**Comment by drcmda** [comment]
@AndreasFaust  @taikn This is fixed. useKeyframes does not exist any longer, springs can accept arrays and functions by default now while custom hooks can be used to toggle animation behaviour.

https://codesandbox.io/embed/141nrz6v73

https://codesandbox.io/s/8ypj5vq6m9?from-embed
