### ISSUE TITLE
<Trail> animating out when unmounting

### ISSUE THREAD

**Issue by alanbuchanan** [react-spring/react-spring#419]
I have a list of expandable items which, when clicked, reveal more information.

Here is the codesandbox: https://codesandbox.io/s/0v1prmxlv0

As you can see, I have a `<Trail>` inside a `<Spring>`. The Spring controls the changing height of each item. The Trails controls the items of each list item.

Everything works great apart from when the Trail animates out. It goes immediately instead of animating out. As in, I want the Trail to animate out in the reverse to how it came in. Is this possible with Trail?

I had a go at refactoring with `<Transition>` here: https://codesandbox.io/s/j79nwp113w
However as you can see I'm not getting any animation. 

What exactly am I doing wrong?

**Comment by drcmda** [comment]
Yes, trail has a "reverse" property, but to me it looks like you're unmounting the trail whole, in that case nothing can animate because it's gone. I would leave items mounted, trail them out, then close down (maybe using a delay).

**Comment by drcmda** [comment]
Btw here's an example doing exactly that: https://react-spring.github.io/examples (scroll down to where it says "panel keyframes"

**Comment by alanbuchanan** [comment]
Thanks, will take a look

**Comment by alanbuchanan** [comment]
Fixed my example by using `Keyframes`. Think this is the only way. BTW, `Keyframes` is fricking awesome. 🥇
