### ISSUE TITLE
Does react-spring work with facepaint (media queries)

### ISSUE THREAD

**Issue by desmap** [react-spring/react-spring#420]
I use different ways of handling media queries. I like [facepaint](https://github.com/emotion-js/facepaint) a lot, it has a super intuitive and minimal API. I guess it's not intended that this works with react-spring or does it? I did a quick [Codesandbox](https://codesandbox.io/s/rjkp71l92m) and could not get it to work.

**Comment by drcmda** [comment]
It depends what you're feeding it, react-spring, like facepaint, has an api. You're giving it an array, that contains an array, that contains two objects, each containing nested keys starting with media queries followed by some value. That doesn't make sense to the springs set function. A spring is not a style sheet, it just contains a bunch of numbers and values that are moving from x to y.

You need to know which media query you're in, `mq` doesn't tell you that. This is probably a better choice: https://github.com/streamich/use-media

**Comment by desmap** [comment]
Perfect and thanks for the hint!
