### ISSUE TITLE
Docs crashes when clicking on some submenus

### ISSUE THREAD

**Issue by brunolemos** [react-spring/react-spring#429]
`Whoops, we crashed`

![kapture 2019-01-09 at 21 10 32](https://user-images.githubusercontent.com/619186/50935445-2c532b80-1453-11e9-84b7-be74793a07ec.gif)

**Comment by sw-yx** [comment]
is this due to docz? theres probably some simple config we are missing?

**Comment by drcmda** [comment]
It could be, unfortunately i'm so deep into hooks overhaul right now, can't spend time on it until it's over with.

**Comment by drcmda** [comment]
switched it back to surge on the front page

**Comment by brunolemos** [comment]
I still have the same crashes fyi. Try clicking on any submenu from the Hooks menu

**Comment by jnsdls** [comment]
I fixed this crash in #451 because I kept running into it on local

**Comment by brunolemos** [comment]
@jnsdls thanks, that should be a separate pr, easier to merge

**Comment by jnsdls** [comment]
@brunolemons yeah, you’re right. I’ll pull it out into its own PR today

**Comment by jnsdls** [comment]
@brunolemos you're right, I pulled it out and have it here:
