### ISSUE TITLE
About updating dependency "react-spring" from the example "Horizontal paged parallax"

### ISSUE THREAD

**Issue by mozgbrasil** [react-spring/react-spring#431]
# About updating dependency "react-spring" from the example "Horizontal paged parallax"

Based on the following examples

https://github.com/react-spring/react-spring/tree/master/examples#codesandboxes-%EF%B8%8F

Accessing the "Horizontal paged parallax"

https://codesandbox.io/s/548lqnmk6l?from-embed

I clicked to update the dependency

"react-spring"

Note that the following "fork"

https://codesandbox.io/s/zqvlqmz2nm

But the example is not working after the update

Can you help me

![captura de tela de 2019-01-09 23-44-34](https://user-images.githubusercontent.com/17202780/50940595-b0fc7480-1468-11e9-9313-9d0192167cc9.png)

**Comment by drcmda** [comment]
You need to update react as well, forward ref came in react 16.3 i believe.

**Comment by mozgbrasil** [comment]
Good Morning

According to the images we see that the example does not work with the updated version of the library "react-spring"

![captura de tela de 2019-01-10 12-50-43](https://user-images.githubusercontent.com/17202780/50976223-96f97b00-14d6-11e9-976b-e7901b4ced44.png)
![captura de tela de 2019-01-10 12-50-52](https://user-images.githubusercontent.com/17202780/50976224-96f97b00-14d6-11e9-8123-a484874b2f6e.png)

**Comment by drcmda** [comment]
ahh sorry about that, it's not /dist/addons, it's straight /addons. this was a change made in 7.x and the sandboxes are outdated. i will update them, already tried, too and they run.

**Comment by mozgbrasil** [comment]
Thank you my friend
