### ISSUE TITLE
Can't use useTrail with useChain

### ISSUE THREAD

**Issue by jmcruzmanalo** [react-spring/react-spring#432]
Reproduction: https://codesandbox.io/s/619qw0xxxz

App crashes, and there is an error on the console but it doesn't seem to be very helpful.
I ran into this on my local project and I was getting a "Cannot read property 'stop' of undefined" error if that helps.

**Comment by drcmda** [comment]
Thanks, will take a look.

**Comment by jmcruzmanalo** [comment]
I agree, and I ran into it chaining multiple ones but I wanted to isolate it.

**Comment by drcmda** [comment]
Rewriting hooks from the ground up currently. There were lots of wires thrown about that made inspection hard. It looks very promising already and i think when it's out i will remove the experimental status and make hooks official.

**Comment by aleclarson** [comment]
Fixed in #632
