### ISSUE TITLE
reset and initial props doesn't work with useTransition

### ISSUE THREAD

**Issue by b00sta** [react-spring/react-spring#436]
Seems like `reset` and `initial` props doesn't work with useTransition as expected. Try to comment out it [here](https://codesandbox.io/s/64r6vkkzqr). I guess, bug with `initial` prop related to wrong initial state at this line https://github.com/react-spring/react-spring/blob/f938b667860da1ace2f13523ea7aae5a9ba2a320/src/hooks/useTransition.js#L146

**Comment by drcmda** [comment]
Yep, saw this today, too, it's the reverse. I am re-writing hooks from the ground up currently, there will be a big update soon.

**Comment by aleclarson** [comment]
Please provide a CodeSandbox if this is still an issue. Thanks! 👍

**Comment by aleclarson** [comment]
What is `reset: true` supposed to do when used with `useTransition` and `initial: null`?

Here's an updated sandbox: https://codesandbox.io/s/7j60194o26

**Comment by aleclarson** [comment]
Fixed in #632 🎉 

When `reset` is true, all items will repeat their `enter` transition.

**Comment by aleclarson** [comment]
Fixed in #632 🎉 

When `reset` is true, all items will repeat their `enter` transition.

The `initial` transition never repeats, even if `reset` is true.
