### ISSUE TITLE
better docs hosting

### ISSUE THREAD

**Issue by sw-yx** [react-spring/react-spring#438]
Hello!

currently the github hosting is kinda buggy: 

![image](https://user-images.githubusercontent.com/6764957/51049289-49d2e300-1582-11e9-9ba7-8747be4972bc.png)

and direct links dont work:

![image](https://user-images.githubusercontent.com/6764957/51049310-5a835900-1582-11e9-9ba0-f282623146fd.png)

you can probably fix this in github but just wanted to also suggest hosting on Netlify :) (i work there)

**Comment by brunolemos** [comment]
Related: #429

**Comment by drcmda** [comment]
yep, i noticed, GH doesn't support SPAs :-( i used surge before, but one of these twitter demos made it explode. But i'll probably switch back to it for now.

**Comment by drcmda** [comment]
should be fixed (for now)
