### ISSUE TITLE
Nested `Trail` inside a `Transition` rendering issue

### ISSUE THREAD

**Issue by alanbuchanan** [react-spring/react-spring#444]
Here is the sandbox in question: https://codesandbox.io/s/pjj926zjjx

The button opens a small menu (animated in and out with `Transition`) with a few items (animated in and out with `Trail`). The problem is with the `Trail`. Notice that when you open the menu for the first time, the trail animates in as expected. However, when you close and reopen in a short space of time, the trail doesn't correctly animate in. This gif should explain it:

![menubug1](https://user-images.githubusercontent.com/10364894/51091897-fbdbfc00-1788-11e9-8ac5-df61baa90367.gif)

I was hoping the presence of `unique` and/or `reset` props passed into the `Trail` would fix this (by the way this fixes animation issues on the `Transition`). The result is quite interesting. I don't think `unique` changes anything, but `reset` waits for the parent `Transition` animation to finish before beginning its own animation. This gif should explain it:

![menubug2](https://user-images.githubusercontent.com/10364894/51091899-026a7380-1789-11e9-8b32-f17b84104259.gif)

I'm sure there are good reasons for the above behaviour but I can't figure it out. Is there a way I can get the nested `Trail` to animate in consistently?

**Comment by drcmda** [comment]
unique retains the original item, so even if it fades out and you click again it takes it back and re-uses it. can't explain the delay right now, but this is what i am reworking atm to make these things more deterministic.

here's a fixed version the way i would do it: https://codesandbox.io/s/5mvp1m5zo4

**Comment by alanbuchanan** [comment]
Thanks @drcmda, can I just confirm the only difference is the usage of the `delay` prop in the `<Trail>`?

**Comment by drcmda** [comment]
i've made the modal position: absolute as well, so that enter and leave transitions can render overlaid.
