### ISSUE TITLE
No initial type for Transition spring config?

### ISSUE THREAD

**Issue by mooman65** [react-spring/react-spring#445]
Under the 'config' prop for the Transition component (https://react-spring.surge.sh/transition#/props), I notice it only says it supports 'enter', 'leave' or 'update' types.  Is there no option to specify a config that applies just for the 'initial' animation?

My use case for this is as follows: I have a list of items popping in when a page loads.  I'd like to delay that initial loading of items so it doesn't happen while the rest of the content of the page is loading (to minimize framerate issues).  Now I also have the ability to toggle individual visibility of these items, and I *don't* want it to use that delay in that case, as it should be as responsive as possible to the user clicking the visibility toggle buttons.

I realize I could just implement this outside of react-spring's scope, controlling when the Transition itself is added, but I'm just curious to know if there's a... cleaner way to do this (?) by just adding a delay to the initial animation.  Thanks!

**Comment by drcmda** [comment]
It exists, it's called `initial`.

**Comment by mooman65** [comment]
![image](https://user-images.githubusercontent.com/6099186/51450757-d8234200-1d96-11e9-9e5b-bf58d8f78ae6.png)

So `initial` is supported even though the docs do not mention it?

**Comment by drcmda** [comment]
I think i got this wrong, i was assuming you meant 

<img width="847" alt="screenshot 2019-01-26 at 23 40 51" src="https://user-images.githubusercontent.com/2223602/51793642-db1d9880-21c3-11e9-97a4-4dd73e705d80.png">

I think adding initial to this makes sense. I'll take a look ...

**Comment by drcmda** [comment]
ok, added it to the hooks release. will cherry pick this into the render props export as well.

**Comment by aleclarson** [comment]
@drcmda Has this been cherry picked then?
