### ISSUE TITLE
React-spring `Keyframes` seems to add implicit delay

### ISSUE THREAD

**Issue by alanbuchanan** [react-spring/react-spring#446]
My question pertains to two sandboxes of the same basic animation. One uses Spring and the other uses Keyframes.Spring.

Spring version: https://codesandbox.io/s/189kvwk3p3

Keyframes version: https://codesandbox.io/s/wz6nnyomvl

The only difference is that in the Keyframes version, there is a short delay before the animation starts.

Why is this and how can I prevent it?

**Comment by drcmda** [comment]
keyframes is async and fires after the first render passes. though it does look a little too long to be sure. i'm in the middle of a complete refactor of all the async logic atm, for just this reason - some things get very hard to trace. i hope i will come out of it with better results.
