### ISSUE TITLE
useImperativeMethods → useImperativeHandle

### ISSUE THREAD

**Issue by phaistonian** [react-spring/react-spring#447]
It seems the latest `next` react version replaced `useImperativeMethods` with `useImperativeHandle `.

This is causing `useTransitions` (at least) to break.

**Comment by j8seangel** [comment]
Yes, I was having the same issue and this is the commit included in the latest alpha.1 version.
https://github.com/facebook/react/commit/b4ad8e947150a1a0b486a388e2d4762d3eee51ee

Fixed using react `16.8.0-alpha.1` for now

**Comment by drcmda** [comment]
could you submit a quick PR? i am in the middle of a refactor and wouldn't want to mess with the local state.

**Comment by jnsdls** [comment]
also breaks `useSpring` and `useSprings`

@drcmda I'll have a PR for you in a minute here

**Comment by jnsdls** [comment]
It’s proving more complicated than expected. (Not as simple as just switching out the function names and calling it a day.)

*so disregard the “in a minute” part of my previous comment*

**Comment by jnsdls** [comment]
@drcmda I have that PR now: https://github.com/react-spring/react-spring/pull/451

**Comment by Jessidhia** [comment]
`const { useImperativeHandle = React.useImperativeMethods } = React` _should_ be sufficient 🤔

**Comment by BenoitZugmeyer** [comment]
For those stumbling on this issue, here is a quick solution before a proper react-spring fix is landing.

In your App entry point, just add:
```js
import React from 'react'
React.useImperativeMethods = React.useImperativeHandle
```

**Comment by JimmyRowland** [comment]
`const { useImperativeHandle = React.useImperativeMethods } = React` 
is not working for me.
8.0.0-beta.3 works fine, but I am using parallax for a different component and parallax no longer exists under 'react-spring/addons. Is parallax bugged because of the new react update?

**Comment by JimmyRowland** [comment]
Thanks for the update, but parallax is still not working.
Here is the error message:
https://codesandbox.io/s/z32qz2n69p

**Comment by drcmda** [comment]
some export missing, will fix it

**Comment by phaistonian** [comment]
@drcmda Will this change in export land in `b5` or it applied already?

**Comment by drcmda** [comment]
@JimmyRowland fixed the export, it looks good now: https://codesandbox.io/s/48r42p59o7 just keep in mind, you can't mix any exports, like using "animated" from react-spring in react-spring/renderprops-xxxx. they are separate libraries.

@phaistonian beta.5, correct

**Comment by drcmda** [comment]
what i love about hooks is that it doesn't need so many abstractions and addons. just like "auto" we don't need it, because measuring with hooks is dead simple. parallax is basically just a scrolltop interpolation: https://codesandbox.io/embed/py912w5k6m or https://codesandbox.io/embed/ojy9902z15 i would rather like to study these cases more to see if we can make interpolations more versatile.

**Comment by brunolemos** [comment]
`useImperativeHandle` should be released now that hooks stable is available.

**Comment by brunolemos** [comment]
This can be closed
