### ISSUE TITLE
Adding button or link inside parallax doesn't work

### ISSUE THREAD

**Issue by Huaoe** [react-spring/react-spring#449]
I'd like to do something like
`<Parallax pages={3} scrolling={false} horizontal ref={ref => this.parallax = ref}>
 <ParallaxLayer offset={0} speed={0.5}> 
<span onClick={() => this.parallax.scrollTo(1)}>
 <button onClick={()=>alert('hello')} ></button> 
</ParallaxLayer> </Parallax>`

see codesandbox 

https://codesandbox.io/s/rmmr7o3xwn

**Comment by Huaoe** [comment]
I'd like to do something like 
`
<Parallax pages={3} scrolling={false} horizontal ref={ref => this.parallax = ref}>
  <ParallaxLayer offset={0} speed={0.5}>
    <span onClick={() => this.parallax.scrollTo(1)}>
      <button onClick={()=>alert('hello')}
    </span>
  </ParallaxLayer>
</Parallax>`

see codesandbox with an a href doesn't work 

https://codesandbox.io/s/rmmr7o3xwn

**Comment by Okami-** [comment]
I find that having a button does work if I change the styles to position: relative and the z-index.

**Comment by Huaoe** [comment]
Hi,
Thank you for your message. I can't succeed with your idea. Would you mind modify this sample ?
https://codesandbox.io/s/5wm8kkm0n

cheers,
Thomas

________________________________

**Comment by xD3CODER** [comment]
Same issue

**Comment by drcmda** [comment]
pointer-events in that demo is set to "none" in the style sheet, meaning no clicks/events ever reach the content of .text - you have to remove it.

**Comment by Huaoe** [comment]
thx ;)
