### ISSUE TITLE
Question: How to use d3-ease with config?

### ISSUE THREAD

**Issue by alanbuchanan** [react-spring/react-spring#460]
In the docs, on the spring page (http://react-spring.surge.sh/spring), it states that, for the `easing` value of `config`,  you can use any easing you want, for instance d3-ease.

I have imported an ease from d3-ease and tried to use it for my config. But the problem is it never seems to apply it. Here is how I am using it:
```
import { easeElasticIn } from 'd3-ease';
```

```
        <Menu
          config={{ easing: easeElasticIn }}
          unique
          state={this.state.menuOpen ? 'in' : 'out'}
        >
```
where `Menu` is a `Keyframes.Spring`.

Please see codesandbox for reference and notice that when you hit the button, you can see the default config for the animation.

https://codesandbox.io/s/04o87745kw

When I place in a custom config from react-spring like `wobbly`, it does work.

Any ideas what I'm doing wrong?

**Comment by drcmda** [comment]
For easing to work you need to specify a duration, this will switch it from spring physics.

**Comment by alanbuchanan** [comment]
Thanks!

**Comment by mwayne16** [comment]
Whenever I try to import it I get this error. Module not found: Can't resolve 'd3-ease' 
Here's how I'm importing: import * as easings from 'd3-ease';
Here's how im attempting to use it:  easing: easings.easeElasticIn,

**Comment by arpandesai0** [comment]
> Whenever I try to import it I get this error. Module not found: Can't resolve 'd3-ease'
> Here's how I'm importing: import * as easings from 'd3-ease';
> Here's how im attempting to use it: easing: easings.easeElasticIn,

I think you did not installed it as your dependency. Run npm install d3-ease and it would work!
