### ISSUE TITLE
react native with transition

### ISSUE THREAD

**Issue by adirzoari** [react-spring/react-spring#465]
Hello,
Im try to make some animations with flatlist with react-spring.
first I try to use transition but i get weird error
![screenshot_2019-01-23-22-04-30-488_com react_spring](https://user-images.githubusercontent.com/20258998/51633730-06517f00-1f5b-11e9-9a90-bbbb583a6dbe.png)

my code
```
`import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, TouchableWithoutFeedback } from 'react-native';
import { animated,Transition } from 'react-spring'

const AnimatedView = animated(View)
const AnimatedText = animated(Text)

const defaultStyles = {
  overflow: 'hidden',
  width: '100%',
  backgroundColor: '#247BA0',
  color: 'white',
  display: 'flex',
  justifyContent: 'center',
  fontSize: '4em'
}


type Props = {};
export default class App extends Component<Props> {

  constructor(props) {
    super(props)
    this.state = {
      items:[
        {key:1, text:'item1'},
        {key:2, text:'item2'},
        {key:3, text:'item3'},
        {key:4, text:'item4'},
        {key:5, text:'item5'},

      ]
    }
  }

  render() {
    return (    
           
            <Transition
              native
              keys={this.state.items && this.state.items.map(item => item.key)}
              from={{ opacity: 0, height: 0 }}
              enter={{ opacity: 1, height: 100 }}
              leave={{ opacity: 0, height: 0 }}>
              {this.state.items.map(item => styles => <View style={{ ...defaultStyles, ...styles }}><Text>{item.text}</Text></View>)}
            </Transition>
      
    );
  }
}

```
`

in addition, Im looking to any examples with react-native with flatlist animation.. anyone?

**Comment by brunolemos** [comment]
Hi, thanks for trying react-spring!

There are multiple things to fix in your code.
Please re-read the [react-native](https://facebook.github.io/react-native/docs/style) and [react-spring](https://react-spring.github.io/transition) docs carefully.

---

> const defaultStyles = {

Use `StyleSheet.create` to create styles and separate on subitems, like `StyleSheet.create({ container: { backgroundColor: 'red' }, text: { color: 'white' }})`.

> color: 'white',

You are mixing `View` styles with `Text` styles.
Works on web CSS, but need to be separated on react-native.

> fontSize: '4em'

fontSize expected a `number`, not a `string`, e.g. `fontSize: 20`

> overflow: 'hidden',
  display: 'flex',

No need for this.

> <Transition keys={this.state.items && this.state.items.map(item => item.key)}

API is wrong. It should be `items={this.state.items}` `keys={item => item.key}`

> {this.state.items.map(item => styles => <View style={{ ...defaultStyles, ...styles }}>

API is wrong. It should be `{item => animatedStyles => (<AnimatedView style={[styles.itemContainer, animatedStyles]}>`

--- 

Here's a modified version of your code that works: https://snack.expo.io/@brunolemos/react-spring-465

<img height="450" src="https://user-images.githubusercontent.com/619186/51711779-2002cd00-2014-11e9-95e1-88539becc2e8.gif" />

<details>

<summary>See code</summary>

```jsx
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableWithoutFeedback,
} from 'react-native';
import { animated, Transition } from 'react-spring';

const AnimatedView = animated(View);

const styles = StyleSheet.create({
  itemContainer: {
    width: '100%',
    height: 100,
    marginBottom: 10,
    backgroundColor: '#247BA0',
  },

  itemText: {
    color: 'white',
    display: 'flex',
    justifyContent: 'center',
    fontSize: 20,
  },
});

export default class App extends Component {
  state = {
    items: [],
  };

  componentDidMount() {
    setInterval(() => {
      this.setState(state => {
        if (state.items.length === 5) return { items: [] };

        return {
          items: [...state.items, { key: state.items.length, text: `Item ${state.items.length}` }],
        };
      });
    }, 1000);
  }

  render() {
    return (
      <View style={{ flex: 1, paddingTop: 50, paddingHorizontal: 20 }}>
        <Transition
          native
          items={this.state.items}
          keys={item => item.key}
          from={{ opacity: 0, height: 0 }}
          enter={{ opacity: 1, height: 100 }}
          leave={{ opacity: 0, height: 0 }}>
          {item => animatedStyles => (
            <AnimatedView style={[styles.itemContainer, animatedStyles]}>
              <Text style={styles.itemText}>{item.text}</Text>
            </AnimatedView>
          )}
        </Transition>
      </View>
    );
  }
}
```

</details>

**Comment by brunolemos** [comment]
No but please send here once you do it so other people can see :)

**Comment by jsp3536** [comment]
I tried this example in react-native-web but had to remove the native prop from the transition and  change animated.View to View.  Is animated.View not supported in react-native-web?  I also tried animated.div with no luck.

**Comment by jsp3536** [comment]
Yes, that works. Thanks
