### ISSUE TITLE
Cannot read property 'push' of undefined (translate3d)

### ISSUE THREAD

**Issue by adjourn** [react-spring/react-spring#468]
v7.2.10

```js
const [styles, set] = useSpring(() => ({
  native: true,
  transform: 'translate3d(0,400px,0)',
}));

// inside gesture handler
set({
  native: true,
  immediate: immediate,
  transform: `translate3d(0,${nextY}px,0)`
});

// render
<animated.div style={styles}>Content</animated.div>
```
No errors when `immediate` is `false`, only happens if it's `true`.

#### Here's the source:

![source](https://user-images.githubusercontent.com/17890701/51716622-2f027300-2046-11e9-80c3-0db859ea6766.png)

#### Im unable to report any patterns at this point, seems to happen randomly:

![console](https://user-images.githubusercontent.com/17890701/51716655-480b2400-2046-11e9-80bd-27f7e248b9b0.png)

**Comment by drcmda** [comment]
i think it could be the native flag, could you remove that? it's native by default. otherwise i can't see anything wrong there ...

**Comment by adjourn** [comment]
I removed `native` flag, same thing. I've discovered that it happens when I do fast movements with gesture, doesn't happen when I move it slowly.. Very odd because error comes from `react-spring` and `transform` is always valid.

Do you have anything else in mind? I'll try to replicate it.

**Comment by adjourn** [comment]
[CodeSandbox](https://codesandbox.io/s/y03yj9n4o1) Same error but it occurs in different situation.. Details are there.

Im starting to suspect that it might have something to do with React state and re-rendering.

**Comment by adjourn** [comment]
[CodeSandbox](https://codesandbox.io/s/y03yj9n4o1) Same error but it occurs in different situation.. Details are there. Sorry about weird math and `ifs`, still a prototype but every path should return a number.
 
Im starting to suspect that it might have something to do with React (state, re-rendering or even portal?).

**Comment by drcmda** [comment]
well the crash is inside the interpolator. don't worry, i will trace and fix it.

**Comment by adjourn** [comment]
I updated CodeSandbox with some additional information, hopefully it's a bit more useful now.

**Comment by zeeyang** [comment]
Seeing the same error when `immediate` flag is on.

**Comment by a-m-dev** [comment]
any solution ???
i'm facing the same issue right now 

nothing is working

**Comment by zeeyang** [comment]
@a-m-dev there's a workaround in my previous comment. Pass numbers into spring (or useSpring), and use `interpolate` function to transform to css.

**Comment by drcmda** [comment]
@adjourn @a-m-dev @zeeyang sorry for the delay, was super busy with something else recently. i am looking at it now and it's the immediate flag that seems to throw it off tracks. fix comes hopefully today if i can find it that fast.

**Comment by drcmda** [comment]
It's fixed, was a really silly bug somewhere in the controller. I will look after some other issue now and publish afterwards.

**Comment by adjourn** [comment]
@drcmda Thanks for the fix, really appreciate it.
