### ISSUE TITLE
Parallax page height

### ISSUE THREAD

**Issue by hyzor** [react-spring/react-spring#469]
Love this library so far but I have one issue with Parallax. The page height is normally set to 100% of the current viewport height (i.e. it's dynamic). What I would like to do is to set the page height to a static height, lets say 1000px. So 6 pages would be in total 6000px. Is this possible?

**Comment by drcmda** [comment]
Yes, it should be possible. You can wrap it into a 1000px container (with position: relative or absolute), then 100% will stretch to that container.
