### ISSUE TITLE
Toggle animation has no leave transition when initial is set to null

### ISSUE THREAD

**Issue by cttobin** [react-spring/react-spring#475]
Thanks for creating this library, it's amazing (although I'm having a problem at the moment).

I want to transition from one component to another using a boolean prop. On first render, I don't want the transition to happen. I thought this would work by setting `initial` to `null` because the documentation says:

> First-render initial values, if present overrides "from" on the first render pass. 

However, it also seems to override the `leave` transition for the first component. Am I doing something wrong or is this a bug? Please see my example on CodeSandbox: https://codesandbox.io/s/8n2j3xz4j9 or the main part of the code here:

```javascript
const Toggle = ({ initial, show }) => (
  <div className="toggle">
    <Transition
      config={config.molasses}
      initial={initial ? null : undefined}
      items={show}
      from={{ transform: "translate3d(0, -100%, 0)" }}
      enter={{ transform: "translate3d(0, 0, 0)" }}
      leave={{ transform: "translate3d(0, 100%, 0)" }}
      native={true}
    >
      {show =>
        show
          ? style => <animated.div style={style}>First</animated.div>
          : style => <animated.div style={style}>Second</animated.div>
      }
    </Transition>
  </div>
);
```

The same thing seems to happen if I set `initial` to the same as `enter` as well. I'm using v7.2.10.

I could set `immediate` based on some condition but I don't know if the `Toggle` component is going to be initialised with `show` being `true` or `false`.

Thank you.

**Comment by ruggedy** [comment]
@cttobin so internally, we treat the 'initialProp' accept any kind of value and ignores it if it `undefined`, treats it as `{}` if its any value that is not a valid object, or a valid object. @drcmda  is this intended?

**Comment by ruggedy** [comment]
@cttobin I have just checked this, and basically, what is happening is you are passing to different string values, so the interpolator is not working. I have updated your Codesandbox here. https://codesandbox.io/s/r7y7p5v86p. basically changed 
` enter={{ transform: "translate3d(0, 0, 0)" }}` to `enter={{ transform: "translate3d(0, 0%, 0)" }}`. 

although I really can say why it works for -100% to 0. @drcmda  any ideas

**Comment by cttobin** [comment]
@ruggedy Thank you for your help, that solves my issue.
