### ISSUE TITLE
attach prop in the Spring Component

### ISSUE THREAD

**Issue by sfegsetsfe** [react-spring/react-spring#477]
In the /src/Trail.js, you use an `attach` prop on the Spring component, which is not mentioned in the document. May I ask what that prop is used for? Thank you

**Comment by drcmda** [comment]
it's a hidden property that makes it possible to "attach" the spring to another, which creates a trail (one spring follows the last value of another). Trail is basically the user-land abstraction around it because using the prop would be too complex.

**Comment by drcmda** [comment]
Yes, reverse needs the trail to init in the given order to be able to reverse attached springs later on. You usually flag it like <Trail reverse={this.state.open} /> With the upcoming hooks version it'll be a little bit more obvious and you can easily define your own trailing logic.
