### ISSUE TITLE
Googlebot parallax not rendering

### ISSUE THREAD

**Issue by Huaoe** [react-spring/react-spring#479]
Hello, 

My SEO manager is not happy with the render as googlebot would 'see' the parralax page.
(tool url: https://www.google.com/webmasters/tools/googlebot-fetch-details)
nothing is rendered actually. I've tried fixing a small width height, no success.
 
any clue ? will it downgrade my indexation ?

cheers,
Thomas

**Comment by LekoArts** [comment]
Yeah, I'm seeing the same behavior:
https://github.com/LekoArts/gatsby-starter-portfolio-cara/issues/10
https://github.com/react-spring/react-spring/issues/322#issuecomment-443429820

**Comment by drcmda** [comment]
@LekoArts you're german right? would you be up for a small skype session or something? i would dedicate some time to ssr but i have never used it and don't know where the problems are. If i know what you need and how to solve it i could fix it. but right now, some google bot not being able to read a react component, it sounds super abstract to it - i just make a lib. 😅

**Comment by LekoArts** [comment]
Yeah, I'm german 😆 You can write me an email and I'd be happy to talk to you about this: https://www.lekoarts.de/contact

**Comment by LekoArts** [comment]
@drcmda ^ 👍

**Comment by jacobrask** [comment]
I'm not 100% sure about the Parallax implemetation here, but a common issue with SEO is content that waits for a scroll event until it renders, because Googlebot will not send scroll events afaik.

**Comment by Huaoe** [comment]
Hi all,
any clue on this ? my SEO manager is still very upset ;)
cheers
