### ISSUE TITLE
Safari Parallax compatibility  

### ISSUE THREAD

**Issue by Huaoe** [react-spring/react-spring#480]
Hi,

The parralax sample is not working properly using Safari.

https://codesandbox.io/s/4w51kl865x

cheers,
Thomas

**Comment by drcmda** [comment]
Parallax itself does work, Safari just can't do css clip-paths it seems. Haven't paid much attention when doing that demo, was just meant as a quick inspiration. If you need clip paths, there are other ways like angled rectangles, etc.

**Comment by Huaoe** [comment]
@drcmda your right, I've managed to workaround adding 
WebkitClipPath:'polygon(20vw 0, 70% 0, calc(70% - 20vw) 100%, 0 100%)',
in my JSS and for every clip
Thank you very much for your sample BTW

have a nice day,
Thomas
