### ISSUE TITLE
[Spring] Disable animation on initial render

### ISSUE THREAD

**Issue by aamorozov** [react-spring/react-spring#485]
I'm trying to disable the animation for the menu item on the initial render and only show it upon hovering the item over. Is there a way to do so with Spring component or it is only available in Transition/setting the initial prop to false ?

**Comment by jacobrask** [comment]
This would be useful, the following ugly pattern (and equivalents) is emerging in our code bases to avoid animating on first mount

```
const ref = useRef();
const springProps = useSpring({
  immediate: !ref.current,
});
return <div ref={ref} />
```

**Comment by drcmda** [comment]
if you don't give it "from" isn't that what you want?

**Comment by aamorozov** [comment]
Hi @drcmda ! Thank you for amazing tool! Here is the sandbox. I've tried your suggestion but I think need to render the component based on the hover state, and it doesn't animate `onMouseLeave` if I don't check the state prior to rendering it. Otherwise it'll be there. Not a big issue in a small example but if you're loading images that you'd like to animate in based on certain events, I think it'll be better to not render them.

@jacoblearned Thank you for your suggestion, but it got me to the same point where i had to either add a `hovered` check prior to rendering or it wouldn't animate `onMouseLeave` 

https://codesandbox.io/s/6nj5wwl3jz

**Comment by aamorozov** [comment]
I think i actually moved a bit away from the original issue - having only `to` prop fixed it, so I will open a new ticket with the description above. Thanks!
