### ISSUE TITLE
React Native Web Support ?

### ISSUE THREAD

**Issue by hedikasmanto** [react-spring/react-spring#486]
Hi

Is React Native Web supported by this great library ?

**Comment by brunolemos** [comment]
Yes, it is! You need to import from `react-spring/native` or `react-spring/native-hooks`.

[DevHub](https://github.com/devhubapp/devhub) is a `react-native-web` project using it for [these](https://twitter.com/brunolemos/status/1087456685080358918?s=20) animations.

**Comment by hedikasmanto** [comment]
Thanks for your reply.. And it works like you said before.. Just import react-spring/native. Awesome library !

**Comment by hanford** [comment]
Since that project is now closed source, is there any other examples out there?

**Comment by fershibli** [comment]
I'm looking for other examples too..
