### ISSUE TITLE
incorrect `ref` on `animated` in 8.0.0-beta.4

### ISSUE THREAD

**Issue by cusxio** [react-spring/react-spring#487]
Currently, `ref` on `animated` returns a function instead of the underlying DOM element due to the usage of [useImperativeHandle](https://github.com/react-spring/react-spring/blob/6abb3e08641648913cd68fd4541db5c438d15953/src/animated/createAnimatedComponent.js#L49)

**Example**:
https://codesandbox.io/s/oqkr4oyjoz

I believe this is not the intended behaviour, unless there is another way to get the DOM element

**Comment by drcmda** [comment]
@cusxio haven't done ref forwarding in a while, could you help me understand what it should be? should i do:

    useImperativeHandle(ref, () => ({ node: node.current, setNativeProps }))

the class based version i guess would just return the dom node as a ref, but there's no "this." any longer, so where do i put component.setNativeProps which is needed for react-native?

**Comment by cusxio** [comment]
Oh, I didn't realise it's something that `react-native` is using.

I'm not too familiar with `react-native` so I am not sure. But what you propose is indeed a viable solution that does not break anything.

Do you think this will work?
```js
useImperativeHandle(ref, () => {
  if (node.current.setNativeProps) {
     return { setNativeProps }
  }
  return node.current
});
```

**Comment by drcmda** [comment]
Something like that could work, but i think setNativeProps has to come from the createAnimatedComponent itself and RN just calls it. I don't really understand it myself. But we could at least make ref catching easier for web users, where this api isn't present.

**Comment by drcmda** [comment]
fixed in the next patch release
