### ISSUE TITLE
`useTransition` items not unmounting in React v16.8

### ISSUE THREAD

**Issue by cusxio** [react-spring/react-spring#490]
Seems like `useTransition` is broken by the latest version of React

16.8.0
https://codesandbox.io/s/8y8n5q67l

16.8.0-alpha.1
https://codesandbox.io/s/j7659151y3

**Comment by drcmda** [comment]
hum, looks like some react hook changed behaviour in between the two versions. need to investigate ...

**Comment by drcmda** [comment]
This looks like a bug in React to me. The transition doesn't do anything wrong, it catches the "false" in the end and renders nothing, but React refuses to let the dom node go. :-S 

here's a version that logs the render pass: https://codesandbox.io/s/vjp41lkrrl

**Comment by brunolemos** [comment]
Yep facing this as well.

I noticed the dom does get removed, but only in the next render phase: https://codesandbox.io/s/o5vn7z0l66

![gif](https://user-images.githubusercontent.com/619186/52377843-30bc3580-2a4d-11e9-9a6b-73d6401834e5.gif)

**Comment by brunolemos** [comment]
I think I found the issue, let me try a fix.

**Comment by brunolemos** [comment]
@drcmda you can't do this anymore to trigger a rerender: `useState()[1]()`. React now bails out of re-rendering when the value is the same.

Do something like this: 

```
const [, _forceUpdate] = useState(false)
const forceUpdate = _forceUpdate(v => !v)
```

**Comment by drcmda** [comment]
Is this official? That's a breaking change :-S

**Comment by brunolemos** [comment]
@drcmda yes it's a breaking change, it's on release notes

**Comment by drcmda** [comment]
good find! i'll update it

**Comment by drcmda** [comment]
published the fix
