### ISSUE TITLE
Why did you update everything to hooks ? 

### ISSUE THREAD

**Issue by MaximeDenuit** [react-spring/react-spring#492]
I've been using your react-spring for a while, this "hooks"-hype isn't really something we like where I work. We used react-spring before, it worked great, thanks for that.

Why have you guys changed EVERYTHING to work with hooks ? Even the render-props (supposed to be the old way of working) is using hooks under the hood, this forces us to update our react version etc.. ?

Are you planning to go forward with an old version, using the "non" hooks way or not ?

Those hooks aren't really a way we'd like at work because we like our OOP approach, we're doing React with a MVVM framework, typescript etc. 

The fact that everyone defines "const" everywhere isn't something we like, but whatever, that's an other discussion.

Will you guys recreate a new repo / branch for those that liked the old way or not ?

**Comment by drcmda** [comment]
no, renderprops are still there and being updated. react-spring now just has two apis. we're working on docs right now, so atm there are two documentations:

Hooks: react-spring.surge.sh

Render-props: react-spring-renderprops.surge.sh

The only thing that changed is that you fetch { Spring, etc } from 'react-spring/renderprops'

**Comment by Tenkir** [comment]
The links to demos in the renderprops docs are dead.

**Comment by MaximeDenuit** [comment]
> no, renderprops are still there and being updated. react-spring now just has two apis. we're working on docs right now, so atm there are two documentations:
> 
> Hooks: http://react-spring.surge.sh
> 
> Render-props: http://react-spring-renderprops.surge.sh
> 
> The code for both is in this repo (look into src/renderprops). The only thing that changed is that you `import { Spring, etc } from 'react-spring/renderprops'`. I can't merge the two because that would be a major breaking change for the render props api and changes go too deep anyway. I hope that i can at least begin to share code at some point, when the majority has updated to 16.8.0.
> 
> So don't worry, all is well and i'll support and fix bugs for both. :)

Thanks for the response, I indeed checked the code and I misunderstood the change, I thought everything was being ported to hooks, or 'under-the-hood' at least. 

This is indeed not the case.

**Comment by drcmda** [comment]
no, i'm not sadistic, that would be some "breaking change" 😇
