### ISSUE TITLE
Native removed from 8.x?

### ISSUE THREAD

**Issue by jas99** [react-spring/react-spring#497]
Getting following error if native is set in hooks

`rangeValue.replace is not a function`

**Comment by drcmda** [comment]
they're native by default, the flag doesn't exist anymore, essentially you're trying to animate a boolean, that's why it complains.

**Comment by jas99** [comment]
@drcmda I suspected that thanks :smile:

**Comment by brunolemos** [comment]
Please add this info to the release notes, and maybe also a `native?: never` to the typescript definition, so it will prevent people from using it.

**Comment by elie222** [comment]
Still confused about this issue. I get the error:
`rangeValue.replace is not a function` when using React Native Web.

```ts
import { useSpring, animated } from 'react-spring'
import { useDrag } from 'react-use-gesture'

const AnimatedView = animated(View)

function DraggableCard() {
  const [{ x, y }, set] = useSpring(() => ({ x: 0, y: 0 }))
  const bind = useDrag(({ down, movement: [mx, my] }) => {
    return set({ x: down ? mx : 0, y: down ? y : 0 })
  })

  return (
    <AnimatedView {...bind()} style={{ x, y }}>
      <Text>Hello</Text>
    </AnimatedView>
  )
}
```

Same error when I import from `react-spring` or `react-spring/native`. I'm using Expo Web.

**Comment by elie222** [comment]
@brunolemos

**Comment by aleclarson** [comment]
Try with v9 and open a new issue if you're still having trouble. Thanks! 👍 

```
npm install react-spring@next
```
