### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by QuentinRoy** [react-spring/react-spring#498]
I would like raise #236 again. I just spent 15 minutes looking everywhere trying to understand how risky it is to move from 7 to 8.
How do I know as a developer what is broken, and what is not? What will I need to change if I take the risk and update to 8? Apparently the entire API just moved to a legacy-like location, but is it the only breaking change?

**Comment by QuentinRoy** [comment]
I understand how time consuming maintaining such a log might be. Maybe something like [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0-beta.3/) could help?

**Comment by QuentinRoy** [comment]
Eventually, it would also help avoiding confusions like #497.

**Comment by drcmda** [comment]
i'm on it, but yeah lots of work. we're setting up a website currently that explains all these steps. for you the only thing that has changes is the export. you import from react-spring/renderprops now, and that's the only change. unless you use hooks. there will be a section in the docs soon - but we ran in a bit of trouble with the dns which kind of threw a wrench in it.

**Comment by drcmda** [comment]
Made a quick one, just to have the breaking change covered: https://github.com/react-spring/react-spring/releases/tag/v8.0.1

I understand it's kind of rough right now, sorry about that. Hooks just changes everything underneath and it's not a joy right now because i can share zero code atm.

**Comment by drcmda** [comment]
i'll close for now to get a better overview of what's to be done, but i get the concern!

**Comment by QuentinRoy** [comment]
Thanks!

**Comment by brunolemos** [comment]
@drcmda Please add the info about the `native` field to the release notes, and maybe also a `native?: never` to the typescript definition, so it will prevent people from using it.

Maybe also mention the change from `react-spring/native-hooks` to `react-spring/native`.

**Comment by drcmda** [comment]
you don't need it - native is the default export in react-native, but i'll add it.

**Comment by brunolemos** [comment]
I do need on react-native-web

**Comment by drcmda** [comment]
ah, that's why! that makes sense, its either renderprops-native or native in that case :)
