### ISSUE TITLE
useSprings missing from web.d.ts v8.0.1

### ISSUE THREAD

**Issue by gscottolson** [react-spring/react-spring#499]
Importing `useSprings` from `react-spring`@8.0.1 throws a TypeScript error. In VS Code:

“react-spring has no exported member 'useSprings'. Did you mean 'useSpring'? ts(2724)”

**Comment by drcmda** [comment]
it's not been added to types yet. types are missing proper definition for useTransition(items, keys, config) and useSprings. But i don't understand types, would you want to add it?

**Comment by gscottolson** [comment]
I have not authored types myself. I was hoping whoever did them initially could knock them out.

**Comment by gscottolson** [comment]
PR is open for what I *think* the `useSprings` typings might be.
