### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by brunolemos** [react-spring/react-spring#502]
Getting this after upgrading to v8.

```
Objects are not valid as a React child (found: object with keys {items, from, enter, update, leave, config, force, unique, onRest}). If you meant to render a collection of children, use an array instead.
```

It seems the api changed, please mention the migration in the release notes if possible.

**Comment by drcmda** [comment]
have you fixed it?

react-spring -> web.js (dom hooks) / native.js (RN hooks)
react-spring/renderprops (dom)
react-spring/renderprops-native (RN)

**Comment by brunolemos** [comment]
Maybe, the error has now changed to https://github.com/react-spring/react-spring/issues/504 but couldn't run the project yet
