### ISSUE TITLE
Unhandled Rejection (TypeError): React.useRef is not a function

### ISSUE THREAD

**Issue by samtietjen** [react-spring/react-spring#505]
This is my first time working with this package, so I'm not sure if this is a bug or I'm doing something wrong? Removing the `useSpring` function clears the error. It's also worth noting that I'm using NextJs.

https://codesandbox.io/s/687004x5n

**The error**
```shell
Unhandled Rejection (TypeError): React.useRef is not a function
```

**index.js**
```jsx
import { useSpring, animated } from "react-spring";

export default () => {
  const props = useSpring({ opacity: 1, from: { opacity: 0 } })
  return <animated.div style={props}>I will fade in</animated.div>
}
```
**package.json**
```json
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^7.0.2",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-spring": "^8.0.2"
  }
}
```

**Comment by drcmda** [comment]
you need to use react 16.8.0 (which introduces hooks).

**Comment by JacquiManzi** [comment]
Just ran into this issue, but yes, there is a warning in the installation.
![screen shot 2019-02-12 at 6 10 52 pm](https://user-images.githubusercontent.com/4119615/52681690-97c86700-2ef1-11e9-8d36-0a67846621bd.png)
