### ISSUE TITLE
With hooks everything is in native spring ?

### ISSUE THREAD

**Issue by oneto018** [react-spring/react-spring#509]
I almost feel bad creating issue for it. I would need some clarifications. I thought this is the best place for it. So now with hooks, everything uses the `native` optimization. With render props, we needed to pass this as a prop to the Primitives. So in order to take advantage of the optimization, I need to use the `animated` variation of the element with `interpolate` for updating via animation?. If I don't use interpolation,  and pass the prop directly, then it will animate the props going through react render on each frame. Are my assumptions right?

**Comment by oneto018** [comment]
I just now read #497

**Comment by drcmda** [comment]
hooks are native by default, interpolate or not, both will be efficient. more on that here: http://react-spring.surge.sh/#/basics#up-front-interpolation
