### ISSUE TITLE
Typescript error for useTransition

### ISSUE THREAD

**Issue by danfri86** [react-spring/react-spring#510]
I'm using React with Typescript and getting typing errors for useTransition:
```
const items = [{id: 1}, {id: 2}];
const transitions = useTransition(items, item => item.id, {
  from: { opacity: 0 },
  enter: { opacity: 1 },
  leave: { opacity: 0 },
})
```
Resulting in "Expected 1 arguments, but got 3."
I'm not sufficient enough in writing types, would be nice if someone can add them.

**Comment by jas99** [comment]
Dude you are on 7.x.x and trying 8.x.x example.
or
using 8.x beta where the wrong typing for 7.x was there

**Comment by drcmda** [comment]
The typing is off, but i'm looking at these types and don't understand what i would have to change. If any of you want to submit a pr, they're super welcome!

**Comment by danfri86** [comment]
Much appreciated @brunolemos 🙏🏻
