### ISSUE TITLE
[v8] onRest api changed

### ISSUE THREAD

**Issue by brunolemos** [react-spring/react-spring#512]
On v7 the on `onRest` used to be called with `(e, state, props)` now seems to be only with `(item)`. 

Could you add it back?

I was relying on it for my nested accordion (it was a hack, but).

**Comment by drcmda** [comment]
is that good?

    if (onRest) onRest(item, slot, values) // slot is state, value are the current-state raw values

**Comment by brunolemos** [comment]
Yeah seems to be the same/similar to what it was, I only use the second and third argument. 

And only the `leave` slot so please check it would be included, it seems it is separated in your code.

**Comment by drcmda** [comment]
It's out in @8.0.3 together with your prs.
