### ISSUE TITLE
useImperativeMethods error with react@16.8.1 & react-spring@7.2.10

### ISSUE THREAD

**Issue by AquiGorka** [react-spring/react-spring#513]
Getting an error: `(0 , _react.useImperativeMethods) is not a function`

https://codesandbox.io/s/x9pkx031ro

Any idea? Thanks

**Comment by drcmda** [comment]
yep, its an outdated react-spring in there. the api is outdated, too. here's an updated version: https://codesandbox.io/s/8zx4ppk01l

**Comment by AquiGorka** [comment]
Hello @drcmda ,
I thought that could be it, is there a way to use `react-spring@7.x.x` with `react@hooks (16.8.x)`?

**Comment by drcmda** [comment]
React had some breaking changes in the hooks release, useState works differently and useImperativeHandle is new. That makes it hard to backport unfortunately.

**Comment by daryl** [comment]
Having the same issue here.

**Comment by AquiGorka** [comment]
@drcmda thanks for the clarification! I'll have to update all usage of `react-spring` 7 -> 8 before trying out hooks.

**Comment by drcmda** [comment]
is this for aragon? it uses the renderprops api so there shouldn't be a problem, we could hang out on jitsi if its pressing

**Comment by AquiGorka** [comment]
@drcmda yes, it is for a swipe-able version of the menu panel I'm working on (PR [here](https://github.com/aragon/aragon/pull/606)) I am using your `react-.with-gesture` tool 😄  and wanted to try out hooks too.

There's no rush, I'll update `react-spring` and then use hooks. Thanks

**Comment by drcmda** [comment]
wow, that looks really cool! let me know if you need help with something!
