### ISSUE TITLE
RenderProps demo links are dead

### ISSUE THREAD

**Issue by Tenkir** [react-spring/react-spring#517]
Since the update, the demo links inside the renderprops documentation goes to a github 404 page.

Example: https://github.com/react-spring/react-spring/tree/master/examples/demos/router

It appears all the renderprop demos have been removed from master in the repository. I understand the desire to move to hooks, especially with its performance improvements, but this feels like it's being rammed through without consideration for legacy applications.

**Comment by johhansantana** [comment]
The old documentation is gone? I just implemented react-spring on a react-native project which still doesn't have support for hooks. Need the examples from version 7 to be able to keep using it.
