### ISSUE TITLE
Transition Performance

### ISSUE THREAD

**Issue by mightym** [react-spring/react-spring#518]
I've using react-spring in several projects so far and I love it ;)

But today I realized on a particular component, a list which renders ~100-200 items that using Transition is so slow that even my whole browser rendering freezes until the transition ends.
Before I had on the list a react-transition-group with a simple css fade from opacity 0 to 1 on each item. Each item animated fluidly.

This is what I did using react-spring:

```
      <ul className={styles.list}>
        <Transition
          items={data} keys={item => item.id}
          from={{ opacity: '0' }}
          enter={{ opacity: '1' }}
          leave={{ opacity: '0' }}
        >
          {data => props => (
           <div style={props}>
             <div>{data.id</div>
            </div>
          )}
        </Transition>
      </ul>
```

Is it just the case that ~100 items is just too much? Or am I doing something wrong? 

Also, I assumed that based on the Transition example the items should appear after each other. Is that correct? Because this didn't also happen in my case. 

Thanks a lot for your help in advance!

**Comment by jonbnewman** [comment]
@mightym you need to use an animated (or animated wrapped) component... (`animated.div`) in this case should work:

```
<Transition
  native
  items={data} keys={item => item.id}
  from={{ opacity: 0 }}
  enter={{ opacity: 1 }}
  leave={{ opacity: 0 }}
>
  {data => props => (
   <animated.div style={props}>
      { React.createElement(this.props.itemRenderer, Object.assign( data ))}
    </animated.div>
  )}
</Transition>
```
