### ISSUE TITLE
transition example does not work with the latest version of react.

### ISSUE THREAD

**Issue by violabg** [react-spring/react-spring#524]
I'have downloaded, this example

https://codesandbox.io/embed/morr206pv8

and updated the dependencies to the latest version and the transition is not happening, here is a sanbox:

https://codesandbox.io/s/14zxwz9234

**Comment by drcmda** [comment]
sorry, it wasn't updated. i'm still in the process of updating them. it's fixed now: https://codesandbox.io/embed/morr206pv8

**Comment by drcmda** [comment]
all examples are updated now.

**Comment by violabg** [comment]
thanks
