### ISSUE TITLE
[useSpring] unmount component when animation's finished

### ISSUE THREAD

**Issue by aamorozov** [react-spring/react-spring#525]
I am animating the width of the element on hover and when it's done animating I would love to unmount the component, but it looks like it is currently not possible(with `Spring`, or now `useSpring`) to have both animation on out(i.e. `onMouseLeave`) and having a conditional whether or not to render the component. I've put together a quick demo.

https://codesandbox.io/s/6nj5wwl3jz

**Comment by drcmda** [comment]
why not doing useTransition? I mean you can use onRest and then unmount, but that's so much hassle. http://react-spring.surge.sh/#/useTransition
