### ISSUE TITLE
Old Docs?

### ISSUE THREAD

**Issue by conradkay** [react-spring/react-spring#529]
Hello, I have a large amount of existing spring component and was wondering where the docs for render-props exists?

**Comment by conradkay** [comment]
Sorry, but now I've found it! (Id recommend a top-level link to render-props docs btw)

**Comment by drcmda** [comment]
new website (with all docs present) goes online tomorrow, we had technical problems merging two docz-roots and two react versions. the previous set up just wasn't prepared for it.
