### ISSUE TITLE
Is it possible to animate on css grid or flexbox?

### ISSUE THREAD

**Issue by jascodes** [react-spring/react-spring#530]
Hey @drcmda 
Gave a quick try, I guess not supported or not make sense without transforms?
 
https://codesandbox.io/s/zzq0k66wvl

**Comment by drcmda** [comment]
you can animate everything, but in your demo youre just placing the item from one column into another. the fr units, vw, vh, all that you can animate. but grid-column just takes an index, there's no point in animating it, the browser will discard it, cut off everything after the decimal point.

**Comment by jas99** [comment]
Hey @drcmda 
I am trying different approach with transition. Is it possible to create scroll slider with css grid and transition. 

How do I animate items; maybe using update which have changed their position in grid but not left.

https://codesandbox.io/s/zzq0k66wvl

Thx

**Comment by jas99** [comment]
@drcmda This is interesting project I came across https://github.com/aholachek/animate-css-grid

**Comment by drcmda** [comment]
@jas99 yea but that's some crazy hackery. they're using flip. you can do this of course, and use react-spring for the animations. but i would much rather rewrite my own small grid in situations like this.

**Comment by jas99** [comment]
@drcmda Thats the plan for now :smile:
