### ISSUE TITLE
interpolate does not exist on property x

### ISSUE THREAD

**Issue by cezarneaga** [react-spring/react-spring#535]
Hi everyone,

in a typescript setup on this line from the [Trails example](https://github.com/react-spring/react-spring-examples/blob/master/demos/renderprops/trails/index.js) with renderprops
`transform: x.interpolate(x => `translate3d(${x}%,0,0)`),`

typescript screams that interpolate doesn't exist on property x.
pretty sure i am making a rookie mistake here. 
thanks,
Cezar

**Comment by drcmda** [comment]
interpolate is part of it, but maybe something in the types broke. do you understand any of this enough to check? https://github.com/react-spring/react-spring/blob/master/types/renderprops-universal.d.ts

@jacobrask @salguerooo

**Comment by cezarneaga** [comment]
not sure. the definitions are quite deep. i am both not familiar with the entire react-spring api and typescript to make a judgement. :)

**Comment by jacobrask** [comment]
Unfortunately I'm not sure I can follow the Trail typings completely yet either, but we're in the process of rewriting the library in TypeScript, which means TypeScript can do more of it's own inference and the types will be a bit simpler. Until then you might occasionally need to add some manual type annotations to your code.

**Comment by cezarneaga** [comment]
Thanks @jacobrask 
All the best in the rewrite. I am sure these will be the toughest types you’ve written :)
