### ISSUE TITLE
useSprings is inconsistent with config settings

### ISSUE THREAD

**Issue by Vindao** [react-spring/react-spring#538]
When using useSpring with tranform there is an inconsistency when using the velocity config. 

I hope the problem is just a mistake from my site...

Please checkout the sandbox on : https://codesandbox.io/s/m3mzvmm95p for an example

**Comment by drcmda** [comment]
Some problems i see there, velocity is is just for initials, i'm not sure it should or can be set like that. translateX should stick to %, there's one without. And otherwise the timeout just seems to cause havok and race-conditions, items will be nulled at one time.

**Comment by Vindao** [comment]
Thanks for the fast reply.

I am not sure what you mean by initials? could you explain that a bit deeper? 

I changed the one translate to %, but that does not seem to be the problem. 

I understand that the timeout is not the best solution, but I could not think about a better one till now. Some suggestions? 

thanks in advance

**Comment by drcmda** [comment]
Velocity is not a manageable value, it is used internally and for some experimental things like decay. I think the weird behavior is caused by setTimeout.

**Comment by Vindao** [comment]
After taking out the setTimeout the issue still remains. But I think I was able to figure out the problem. When toggling fast the velocity does not get used because the fade-out transition did not end yet. 
The issue can be resolved by setting a config for the fade-out transition and give it a duration: 0. 

But this is still mot a solution, because the fade-out transition will obviously not occur then. 
A work-around would be to disable the toggle button during the timeout, but it is hard to figure out the duration of the animation when using velocity. 

Probably the right way would be to use a transition in such a scenario?

https://codesandbox.io/s/j7l66z5429

**Comment by Vindao** [comment]
hope its ok if I put another issue in here. Dont want to open another one as you already have enough to do.
I am trying to build a transition with react router. But I am getting a really weird behavior.

Here is a sandbox which represents the issue: https://codesandbox.io/s/345o5x0636

Also I was able to solve it when using Transition instead. Here a sandbox representing it: https://codesandbox.io/s/j39649pnw3
* Its only transitioning from Test to Home, that is on purpose. 

Probably its a stupid mistake on my site... I appreciate any suggestions

Thanks in advance
