### ISSUE TITLE
Transition required props unexpected behaviour

### ISSUE THREAD

**Issue by enzoferey** [react-spring/react-spring#541]
Hello !

Thank you very much the the library, it's awesome how ridiculous simple animations can be achieved.

I'm working on a project that can't upgrade to latest version of React, so I need to work with `react-spring/renderprops`. After reading the `Transition` component [docs](http://react-spring-renderprops.surge.sh/transition) I found out some unexpected behaviour if you don't supply the non-required props `from` and `enter`.

You can check it on [this sandbox](https://codesandbox.io/s/6lx8oq82z).

Very straightforward examples:

```jsx

        // Doesn't work
        <Transition
          items={this.state.open}
          leave={{
            from: {
              backgroundColor: "#FFF"
            },
            backgroundColor: "#000"
          }}
        >
          {open =>
            open &&
            (props => (
              <div className="App" style={props}>
                <h1>Hello CodeSandbox</h1>
                <h2>Start editing to see some magic happen!</h2>
              </div>
            ))
          }
        </Transition>

        // Works
        <Transition
          items={this.state.openGood}
          from={{
            visibility: "visible"
          }}
          enter={{
            visibility: "visible"
          }}
          leave={{
            from: {
              backgroundColor: "#FFF"
            },
            backgroundColor: "#000"
          }}
        >
          {open =>
            open &&
            (props => (
              <div className="App" style={props}>
                <h1>Hello CodeSandbox</h1>
                <h2>Start editing to see some magic happen!</h2>
              </div>
            ))
          }
        </Transition>
```

The first one doesn't work as expected and the second one is working as expected but I need to add useless values for the `from` and `enter` props.

Am I doing something wrong ?

**Comment by enzoferey** [comment]
Hi @drcmda ! Thanks for the comment. Two things come to my mind then:

1. Why is from inside leave still working then ? If it's not allowed (by the way I couldn't find any of that in the docs), I think it shouldn't work.
2. How would you then animate a component that only needs an `onUnmount` animation ?

**Comment by drcmda** [comment]
https://www.react-spring.io/docs/hooks/useTransition see additional notes on multistage transitions. You need at least from, to give it base values, otherwise it will not animate new values because it wouldn’t know from where to animate. For instance you say: animate green, that doesn’t make sense to it, should it start black, blue,...? If you say animate from yellow to green, that is better.

**Comment by enzoferey** [comment]
Right, but once again in the docs you referenced it states that the `from` prop is optional. On the other hand you are telling me it's needed to know from where to animate, so I'm confused 😅 That's why a created a `from` key in the `leave` prop value, and it actually works as you can see in my codesandbox 🤷‍♂️

**Comment by drcmda** [comment]
no, what i mean is that if you optionally supply base values, it has something to animate towards. if you do not have from and just give it "enter", that is valid, but the state will simply appear, without animation. sometimes you want it to be like that.
