### ISSUE TITLE
Feature request: different config for enter and leave for Transition

### ISSUE THREAD

**Issue by huchenme** [react-spring/react-spring#546]
Would it be possible to have different animation config for `enter` and `leave` of `Transition`? it makes sense to enter slower but leave faster

**Comment by drcmda** [comment]
That’s possible, config can be a function that receives the item and the state (enter, leave, ...) and returns a new config.

**Comment by huchenme** [comment]
@drcmda can you help provide a code example?

**Comment by drcmda** [comment]
```js
useTransition({ config: (item,state) => {
  switch (state)
    case "enter": return { tension: 50 }
    case "leave": return { friction: 100 }
})
```

**Comment by huchenme** [comment]
Thanks, is it possible using render props? we are still largely using React class component

**Comment by drcmda** [comment]
Sure, it’s the same

**Comment by huchenme** [comment]
@drcmda Thanks

**Comment by MattyBalaam** [comment]
This is a feature introduced in v9 I think?
