### ISSUE TITLE
react-router transition help

### ISSUE THREAD

**Issue by LJEsp** [react-spring/react-spring#551]
Sorry but I can't find an example on how to add a transition to a simple route. None of my attempts have worked :(

The route
![image](https://user-images.githubusercontent.com/36854142/52935145-88cf3200-3393-11e9-8b23-4daa17100bd8.png)

A bad attempt
![image](https://user-images.githubusercontent.com/36854142/52935405-46f2bb80-3394-11e9-9e3d-00e693787d09.png)

**Comment by drcmda** [comment]
renderprops: https://www.react-spring.io/docs/props/transition (down there in examples/react-router)

hooks: https://twitter.com/0xca0a/status/1092772431087964161

**Comment by LJEsp** [comment]
Thanks. I didn't saw that. It's working now:
![image](https://user-images.githubusercontent.com/36854142/53015838-07f16280-3487-11e9-883f-38bcaf39e638.png)
