### ISSUE TITLE
React-spring > 8.0.5 stopped working in IE 11

### ISSUE THREAD

**Issue by taikn** [react-spring/react-spring#552]
I am getting Syntax error in console which points to this line, probably due to defining variables with` let`
![annotation 2019-02-18 100805](https://user-images.githubusercontent.com/16017660/52939841-6c1c0580-3365-11e9-8e75-1597ef4f4d45.jpg)

**Comment by jacobrask** [comment]
The Common JS bundle should support IE11. Try updating your imports to

```
import { useSpring } from 'react-spring/web.cjs'
```

Or add a Webpack alias

```
  resolve: {
    alias: {
      'react-spring$': 'react-spring/web.cjs',
      'react-spring/renderprops$': 'react-spring/renderprops.cjs'
    },
  }
```

Not entirely sure but `not ie11` has been in the babelrc config since very long ago so the fact that IE11 support broke in 8.0.5 could be due to unrelated changes making Rollup actually picking up the babel config properly for the default esm bundle.

**Comment by taikn** [comment]
Thanks, I also found a note in the docs about it!

**Comment by ShanonJackson** [comment]
to me when i swap my import from react-spring to react-spring/web.cjs all my animations stop working, i don't think they're equivalents.

**Comment by ammmze** [comment]
oye...not ideal to import the commonjs module :\

**Comment by aleclarson** [comment]
@ammmze fwiw, we'll eventually split each platform into its own package so that the `.cjs` extension is no longer needed.

**Comment by Chetan-k** [comment]
Try 
1. what @jacobrask mentioned above to import from common js and also
2. `import { useGesture } from 'react-use-gesture/web.cjs.js'`
since `useSprings` depends on `react use gesture`.
3. use latest version of `react-use-gesture` ~ `5.1.2`

**Comment by aleclarson** [comment]
**Note:** In the latest beta, you can import the platform-specific package if you don't like adding `.cjs.js` to every import statement:

```ts
import { useSpring } from '@react-spring/web'
```

**Comment by cr0cK** [comment]
Unfortunately, the previous tricks don't work for me. my build is still broken for IE11. Only solution that I have found for now is to revert to 8.0.4...

**Comment by rickiesmooth** [comment]
unfortunatly didnt work for me either.
