### ISSUE TITLE
Could we export {Spring, Transition} from 'react-spring' instead of 'react-spring/renderprops'?

### ISSUE THREAD

**Issue by huchenme** [react-spring/react-spring#559]
May I know what is the reason to scope `{Spring, Transition}` under `react-spring/renderprops` instead of `react-spring`? 

There are still large usage of class components, if scope under `react-spring/renderprops` we could not continue using `module` field because Test fails in Jest, end up we have to use `react-spring/renderprops.cjs`, not only more ugly code, but also not able to tree shaking.

Can I suggest to export both `useSpring` and `Spring` under `react-spring`?

**Comment by drcmda** [comment]
Eventually it will hopefully be like this, but as of right now hooks were a drastic change that didn't allow us to share code much, also would have chained the lib to React 16.8.x. Next major i hope that wrapping the classes around hooks will do. What sucks is that i allowed magic stuff like "auto" to creep into the api, and that will come back to haunt me.

**Comment by drcmda** [comment]
https://github.com/react-spring/react-spring/pull/561

But i don't yet know how to deal with regressions like auto. But that could be a way for now.

**Comment by aleclarson** [comment]
You can use v9 like this now: `yarn add react-spring@next`

Let us know how it goes: #642

**Comment by huchenme** [comment]
Nice, thanks @aleclarson
