### ISSUE TITLE
Feature request: easier way to animate non-CSS props passed to custom component with useSpring hook

### ISSUE THREAD

**Issue by jedwards1211** [react-spring/react-spring#563]
I'm trying to animate the time range I'm passing to a plot component.  This is a non-CSS animation since the plot component computes what to draw to an HTML canvas and where.  I'm using the code below.

It seems like `useSpring` doesn't actually actually trigger updates to animate my component.  I can tell because I only see the animation if I do other things that trigger my component to rerender.

It seems like `useSpring` is designed mostly for use with `animated.div` and isn't very oriented towards animating props that are not used for CSS.  This was easy with `react-motion`'s render props component but I'm trying to transition to using hooks for this.  I see there is a `createAnimatedComponent` HoC but that would defeat the purpose of using a hook for me.

Is there a prop I can pass to `useSpring` to make it force my component to rerender?  If not could we design an API for the non-CSS use case?
```
export default function useTimeRangeSpring([timeRange, setTimeRange]: [
  TimeRange,
  SetTimeRange,
]): TimeRange {
  const { beginTime, endTime, animate } = timeRange
  const springRange = useSpring({ beginTime, endTime, immediate: !animate })
  return {
    animate,
    beginTime: springRange.beginTime.value,
    endTime: springRange.endTime.value,
  }
}

const PlotGridEffects = props => {
  const animatedTimeRange = useTimeRangeSpring([props.timeRange, props.setTimeRange])
  return (
    <HistoricalPlotGrid
      {...props}
      timeRange={animatedTimeRange}
      setTimeRange={setTimeRange}
    />
  )
}
```

**Comment by drcmda** [comment]
The problem is that the hook would cause the entire component to re-render, where previously, with the renderprops-api, react-spring could forceUpdate only the small view wrapped into the Spring components as a function child.

All you need to do is:

```jsx
const AnimatedHistoricalPlot = animated(HistoricalPlotGrid)

const PlotGridEffects = props => {
  const props = useSpring({...})
  return <AnimatedHistoricalPlotGrid {...props} />
}
```

That will make sure only "HistoricalPlot" re-renders, while the carrying component stays put.

**Comment by drcmda** [comment]
Other than that, you can do what you want in userland:

```jsx
const [props, set] = useState({ opacity: 0 })
useSpring({ opacity: show ? 1 : 0, onFrame: set })
return <HistoricalPlotGrid {...props} />
```

**Comment by jedwards1211** [comment]
Thanks for explaining how to do it!

I understand the risk of everything in the carrying component getting rerendered - for my use case the latter path is actually just fine, because the carrying component doesn't render anything else, it just applies several other hooks that control the time range.

I would be happy to make a PR to the docs to include this, but sounds like you may not want the docs to encourage users to take the latter approach?

**Comment by jedwards1211** [comment]
This is a good lesson in the drawbacks of the tradeoff hooks make, in any case.  For a lot of cases like my `material-ui-popup-state` a promiscuous rerender is not really a big deal, but you're right that it's critical to avoid for animation.

**Comment by drcmda** [comment]
a FAQ would maybe be a good idea, something where we can  collect stuff like this. If you want to set a page up for this i would gladly review your PR.

**Comment by jedwards1211** [comment]
@drcmda I noticed when I use `onFrame` that it never stops animating...should I open an issue for that?

**Comment by jedwards1211** [comment]
@drcmda also, mysteriously, it does pause when I trigger the actual animation...have you tested using `onFrame` as the set state function before?  It doesn't *seem* to work, unless I'm doing something dumb...

**Comment by drcmda** [comment]
I have never done it, but don't see why it shouldn't work, could i see your example as a codesandbox? I will fix it.

**Comment by drcmda** [comment]
Thinking about it some more perhaps it's not a bug, just an endless loop. It causes useSpring to cause a render, which causes a onFrame, which ... and so on. Probably not a good way then.

**Comment by jedwards1211** [comment]
Yeah I spent an hour trying to debug it and was surprised I couldn't figure out why it was behaving the way it was.  I had to move on to other things for the time being, and just stick with using a render props component.
