### ISSUE TITLE
Animate innerText with new hooks api

### ISSUE THREAD

**Issue by dpyzo0o** [react-spring/react-spring#566]
![screen shot 2019-02-22 at 17 00 27](https://user-images.githubusercontent.com/24768249/53254309-699e1080-36c3-11e9-9cf8-1f9230491e50.png)

I want to reproduce the example above. How could I correctly format the number? In renderprops I can just use `props.number.toFixed(2)`. However, with the new hooks api, `props.number.toFixed(2)` does not work anymore since `props.number` is now an animated object.

Any help?

**Comment by dpyzo0o** [comment]
Sorry, I just found it explained in the docs using interpolate. Should have read more carefully.

Closed

**Comment by drcmda** [comment]
same with the renderprops api if you use the "native" flag. values turn into self-updating classes that drive the animation outside of react without causing render cycles.
