### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by brunolemos** [react-spring/react-spring#570]
The code is [this one](https://github.com/devhubapp/devhub/blob/fa7e11d19ab02d1af0f3c5ae9ebedaaf23606cd6/packages/components/src/components/modals/ModalRenderer.tsx#L84-L140), two `useTransition` at the same screen.

Works ok on iPhone X.
I notice some lags on Web sometimes and on Android 100% of the time. @Wmitrut reported this:

![kapture 2019-02-24 at 19 04 23](https://user-images.githubusercontent.com/619186/53306034-1b297700-3867-11e9-8475-1e9557a49da7.gif)

Not sure if it's a regression from 7x -> 8x or we just really need #299.

**Comment by drcmda** [comment]
imo that looks too slow to be just a fps issue, but needs to be profiled in order to look into what's causing it to stall like that. is it possible to extract this small piece with mock code around it into a codesandbox?

**Comment by brunolemos** [comment]
I don't think it's anything specific to this code, any transition should be enough to debug.
Just need a mid-end device.

**Comment by brunolemos** [comment]
Ok, I made a quick investigation and there's definitely room for optimization.
Some on react-spring and maybe some on my side.

There are too much script being run while the animation is running.
For example, the callback of `injectCreateAnimatedStyle` is being called more than 1000+ times on my app and this method (that contains `StyleSheet.flatten`) is a bit expensive.

And it seems to be called multiple times while the animation is running instead of only once, see:

![kapture 2019-02-24 at 20 34 36](https://user-images.githubusercontent.com/619186/53307112-cdffd200-3873-11e9-9a0c-0fbc71e58d73.gif)

![image](https://user-images.githubusercontent.com/619186/53307156-45356600-3874-11e9-800a-b08ff3ff8278.png)

**Comment by drcmda** [comment]
that could make sense, flatten can be memoized away. actually, it used to be like that, but when createAnimatedComponent was converted to hooks the complex shouldComponentUpdate stuff that was in there was moved out. i asked vincent riemer about this and we both agreed that it wouldn't cause any trouble. but we were thinking about the dom primarily.

**Comment by drcmda** [comment]
there's still something weird about this, why is createAnimatedComponent.attach (https://github.com/react-spring/react-spring/blob/master/src/animated/createAnimatedComponent.tsx#L83) called so often? This is the one that creates animatedProps/styles, which should be one time. But why is the component re-rendering so often?

**Comment by brunolemos** [comment]
hum...

I think one of the causes of this is because I have too many animated components.
Because the app supports multiple themes, basically all texts and views with background are an animated component. I don't think react-spring was made with this case in mind, so maybe it's not optimized for this. I did this way because theme change was causing a re-render of the whole app before and it was super slow.

So, looking at my Settings screen, I have ~30 "animated" components. The console.log shows ~170 occurrences of the call when opening/closing the modal.

**Comment by brunolemos** [comment]
I added a `console.log` below `attachProps(props)` and same thing happened.

**Comment by aleclarson** [comment]
Could you test v9 on this? `yarn add react-spring@next`

**Comment by brunolemos** [comment]
@aleclarson didn't notice any perf improvement unfortunately. did notice a useTransition bug, my modal close animation stopped working after upgrading (it's now opening animating and closing instantly, but not on v8)

**Comment by brunolemos** [comment]
I was using react-spring on hundreds of components to avoid triggering a rerender on app theme switch. I changed this and now I only use on a few components that actually have animations. 

Performance improved considerably after this change, but there's still a long way to go on android.

But the question is: why having react spring on lots of components causes lag even if they are not being animated or updated at all? something might be off on react-spring internal code.

Possibly related: #654

**Comment by brunolemos** [comment]
I FINALLY found what was causing these lags. And it was a react-native bug, not react-spring's. Here's the details: https://github.com/facebook/react-native/issues/25201
