### ISSUE TITLE
Animating number without decimal points?

### ISSUE THREAD

**Issue by ratnajeetshyamkunwar** [react-spring/react-spring#573]
I want to animate numbers without decimal points. So far I am unable to apply any spring api for that. Please help.

**Comment by Mathspy** [comment]
You just need to floor/round them with an interpolate call:
https://codesandbox.io/s/8yx9j20lo9

**Comment by ratnajeetshyamkunwar** [comment]
Thanks @Mathspy It was super helpful. Closing this issue.

**Comment by cooperfrench95** [comment]
@Mathspy that link doesn't work for me, would it be okay to elaborate here? I've tried to use interpolate, but typescript doesn't like the fact that the props can possibly be undefined.

**Comment by Mathspy** [comment]
@cooperfrench95 
I think it's more recommended to use `interpolate`

```js
function Component() {
  const spring = useSpring({ from: { val: 0 }, to: { val: 100 } });

  return (
    <animated.div>
      {spring.val.interpolate(val => Math.floor(val))}
    </animated.div>
  );
}
```

**Comment by vaibhavhrt** [comment]
Doesn't works when using render-props api. `spring.val.interpolate is not a function`.

**Comment by aleclarson** [comment]
@vaibhavhrt 	Try with v9 beta. If that doesn't work, open a new issue.
