### ISSUE TITLE
Use chain issue

### ISSUE THREAD

**Issue by jas99** [react-spring/react-spring#574]
Tiles don't wait on open animation.

https://codesandbox.io/s/108y319q27

**Comment by jas99** [comment]
@drcmda

**Comment by ruggedy** [comment]
@jass99 this is working as intended, since you're passing the same arguments to useChain on every render, this would cause it to just start both animations immediately. 

do you want it to be sequential without changing the order?

**Comment by jas99** [comment]
Yes.., even somthing like   `useChain([springRef, transRef],[4,5])` won't work...

Can you lay it out for me, and can you update the codebox show how sequential without changing order.
Thx

**Comment by ruggedy** [comment]
that is not supported internally.. but a workaround is here [https://codesandbox.io/s/4lvjk9vxj9](url) . this would force the object ref to change everytime thereby forcing it to play the animations sequentially.

**Comment by jas99** [comment]
Bunch of thanks!!!

**Comment by wereHamster** [comment]
What was the reason to immediately start all animations on subsequent renders?

**Comment by robbertvancaem** [comment]
What worked for me was to change: 
`useChain([firstRef, secondRef])`

into
`useChain([{ current: firstRef.current }, { current: secondRef.current }])`

**Comment by aleclarson** [comment]
v9 fixes this issue, I think.

**Comment by Soundvessel** [comment]
@robbertvancaem The workaround  with v8.0.27 causes the following console error `web.js:584 Uncaught (in promise) TypeError: Cannot read property 'start' of undefined
    at web.js:584` is that safe to ignore?

**Comment by mattzuckermann** [comment]
My Apollo "useQuery" function was somehow breaking the time changes of my "useChain" function, but this fix got it up and running for me again. Thank you!
