### ISSUE TITLE
"export 'Spring' was not found in 'react-spring'

### ISSUE THREAD

**Issue by gilbertlucas46** [react-spring/react-spring#578]
Hi, I'm trying to use react spring in my gatsby application, but I'm getting this error when I tried to use it
`"export 'Spring' was not found in 'react-spring'`

I imported it like this
`import { Spring } from 'react-spring'`

This is how I'm using it

```
<Spring
          from={{height:100}}
          to={{height:200}} >
        {styles => (
          <div style={{overflow:'hidden',...styles}}>
          <Img fluid={data.file.childImageSharp.fluid}/>
          </div>
        )} 
</Spring>
```

I also made sure that the react-spring is included in my node modules

**Comment by drcmda** [comment]
it's import { Spring } from 'react-spring/renderprops'

See: https://www.react-spring.io/docs/props/spring
