### ISSUE TITLE
Inconsistent functionality when applying a ref to useTransition

### ISSUE THREAD

**Issue by JesseFarebro** [react-spring/react-spring#579]
First off I want to say that 8.0 with hooks is amazing!

I've been trying to set up a chain with `useChain` and noticed that when I apply a ref to `useTransition` it causes some props to not be applied. I don't see why such functionality should change if a user wanted to chain together already existing animations.

Here is a code sandbox: [https://codesandbox.io/s/r7po86w6qq](https://codesandbox.io/s/r7po86w6qq?fontsize=14).

If you leave the ref on `useTransition` you can notice `position: absolute` is *not* applied to the leaving component. Simply uncommenting the ref and not using the chain causes the style to be applied as expected.

**Comment by drcmda** [comment]
this is a bit odd indeed. 😦 i am super busy right now but i'll flag this as a bug to pick it up when time allow. i would of course be super happy if someone could take a took. maybe you wanna try?

**Comment by drcmda** [comment]
@JesseFarebro late answer, but turns out it's the same thing mentioned here: https://github.com/react-spring/react-spring/issues/604

these values are animated, but they aren't connected to the view. giving it a default in from fixes it.

I think async animation needs more documentation

**Comment by JesseFarebro** [comment]
@drcmda Thanks for the response. That does seem to be the case and the reasoning makes sense. 

One last comment: I have been trying to debug `useTransition` applying props immediately on the first transition (it doesn't animate) when using a ref. I'm scraping through issues to see if anyone else has had a similar issue. Not sure if you are aware of this. I can create another code sandbox to reproduce it if you'd like.

**Comment by aleclarson** [comment]
@JesseFarebro A repro would be great, thanks! 👍

**Comment by JesseFarebro** [comment]
@aleclarson the other problem I was facing was due to how I was using the refs. I'm unable to reproduce the issue and I determined it wasn't a problem with react-spring.

This issue can be closed, there is a good explanation of the issue in #604. Thanks, everyone!
