### ISSUE TITLE
Error when trying to customize a keyframe: rangeValue.replace is not a function

### ISSUE THREAD

**Issue by ssynix** [react-spring/react-spring#581]
I'm trying to create something like [this animation](https://codesandbox.io/embed/pxqo7113x) using the hooks API:
1. Immediately change a prop to value1.
2. Then animate it to value2.

Here's my attempt: https://codesandbox.io/embed/m7rl0rv2lp

I can't seem to be able to make the first piece of animation execute immediately, reproducing what `immediate: true` accomplished in `Keyframes`.

Passing `immediate` or `config` in `to`, `from`, or the to prop shortcut (`to: [{...}, {..., config }]`) produces this error:
```
TypeError: rangeValue.replace is not a function
...
  at createStringInterpolator
```

Is there a concise way of scripting an animation that may not use the same config for every frame? It'd also be nice if the error was more human-readable.

**Comment by ssynix** [comment]
I realized that my code sample above is actually producing the effect that I wanted, I just have to tweak the duration to see it. But nevertheless, it seems like it's not possible to individually tweak animations using the to prop shortcut and an attempt to do so results in cryptic error messages.

**Comment by drcmda** [comment]
@ssynix sorry for the delay, was super busy. i am looking into it right now ...

**Comment by drcmda** [comment]
It's fixed: https://codesandbox.io/s/98j7vny35w

was a small bug somewhere in the controller that thought "immediate" was a prop it should animate.

**Comment by ssynix** [comment]
Thanks for the quick fix! I'd definitely run into the issue of not setting `from` and sticky props before, so it's great to know what I was missing (would be nice to have them added to the docs) 👍

**Comment by drcmda** [comment]
It's there: https://www.react-spring.io/docs/hooks/use-spring (under async chains)
