### ISSUE TITLE
Snap effect when transitioning out of a component.

### ISSUE THREAD

**Issue by nateshmbhat** [react-spring/react-spring#585]
I am trying to have an animation every time the picture component gets changed. The first animation when the page loads , is fine. When I click the '+' button , the animation kind of snaps back to its final position in a jerk and is not smooth. I don't understand why this snap effect is happening. How do i fix this ?

https://codesandbox.io/s/wn6jp23vxl

**Comment by drcmda** [comment]
it's easier to think of spring as a value interpolator, it doesn't do magic. if you want two elements on top of one another in css you need to position them absolutely. you can do this in plain css classes or even in the spring definition, for instance `from: { position: 'absolute', ...`

**Comment by nateshmbhat** [comment]
I tried giving 'absolute' property for the component which I am animating but no luck :(

**Comment by nateshmbhat** [comment]
Can u please post what I can fix on that codesandbox i shared  ?
