### ISSUE TITLE
Bug that prevents scrolling on an overflow div with the mouse-wheel after transition (on Chrome)

### ISSUE THREAD

**Issue by LJEsp** [react-spring/react-spring#586]
I have this overflow div (Create Person)..
![image](https://user-images.githubusercontent.com/36854142/54069256-49f51380-4291-11e9-869c-859373eb5838.png)

With this ordinary Transition..
![image](https://user-images.githubusercontent.com/36854142/54069259-59745c80-4291-11e9-8a37-1a28173de8e6.png)

When the div mounts somehow you **can't scroll with the mouse wheel** (but you can scroll with the scrollbar). Then, when some other part of my code rerenders (like the async stuff in the foreground) the mouse wheel works again.

I think it has something to do with the animating in the DOM. To test I added the immediate prop, the problem disappears. Same issue when I use Spring. I think for a workaround I have to do something in the onRest but I have no clue what.

This doesn't happen on Firefox so it might be a bug in Chrome.

**Comment by drcmda** [comment]
the lib doesn't do any more than project your html/css content into the dom, there's no magic or implicit stuff going on (events handlers, etc). there's some css thing that's keeping it from scrolling. if you pour that into a codesandbox maybe i or someone else can help you anyway.

**Comment by LJEsp** [comment]
This is just weird. Could be css, animation, or Chrome issue.
