### ISSUE TITLE
UMD bundle?

### ISSUE THREAD

**Issue by ad-git** [react-spring/react-spring#588]
Where i can find umd library available for in-browser use?

Thx for yout time

**Comment by drcmda** [comment]
We had one, but it didn't survive 8.x. Would you submit a pr to add it back? It's under rollup.config.js, it's in the git history.

**Comment by aleclarson** [comment]
Here it is if anyone wants to submit a PR:
https://github.com/react-spring/react-spring/blob/be06c3b8c9978d8db08754bad98e4e91ac70bf68/rollup.config.js#L38-L58
