### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by jascodes** [react-spring/react-spring#589]
Hey Guys,

I came across this awesome postcss plugin called grid-kiss,https://github.com/sylvainpolletvillard/postcss-grid-kiss. I was thinking if its possible to natively animate this grid using react-spring or matter of fact any other postcss code.

Thx
@drcmda 

PS: There is also https://github.com/4Catalyzer/astroturf which I am looking into.. any commets on that?

**Comment by drcmda** [comment]
as long as you can write into styles you can always animate. but this pre-processing / babel / macro stuff can sometimes shut you out.
