### ISSUE TITLE
useTransition and immediate

### ISSUE THREAD

**Issue by nervestaple** [react-spring/react-spring#594]
`immediate` key fails when used with `update:` or `enter:` or whatever keys on `useTransition`. is there any way to immediately snap an `update` to its destination, for example? would this require an API change?

**Comment by drcmda** [comment]
i think you don't need transition at all in this case, it's been made for situations where immediate actions are intercepted in order to animate items in and out.

**Comment by nervestaple** [comment]
sure, that's what I'm using it for -- I want to animate transitions like enter/exit/update, but also want to conditionally snap certain transitions to their destination some of the time. `immediate` is an option that exists in useSpring, for example -- is there something that conceptually prevents such an option in `useTransition`?

**Comment by nervestaple** [comment]
the issue is manifesting with animating `display: grid` cells. imagine using `useTransition` to manage adding/removing/moving grid rows smoothly. 

upon adding a row to the grid, the existing cells in rows below have to be shifted down 1 row -- once they're in position, the `grid-row` of each cell must be incremented simultaneously with their `transform: translateY` snapping back to 0. this doesn't seem possible with `useTransition` currently without an option like `immediate`.

**Comment by aleclarson** [comment]
Please provide a CodeSandbox that demonstrates the issues you're having. Thanks! 👍

**Comment by nervestaple** [comment]
https://codesandbox.io/s/ql21yr2l4?fontsize=14

it's very possible that there's a way to fix this specific implementation, or that it doesn't make technical sense to implement immediate properties for `useTransition`, but it does seem like it would be convenient here.

**Comment by aleclarson** [comment]
You can use v9 like this now: `yarn add react-spring@next`

Let us know how it goes: #642
