### ISSUE TITLE
Trails example doesn't work, no animation

### ISSUE THREAD

**Issue by AndrewRayCode** [react-spring/react-spring#596]
Using the trails example code, both css and js, from https://github.com/react-spring/react-spring-examples/blob/master/demos/renderprops/trails (linked from https://www.react-spring.io/docs/props/trail), pasted into a Codesandbox, there is no animation when clicking on the element: https://codesandbox.io/s/mjmoq7nqrx

This code is copied directly from the example, so I'm not sure what the issue is. I'm not sure if the API is out of date or if there's something higher up in the example boilerplate that adds code.

I know this is a borderline StackOverflow question, but I'm making a ticket because if copying and pasting the code doesn't work it's hard for me to know if it's an issue with this library or an issue with my implementation of it.

**Comment by ioss** [comment]
@AndrewRayCode your copy has some modifications. 
You are importing `animated` from 'react-spring', but you should use the one from 'react-spring/renderprops'.

**Comment by AndrewRayCode** [comment]
oh snap, thanks, as a noob I didn't even realize you could get it from one vs the other
