### ISSUE TITLE
Flash of final state in useSpring vs Spring using custom interpolator

### ISSUE THREAD

**Issue by ebemunk** [react-spring/react-spring#597]
Hi,
I am trying to use a custom interpolator to animate some paths, what I found is that there seems to be a bug in the hook implementation. I have reproduced what I see below:

https://codesandbox.io/s/r0333k1pyp

In the hook case, you see the final state flash before it starts animating. This is highlighted even more with a delay.
In the renderprop case there is no issue, which I assume is the correct behavior.

**Comment by drcmda** [comment]
That's tough. The renderloop uses requestAnimationFrame. So it renders the current state, then starts the animation. On top of that, delay doesn't start until the timeout, that was a previous bug in the old implementation that looks better in this case, but caused so much trouble down the line. I'm thinking how to solve this ... you're switching the interpolator, but any render would destroy your component. If the parent for instance forceupdates, it would pull this down. Can't the d3 interpolator be configured in such a way that it moves in between shapes without re-creating the interpolator?

**Comment by koss-lebedev** [comment]
Just for the reference, here's the same bug I found by recreating shape morphing demo from render props to hooks: https://codesandbox.io/s/spring-snowflake-htnzp

**Comment by aleclarson** [comment]
This isn't `react-spring`'s fault. You are updating the interpolator before the animation is reset.

Here's a fixed sandbox: https://codesandbox.io/s/react-spring-597-f62sf

But note, there's still an edge case when quickly clicking twice.
