### ISSUE TITLE
👋 Maintainers wanted

### ISSUE THREAD

**Issue by drcmda** [react-spring/react-spring#600]
Hey 👋,

i'm looking for more eyes on this project. There are times when i'm relatively busy and it would be great to have some more devs on board. I'm completely open to share authorship, discuss or new ideas, or would otherwise be happy with maintenance. This lib will go forward of course, but would be great if it could do so faster, so that the experience will be better for all of us.

Let's talk if anyone's interested! : )

**Comment by bernard-lin** [comment]
I've loved using this library but haven't paid as much attention to its development. I'll start watching the repo 🙂

**Comment by drcmda** [comment]
@bernard-lin sure, if you want go ahead. I am super happy if i can get some help.

**Comment by aleclarson** [comment]
I can help out periodically. I already maintain [immer](https://github.com/mweststrate/immer) with Michel.

First thing, I would start adding labels to the issues.

**Comment by drcmda** [comment]
@aleclarson would appreciate that very much!

**Comment by aleclarson** [comment]
@drcmda Sweet, send me an invite when you can. 👍

**Comment by aleclarson** [comment]
I just labelled all open issues, and closed 29 of them! 😄 ❤️

**Comment by drcmda** [comment]
Ha, i saw! Nice work!

**Comment by nimamehanian** [comment]
Very interested. Been migrating projects with react-motion to react-spring and really loving it. Would enjoy having a hand in this. Main site deserves a lot of love. Not seeing an issue about this (which brought me here): `useSpring` doesn't accept an object anymore; it demands a function. And when doing so, passing a `delay` key into the object that that function returns throws an error. Docs don't address this right now.

**Comment by aleclarson** [comment]
> `useSpring` doesn't accept an object anymore; it demands a function. And when doing so, passing a `delay` key into the object that that function returns throws an error. Docs don't address this right now.

Is there an issue open about this? If not, please make one (with a repro). Thanks! 👍

**Comment by rnnyrk** [comment]
I'm interested in helping out. Would like to know how I can add value ;)

**Comment by aleclarson** [comment]
@rnnyrk For starters, you can test out the new beta :)

**Things to do:**
- [ ] test the beta
- [ ] convert some (or all?) [examples](https://github.com/react-spring/react-spring-examples) to TypeScript
- [ ] convert remaining JS modules in `src` to TypeScript

**Comment by rnnyrk** [comment]
Cool! Going to look into it. Already started testing out the new beta, see f.e; https://codesandbox.io/s/5yzw5x0wyl Going to use it more in the upcoming weeks for sure

**Comment by MaxBSilver** [comment]
I'd love to help manage issues and really anything else!

**Comment by aleclarson** [comment]
We can use all the help we can get! 👍 

Feel free to open issues if you have any questions for @drcmda about the internals. :)

I'll mark those questions with the "internals" tag.
