### ISSUE TITLE
Properties in useTransition.enter only applies for the 1st item

### ISSUE THREAD

**Issue by Albert-Gao** [react-spring/react-spring#604]
I am using `8.0.18`.

```javascript
  const transitions = useTransition(items, i => i, {
    from: {
      transform: "translateY(-6000%) translateZ(0)"
    },
    enter: {
      transform: "translateY(0) translateZ(0)",
      zIndex: 1
    },
    unique: true,
    leave: {
      transform: "translateY(-6000%) translateZ(0)"
    },
    trail: 180
  });
```

For an animation like this, everything works perfectly, unless the `zIndex` in `enter`, it only applies to the 1st item but not the rest.

Is this a bug or I miss something?

I need this to make the stack context right after using `transform` for animation.

A reproduce example can be found here: https://codesandbox.io/s/jnj75r74my

**Comment by drcmda** [comment]
Curious indeed, im looking at it now ...

**Comment by drcmda** [comment]
ok, this makes sense, at least from a technical standpoint. You're using delays, so the animated props are asyc, meaning at the time where you distribute them among the view they haven't executed yet. They only contain the props in from, which react-spring can read out and distribute immediately. later on it will execute "enter", but only the transform prop has been linked to the view, and since the view.

If you want to animate props async, you must make sure they exist when you connect them to the view. This is explained here: https://www.react-spring.io/docs/hooks/use-spring (under async chains)

**Comment by Albert-Gao** [comment]
Thanks for the answer.

I tried this:

```javascript
    const transitions = useTransition(patients, p => p.RecallId, {
      from: {
        transform: 'translateY(-100%) translateZ(0)',
        opacity: 0,
      },
      enter: item => async (next, cancel) => {
        await next({
          transform: 'translateY(0) translateZ(0)',
          opacity: 1,
          duration: 250,
          zIndex: 10,
        });
      },
      unique: true,
      leave: item => async (next, cancel) => {
        await next({
          transform: 'translateY(-100%) translateZ(0)',
          opacity: 0,
          duration: 390,
        });
      },
```

and updated the `enter` to this:

```javascript
 enter: [
{
      transform: 'translateY(0) translateZ(0)',
      opacity: 1,
       duration: 250,
},
{zIndex: 10}
]
```

but the problem exists. What do I miss?

**Comment by drcmda** [comment]
In your first demo, if you put zIndex into from it works. No need for functions and arrays. Other than that, you can't animate zIndex, it makes no sense. The browser won't allow you to use floats. I would suggest using strings, like zIndex: "1" if you want to give it another value in the leave transition, etc.

**Comment by Albert-Gao** [comment]
Thanks, it's indeed there, but seems the zIndex must be applied during enter, means, after the animation. Apply at the start, won't change the stack context...

Is there a way to apply some properties at the end?

**Comment by aleclarson** [comment]
@Albert-Gao You can use the `immediate`prop

```js
enter: item => async (next, cancel) => {
  await next({
    transform: 'translateY(0) translateZ(0)',
    opacity: 1,
    duration: 250,
  });
  await next({
    immediate: true,
    zIndex: 10,
  });
},
```
