### ISSUE TITLE
Parallax scrollTo happens too fast second time

### ISSUE THREAD

**Issue by duketran1996** [react-spring/react-spring#607]
Hi,
I am having this issue when I have a nav toolbar and send a state value onclick to my parallax page. I use `this.parallax.scrollTo` inside a componentDidUpdate.

```js
  componentDidUpdate(prevState) {
    if (prevState.currentPageScroll !== this.state.currentPageScroll) {
      this.parallax.scrollTo(this.state.currentPageScroll);
    }
  }
```

I am aware that my `prevState.currentPageScroll` is undefined which I want to so when I scroll up without clicking nav button, my scrollTo will always hit.

The problem is when page load click the nav button, the page scroll smoothly. But when I scroll up using mouse then click on nav button agai, my background move very fast like instant without the smooth scroll effect. I am seeking out for help since I am not sure how the problem is. I am also open for anything different approach using navBar. Thank you

**Comment by aleclarson** [comment]
Could you provide a sandbox? Thanks 👍 

Closing until you respond.

**Comment by jason-crowley** [comment]
I have this issue as well and I think that this can be reproduced in the demo for Parallax on the React Spring page: https://codesandbox.io/s/nwq4j1j6lm?from-embed.

Steps:
1. After loading the page, click the screen (at offset 0) to scroll to the second page (offset 1).
2. Use mouse to scroll back up to the top of the page (offset 0).
3. Click the first screen (offset 0) again to scroll to the second page (offset 1) again.

Expected: Clicking the first screen (offset 0) for the second time should smoothly scroll to the second page (offset 1) as it did for the first click.
Actual: For the second click, the screen jumps up suddenly and the "bash" image of the second place also seems to appear out of nowhere very quickly.

Also it should be noted that the transition from page 1 -> page 2 remains smooth as long as you click through all three screens to get back to the first page.
