### ISSUE TITLE
background image url gets altered

### ISSUE THREAD

**Issue by dferber90** [react-spring/react-spring#608]
When using `backgroundImage: url("/images/foo-5.jpg")` in a `useTransition`  call, then the image url gets turned into `/images/foo-5jpg` before it is set. This could also happen for other methods (like `useSpring`, or might be the fault of `animated.div`- I didn't look into it).

```diff
-/images/foo-5.jpg
+/images/foo-5jpg
```

The same happens for

```diff
-/images/foo+5.jpg
+/images/foo5jpg
```

Something similar happens when for the url is `/images/foo-8e47-bar.jpg` which gets converted to `/images/foo-8e+47-bar.jpg`

```diff
-/images/foo-8e47-bar.jpg
+/images/foo-8e+47-bar.jpg
```

I assume some numbering logic is parsing `e47` and converting it to `e+47`. The same logic is parsing `-5.` and converting it to `-5`.

This loss of the original URL results in the background image not showing up.

Reproduction sandbox: https://codesandbox.io/s/887y76o9m9?fontsize=14

---

Thanks for creating and maintaining `react-spring`. It's a joy to use 🌞

**Comment by drcmda** [comment]
https://codesandbox.io/s/5w05wwmk0n

It's trying to interpolate your string. The interpolator can animate any string you give it if it detects numbers in it.

**Comment by dferber90** [comment]
Ah, I thought there was some CSS parsing going on, but it makes sense now.
Thanks for explaining and thanks for the example, helped a lot  💐 

I guess I assumed for some reason that putting all styles into the spring was some sort of best practice (as the styles are not spread to two places), but now that I understand that springs just interpolate anything (without parsing), I get it.

I'll close this as it works as intended.
