### ISSUE TITLE
Parallax hide scrollbar

### ISSUE THREAD

**Issue by hyzor** [react-spring/react-spring#609]
Hi, fantastic library first of all. I wonder if it's possible to hide the scrollbar for Parallax?

The first solution I have found is to override div elements style with -webkit-scrollbar display: none but that affects **all** divs. I am struggling because Parallax bakes the div pages at runtime so I have no control of it.

Do you have any idea on how to solve this?

**Comment by hyzor** [comment]
The second solution I found was to put a div on top of Parallax and give it a custom CSS class that hides the scrollbar, which is described [here](https://www.geeksforgeeks.org/hide-scroll-bar-but-while-still-being-able-to-scroll-using-css). Problem is that I can't make it work for Chrome, only IE/Edge and Firefox.

**Comment by aleclarson** [comment]
Closing this, since it's not really a react-spring issue.

**Comment by Maca30** [comment]
> Closing this, since it's not really a react-spring issue.

Could you maybe have been bit more helpful?

**Comment by iliasrafia** [comment]
Add overflow: "hidden"
![code](https://user-images.githubusercontent.com/65836995/145303347-cad18398-40ee-4c9c-b7f7-03334e41a973.png)

**Comment by dondxniel** [comment]
The above solution might not work for some people; like it didn't work for me. Give it the css style:

```
.parallax-remove-scrollbar {
	-webkit-scrollbar-display: none !important;
	scrollbar-width: 0 !important;
	overflow: hidden !important;
}

```
