### ISSUE TITLE
ParallaxLayer speed scroll bug

### ISSUE THREAD

**Issue by hyzor** [react-spring/react-spring#610]
I have found what I think is a bug (or a feature?). When I open, let's say a [Material UI Dialog](https://material-ui.com/demos/dialogs/), the Parallax object and body gets locked in place in the background as it should, and scrolling in the Dialog object doesn't make Parallax in the background scroll, which is exactly what is intended.

**However**, ParallaxLayers in the Parallax object with speed > 0 are still scrolled in the background while scrolling in the Dialog object, thus these layers are scrolled while the actual Parallax object and body is still locked in place. **This is very confusing and makes me wonder if it's intended or not**.

I had to solve this myself by setting the speed of all layers to 0 while a Dialog is open (or any other kind of popover/popup) and back to normal speed after closing.

**Comment by aleclarson** [comment]
Please provide a CodeSandbox if you want help.
