### ISSUE TITLE
[codesandbox](https://codesandbox.io/s/zwpy8xx1w3) TypeError: arr[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by mfelmy** [react-spring/react-spring#616]
Dear Team,

I tried getting into react-spring but always get the above mentioned error. Even a fresh new `npx create-react-app` and `npm i react-spring` as the only additional dependency doesn't get rid of this error.

Am I missing something obvious here?

Thanks a lot
Malte

**Comment by drcmda** [comment]
it's

```jsx
const props = useSpring({ width: `${value}%`, from: { width: "0%" } });
```

You're trying to destructure a non-iterable result ;-)

**Comment by mfelmy** [comment]
Oh, okay. So it was something obvious indeed...

Thank you very much for your help!
