### ISSUE TITLE
Parallax is breaking the layout

### ISSUE THREAD

**Issue by visualcookie** [react-spring/react-spring#618]
Hey, I'm having troubles using react-spring without breaking my layout. On the background of my page are a couple of lines, which will be animated as well as each content element inside of a content section will move accordingly (moving slowly up or down).

While doing this, the issue is, that without applying a fixed height to my content sections, the layout will break. I've discovered by simply removing the `position: absolute;` and `height: 0;` from the elements, the parallax still works, so I don't know why these props are even there.

May there be a way of simply deciding whether to use position? Shouldn't the height be the height of the element inside?

**Comment by visualcookie** [comment]
@aleclarson Hey, sure. Just set-up the elements like I'm having them + adding a spacer, so you can scroll.

Can be best viewed on full view.

LINK https://codesandbox.io/s/2w55xwwj0

**Comment by aleclarson** [comment]
The sandbox seems to have been deleted. 😅

**Comment by lopezdp** [comment]
really wish that code pen was still around

**Comment by tiarebalbi** [comment]
The Sandbox is working as expected...

https://codesandbox.io/s/2w55xwwj0
<img width="668" alt="Screen Shot 2019-12-28 at 4 41 00 AM" src="https://user-images.githubusercontent.com/103419/71538964-491a9480-292c-11ea-83f9-c2e024394423.png">

I'm having the same issue on Tablets... for desktop the size is perfect but as soon I change the resolution for an iPad I start to have an overlap of the sections...

<img width="1025" alt="Screen Shot 2019-12-28 at 4 42 42 AM" src="https://user-images.githubusercontent.com/103419/71538980-82eb9b00-292c-11ea-8377-4b6884aa8a9b.png">

Link: https://new-site.tiarebalbi.com/
