### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by eDubrovsky** [react-spring/react-spring#620]
In console i see this message:
`warning " > react-spring@8.0.19" has unmet peer dependency "prop-types@15.x.x".`

**Comment by aleclarson** [comment]
Run `npm install prop-types@15`

**Comment by Kukkimonsuta** [comment]
@aleclarson Official recommendation for `prop-types` is to take direct dependency

https://github.com/facebook/prop-types#how-to-depend-on-this-package

More discussion around the topic: https://github.com/facebook/prop-types/issues/44

**Comment by aleclarson** [comment]
@Kukkimonsuta Good catch, I'll change it
