### ISSUE TITLE
onDestroyed being called more than for the same item (with `lazy`)

### ISSUE THREAD

**Issue by Andarist** [react-spring/react-spring#622]
https://codesandbox.io/s/1ox8lq0o83

Sorry for somewhat complex repro, I was working on reproducing other issue and noticed this one. Seems to me that if item gets marked as destroyed that callback shouldnt be called when we rerender in the meantime without touching that particular item (it stays destroyed).

**Comment by drcmda** [comment]
There's a destroy, then a transition out phase and the actual moment the element is taken out. looks like there's a check missing that tells it that it has already fired that event.

**Comment by aleclarson** [comment]
Not relevant once #809 is merged. The `onDestroyed` prop has been removed there.
