### ISSUE TITLE
onRest is called again after rerender

### ISSUE THREAD

**Issue by ThomasDeutsch** [react-spring/react-spring#623]
Problem:  Once completed, onRest function is called on every rerender.

[minimal codesandbox demo](https://codesandbox.io/s/5x2xxpjoop)

**Expected**:  the count should only increment once.
**Current Behaviour**:  after rerender the onRest function is called again, and the count gets updated.

Versions in this demo:
"react-spring": "**8.0.19**",
"react": "16.8.3",
"react-dom": "16.8.3"

**Comment by drcmda** [comment]
It's how onRest is currently working, it animates between 100% and 100% and comes to a rest immediately. If if didn't do that, then you couldn't await async animations, since onRest wouldn't be called once you animate towards a value that's already set.

**Comment by ThomasDeutsch** [comment]
understood, thanks for the explanation.

But how can i change the state once, after the animation has finished?
It would be possible if i could get the from-to values in onRest. 
In this case i could check if from === to and not update the state.

**Comment by aleclarson** [comment]
You can use v9 like this now: `yarn add react-spring@next`

Let us know how it goes: #642
