### ISSUE TITLE
supporting scroll to anchor and animation on appearance

### ISSUE THREAD

**Issue by violabg** [react-spring/react-spring#628]
Are there any plans to support link to anchor animation, and animating an element when it enters the viewport when user scrolls?

**Comment by aleclarson** [comment]
I believe these features would be better as separate packages. And they probably shouldn't depend directly on react-spring, but instead provide hooks that interoperate with react-spring (or any other animation library that uses hooks) in an elegant way.

So I'm closing this as "out of scope".

**Comment by aleclarson** [comment]
`react-intersection-observer` might help you with viewport detection: https://www.npmjs.com/package/react-intersection-observer
