### ISSUE TITLE
useTransition on redux object array causes rerender loop when items are removed

### ISSUE THREAD

**Issue by chriscamplin** [react-spring/react-spring#636]
I'm animating the sorting & loading of a large list of items from a redux store using the useTransition hook. It works really well except when toggling a button that removes some or all of the items in the list.

When items are removed it appears to loop through all the items in the array forcing a rerender each time, which means the UI can't be interacted with until it's finished.

I've tried to use react memo to prevent rerender but it's not playing nicely with react-spring.

Could this an issue with mixing redux & hooks, or is there a way to avoid rerender on every array item?

unsure if this is a bug, or something i've missed so please adjust the label accordingly, thanks.

**Comment by aleclarson** [comment]
Can you provide a CodeSandbox link or Github repo so I can take a closer look?

**Comment by chriscamplin** [comment]
@aleclarson it's a bit difficult to replicate the issue in a sandbox, it's a GRAPHQL app with redux state management, it's in a private repo for work so can't really share access.


`  let generateAnimatedRows = useTransition(
    animatedRows.map(playerList => ({
      ...playerList,
      y: (height += playerList.height) - playerList.height
    })),
    d => d.playerId,
    {
      from: { height: 0, opacity: 0 },
      enter: ({ y, height }) => ({ y, height, opacity: 1 }),
      leave: { height: 0, opacity: 0 },
      update: ({ y, height }) => ({ y, height }),
      config: { delay: 2000, mass: 4, tension: 500, friction: 80 },
      unique: true
    }
  );
`

obviously the above doesn't give away much, but the animatedRows array is from the redux store

**Comment by aleclarson** [comment]
If it's an issue with react-spring, you can rip out the GraphQL and Redux parts.

https://stackoverflow.com/help/mcve
