### ISSUE TITLE
v9 gesture regression

### ISSUE THREAD

**Issue by subhero24** [react-spring/react-spring#645]
## 🐛 Bug Report

The following react-with-gesture demo does not work in v9.0
https://codesandbox.io/embed/zq19y1xr9m

I don't know how the API in 9.0 is different from 8.0, and thus if this is intentional, otherwise this is a regression with v9.0

## To Reproduce

Switch version of react-spring in codesandbox to v9.0.0-beta

**Comment by aleclarson** [comment]
Nice catch! 👍

**Note:** It has nothing to do with gestures. The controller doesn't compare `config` props anymore to determine if an animation should be updated. Only the "goal value" and `reset` prop are checked, so you need to use `reset: !down` to ensure the decay animation is created. Or you could ensure that the `xy` prop is different from the previous `set` call.

https://codesandbox.io/s/v01n79qjj0

**Comment by phaistonian** [comment]
Related: I am not sure `config.decay` is documented anywhere -  as far as I noticed.

I am also not quite sure what it does :)

**Comment by aleclarson** [comment]
@phaistonian It's for gradual decay of velocity (think of scroll animations).
