### ISSUE TITLE
Missing TypeScript declaration file for react-spring/universal export (universal.d.ts)

### ISSUE THREAD

**Issue by flsilva** [react-spring/react-spring#647]
## 🐛 Bug Report

There's not `universal.d.ts` file, so when we import stuff from `react-spring/universal` we get the following TypeScript error:

```
Could not find a declaration file for module 'react-spring/universal'. '/PATH_TO_PROJECT_ROOT/node_modules/react-spring/universal.js' implicitly has an 'any' type.
  Try `npm install @types/react-spring` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-spring/universal';`ts(7016)
```

## To Reproduce

Just start a new TypeScript project and import `animated` and `useSpring` from `react-spring/universal`.

## Expected behavior

We should have a `universal.d.ts` file just like we have for web and native.

## Environment

This affects `react-spring 9.0.0-beta.1` but also `8.0.19`.

Thank you for your time and work.

**Comment by aleclarson** [comment]
Fixed in the v9.0.0-beta.3
