### ISSUE TITLE
Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by bytewoopy** [react-spring/react-spring#648]
## 🐛 Bug Report

I have seen other people mention some similar issue with 'push' recently. I am having this happen using the Trail component with data that is being fed as a list. The list is a state and gets updated via componentDidUpdate()

If i pull this out of the trail component and just render the Animated box by mapping groupIdsByDayData[i], everything works fine but of course I lose all the fancy animations.

```
<Trail
                                native
                                config={config.gentle}
                                // items={this.groupsDataArrayForDay(i)}
                                items={groupIdsByDayData[i]}
                                keys={item => item.id}
                                from={{ opacity: 0, x: 40 }}
                                to={{ opacity: 1, x: 0 }}>
                                {item => ({ x, opacity }) => {
                                    let editState = editing
                                    if (item.program_id !== program.id){
                                        editState = false
                                    }
                                    return(

                                        <AnimatedGroupBox style={{
                                            opacity,
                                        }
                                        }
                                                          color = {this.props.allPrograms[item.program_id].color}
                                                          key={item.id}
                                                          group={item} edit = {editState} />
                                    )}}
                            </Trail>


```
![image](https://user-images.githubusercontent.com/48188775/56631841-dd995e00-660b-11e9-9027-28ea5aff1560.png)

**debugger links to this part of the app.js code, some part of Spring?**
![image](https://user-images.githubusercontent.com/48188775/56631992-8e9ff880-660c-11e9-971f-abaa91f059a1.png)

## To Reproduce

Hard to reproduce, happens randomly after I try a few updates.

## Expected behavior

that it magically works :)

## Link to repro (highly encouraged)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

"react-spring": "^8.0.19",
"react": "^16.8.6",
"react-dom": "^16.8.6",

**Comment by bytewoopy** [comment]
If I use just a SPRING component and map the list manually, it also seems to work.
```

{groupIdsByDayData[i] && groupIdsByDayData[i].map(item =>
                                <Spring
                                    native
                                    key={"new"+item.id}
                                    config={config.wobbly}
                                    from={{ willChange: 'opacity,transform', opacity: 0, transform: 'translate3d(0,-40px,0)' }}
                                    to={{ opacity: 1, transform: 'translate3d(0,0px,0)' }}>
                                    {styles =>
                                                <AnimatedGroupBox style={styles}
                                                color = {this.props.allPrograms[item.program_id].color}
                                                key={item.id}
                                                group={item}/>}
                                </Spring>

                                                )}
```

**Comment by aleclarson** [comment]
Can you try it with the v9 beta?

```sh
npm install react-spring@next
```

Make sure to change the import path:
```js
// You can import the <Trail> component from the main module now.
import { Trail } from 'react-spring'
```

**Comment by aleclarson** [comment]
Hello @bytewoopy. Please try with `react-spring@next` and I'll reopen if the issue persists.

**Comment by colepeters** [comment]
I'm experiencing the same issue with `useTrail` in 8.0.27, however upgrading to `react-spring@next` isn't viable for me at the moment due to other issues with trails that I've noted in the v9 issue. For me, this error occurs when the animated component is unmounted.

Here's the error's call stack, I can provide more information if needed!

![image](https://user-images.githubusercontent.com/1713932/70668360-03c24b80-1c39-11ea-977f-be4544e9e90f.png)
