### ISSUE TITLE
9.0.0-beta.1: Renderprops Transition can't be used for show/hide

### ISSUE THREAD

**Issue by bhollis** [react-spring/react-spring#650]
## 🐛 Bug Report

If I try to follow the example code from "mount/unmount single-component reveals" at https://www.react-spring.io/docs/props/transition with v9, I get `children(...) is not a function`.

## To Reproduce

Create a Transition where the renderprops function can return false/null.

## Expected behavior

It should show and hide the element.

## Link to repro (highly encouraged)

https://codesandbox.io/embed/6j61zvk453

## Environment

- `react-spring` v9.0.0-beta
- `react` v16.8.4

**Comment by aleclarson** [comment]
Fixed in v9.0.0-beta.4
