### ISSUE TITLE
V9-branch: npm build generates invalid dist

### ISSUE THREAD

**Issue by Nizarius** [react-spring/react-spring#651]
## 🐛 Bug Report
(A clear and concise description of what the bug is.)

V9 branch in repository generates wrong output files which calls error in computeGoalValue function:

```
Uncaught TypeError: interpolation is not a function
    at computeGoalValue (web.js:1642)
    at Controller._animate (web.js:1385)
```

## To Reproduce
- fork v9 branch
- yarn -> yarn build
- use it as npm dependency instead of react-spring@next 

## Expected behavior
Should work as react-spring@next

## Environment
- 'npm' 6.9.0

**Comment by aleclarson** [comment]
What JS code is required to trigger the error?

**Comment by aleclarson** [comment]
Please try with the newest beta 👍

**Comment by Nizarius** [comment]
@aleclarson yeah, that works! Thank you.
