### ISSUE TITLE
[react-native] Cannot animate shadowOffset props on iOS

### ISSUE THREAD

**Issue by flsilva** [react-spring/react-spring#655]
## 🐛 Bug Report

I'm trying to animate `shadowOffset` props (`width` and `height`) on iOS and getting the following error:

![error-image](https://user-images.githubusercontent.com/544957/56830623-33088180-683d-11e9-83a6-e8a8d783df78.jpg)

I don't know if that's a `react-spring` issue, or a React Native's limitation that we can work around. Please let me know what you think.

## To Reproduce

Try to animate `shadowOffset`'s `width` and `height` (see link to repo below).

## Expected behavior

We should be able to animate those props like any other.

## Link to repro

I've created a GitHub repository to reproduce the bug. Please take a look at it and read instructions and more details on its README file:

https://github.com/flsilva/react-spring-ios-shadow-issue

## Environment

- `react 16.8.6`
- `react-native 0.59.5`
- `react-spring 9.0.0-beta.3`

But the issue can also be seen using `react-spring 8.0.19`.

Thank you for your time and work.

**Comment by aleclarson** [comment]
@flsilva This is now supported in v9.0.0-beta.4

Give it a try and LMK how it goes 👍

**Comment by flsilva** [comment]
@aleclarson Amazing! I've just tested it in `v9.0.0-beta.5` and it works! Thank you for your great work.
