### ISSUE TITLE
9.0.0-beta.x: useSprings won't work with plain objects anymore

### ISSUE THREAD

**Issue by dbismut** [react-spring/react-spring#657]
## 🐛 Bug Report

In **8.x**, useSprings `set` would accept a function but also a plain object:

```jsx
const [props, set] = useSprings(nb, () => ({ x: 0 }));
// in 8.x, this:
set({ x: 100 });
// was similar to this:
set(i => ({ x: 100 }));
```

Only the second option works properly in  **9.0.0-beta.4**: the former doesn't throw an error but doesn't work as expected (only the first index seems to update).

## To Reproduce

Comment or uncomment line 12/13 and try dragging the colored squares:
https://codesandbox.io/s/4xonnmkpv4

- Line 12 uncommented: only the blue square drags
- Line 13 uncommented: all colored square drags (expected behavior)

## Environment

- `react-spring` v9.0.0-beta.4
- `react` v16.8.6
- all browsers

**Comment by aleclarson** [comment]
This will be fixed in the next beta 🎉
