### ISSUE TITLE
onRest callback within useSpring cannot access updated component state

### ISSUE THREAD

**Issue by bmcmahen** [react-spring/react-spring#660]
This isn't really a bug per-se since it's kinda how closures work, but let's say you have a useSpring like this:

```jsx
const [isOpen, setIsOpen] = React.useState(false);
 
 const [{ xy }, setSpring] = useSpring(() => {
    const { x, y } = getDefaultPositions(isOpen, position);
    return {
      xy: [x, y],
      config: animationConfig,
      onRest: ya => {
        console.log(isOpen);
      }
    };
  });
```
From my experience, `isOpen` will always return `false` even if its value has changed to `true` within the component. Ideally we could access updated state here. 

You can see this in action on this [codesandbox](https://codesandbox.io/embed/5k1y5lny6p). Open the console and try dragging the dot around.

In my experience, you can fix this sort of thing by doing something like this:

```jsx
function useSpring(fns) {
  const callbacks = React.useRef(fns);

 React.useEffect(() => {
   callbacks.current = fns;
 }, [fns])

 // and then make calls to callback.current.onRest... 
}
```

I've taken a quick look at the source, but feel a bit like a deer in headlights. Not sure how easy this would be to fix for someone more knowledgeable of the codebase.

**Comment by bmcmahen** [comment]
I've found a solution on my end. Refs to the rescue!

```jsx
const [isOpen, setIsOpen] = React.useState(false);
const isOpenRef = React.useRef(isOpen);

React.useEffect(() => {
  isOpenRef.current = isOpen;
}, [isOpen])
 
 const [{ xy }, setSpring] = useSpring(() => {
    const { x, y } = getDefaultPositions(isOpen, position);
    return {
      xy: [x, y],
      config: animationConfig,
      onRest: ya => {
        console.log(isOpenRef.current);
      }
    };
  });
```
I still wonder if this could be made easier.

**Comment by aleclarson** [comment]
`useCallback` can be useful here

```ts
const [isOpen, setIsOpen] = React.useState(false)
const onRest = React.useCallback(() => {
  console.log('isOpen:', isOpen)
}, [isOpen])

const props = useSpring(() => {
  return {
    onRest: () => onRest(),
  }
})
```

**Comment by aleclarson** [comment]
@satya164 recently pointed out [here](https://twitter.com/satya164/status/1145950215494610944) that my solution is incorrect. (Thanks Satya!)

Here's another workaround that *should* work as expected:
```js
const [isOpen, setIsOpen] = React.useState(false)
const [props, update] = useSpring(() => ({ ... }))
React.useEffect(() => {
  update({
    onRest() {
      console.log('isOpen:', isOpen)
    }
  })
}, [isOpen])
```

Once v9 is released, you'll be able to use a "dependencies array" just like useEffect:
```js
const [isOpen, setIsOpen] = React.useState(false)
const [props, update] = useSpring(() => ({
  /* ...initialProps */
  onRest() {
    console.log('isOpen:', isOpen)
  }
}), [isOpen])
```

Note: If your initial props are expensive to compute (which they usually are if you're passing a function to `useSpring`), you'll want to wrap them in a useMemo call like this:
```js
const [isOpen, setIsOpen] = React.useState(false)
const initialProps = React.useMemo(() => ({ ... }))
const [props, update] = useSpring(() => ({
  ...initialProps,
  onRest() {
    console.log('isOpen:', isOpen)
  }
}), [isOpen])
```

**Comment by aleclarson** [comment]
Most of the time, it's premature optimization to pass a function to `useSpring`. For your own sanity, just pass an object and you won't need the dependencies array.
```js
const [isOpen, setIsOpen] = React.useState(false)
const [props, update] = useSpring({
  ...initialProps,
  onRest() {
    console.log('isOpen:', isOpen)
  }
})
```
**Note:** This is the v9 API that isn't released yet (not even in the beta). See here: #670

**Comment by bmcmahen** [comment]
Looking forward to the new API - looks great. fwiw, i've consistently been using my `ref` solution that I posted above, which seems to work.

**Comment by jonisapp** [comment]
> Most of the time, it's premature optimization to pass a function to `useSpring`. For your own sanity, just pass an object.
> 
> ```js
> const [isOpen, setIsOpen] = React.useState(false)
> const [props, update] = useSpring({
>   ...initialProps,
>   onRest() {
>     console.log('isOpen:', isOpen)
>   }
> }, [isOpen])
> ```
> 
> **Note:** This is the v9 API that isn't released yet (not even in the beta). See here: #670

Passing a function rather than an object allows to directly apply the animation on the component, thus avoiding a useless re-render of it and all its children. So it's a costless optimization which could make a big difference (as if the component you are animating does contain a large tree).

**Comment by jonisapp** [comment]
The best solution I have found is to put onRest in the setter function. Like this : 
`
const [ isOpen, setIsOpen ] = useState(false);
const [ spring, setSpring ] = useSpring(() => ({
  config: { ... }
}));
setSpring({ ...props, onRest() { console.log(isOpen) } })
`
