### ISSUE TITLE
Can no longer reproduce auto height carousel demo on modern react-spring

### ISSUE THREAD

**Issue by exogen** [react-spring/react-spring#661]
## 🐛 Bug Report

I'm trying to reproduce this older modal + carousel demo that was created with react-spring v5: https://codesandbox.io/s/2vp5ny068n?from-embed

The demo behaves nicely. The challenging part is that the carousel animates smoothly from one slide's height to the next.

I've updated the demo as faithfully as possible to modern react-spring here: https://codesandbox.io/s/72kx5p3zr0?fontsize=14 – this includes using `items` and `config` on the Transition component, and using `item => props => ...` instead of just `props => ...`, and importing from `react-spring/renderprops`.

Unfortunately the height transition no longer works: it jumps around unexpectedly.

I've noticed that in recent react-spring size-transition demos, they resort to using a resize observer constantly watching the content. This would be very disappointing to me if it were the new suggested approach – a major reason for using an animation library at all in the first place is that it supports animating `height: auto`, and I'd like to *only* animate it during the slide transition (after which it should go back to `auto`, not be an exact `px` value controlled by a resize observer).

## To Reproduce

Modern demo: https://codesandbox.io/s/72kx5p3zr0?fontsize=14

The height behaves erratically.

## Expected behavior

Old demo: https://codesandbox.io/s/2vp5ny068n?from-embed

The height transitions smoothly between slides.

## Environment

- `react-spring` v8.0.20
- `react` v16.8.6

**Comment by aleclarson** [comment]
We're definitely open to suggestions on how to improve the DX for animating to fluid values via the new hooks API.

**Comment by drcmda** [comment]
The problem with auto is that if it is automated it will never fulfil all use-cases. Even the one you mentioned is deeply flawed, what if the content size changes inside while it animates towards auto for instance. The point in rem removing it is that now it's under your control. If you don't want it to watch for resize changes you don't need to use a resizeObserver. At this point there are already dozens of measure hooks that make dealing with this property relatively easy.

I tried looking what's up but there's code in there i don't understand, like

    <Spring native force from={{ height: "auto" }} to={{ height: "auto" }}>

If this has worked in version 5 it must have been a bug.
