### ISSUE TITLE
[react-native & web] Cannot rerender right away with different props

### ISSUE THREAD

**Issue by flsilva** [react-spring/react-spring#662]
## 🐛 Bug Report

Here's what I'm trying to achieve and the error I'm getting (simplified version implemented in a repro repository with link below):

I have a button `<TouchableWithoutFeedback>` (blue box on screen). That button has an internal `interactionState` that can be set from its parent (default to `enabled`), and is also set when we press the button (to `pressed`).

When the `interactionState === "pressed"` the button triggers an animation (inner red box grows).

Everything works fine in the base scenario, i.e., the button starts with "enabled" state and when we tap it changing its state to `"pressed"` we can see the animation.

The problem happens on a different scenario: we start the button state as `"pressed"` right away, forcing it to rerender with different props right away (due to the way its implemented). We then get a runtime error, but the expected behavior is to get the inner red box animating right away (right after rendering the app).

The following error can be seen on iOS and Android:

![error-shot](https://user-images.githubusercontent.com/544957/57184100-b012a700-6e8c-11e9-81ee-9ac8b9b6ee7f.jpg)

I can also see an error on web using `react-native-web` with a slightly different message, but seems to be the same error.

I've also tested using `react-spring 8.0.20` and although there's no runtime error, there's no animation either, i.e., nothing happens visually (inner red box doesn't animate right away).

## To Reproduce

I've created a repo to reproduce it (link below), but here's the whole thing to (hopefully) make it easier to discuss the issue:

```js
import React, { useState } from "react";
import { StyleSheet, TouchableWithoutFeedback, View } from "react-native";
import { animated, useSpring } from "react-spring/native";

const AnimatedView = animated(View);

const useMyAnimation = interactionState => {
  const [isAnimating, setIsAnimating] = useState(false);
  const [animateToProps, setAnimateToProps] = useState({
    config: { friction: 20, tension: 170 },
    from: { scale: 1 },
    to: { scale: 1 }
  });
  const motionProps = useSpring(animateToProps);

  if (interactionState === "pressed" && !isAnimating) {
    setIsAnimating(true);
    setAnimateToProps({
      config: { friction: 20, tension: 170 },
      to: { scale: 2 }
    });
  }

  return motionProps;
};

const MyButton = props => {
  const onPress = () => {
    setInteractionState("pressed");
  };

  const [interactionState, setInteractionState] = useState(
    props.interactionState || "enabled"
  );
  const motionProps = useMyAnimation(interactionState);

  const motionStyle = {
    ...styles.redBox,
    transform: [{ scale: motionProps.scale }]
  };

  return (
    <TouchableWithoutFeedback onPress={onPress}>
      <View style={styles.blueBox}>
        <AnimatedView style={motionStyle} />
      </View>
    </TouchableWithoutFeedback>
  );
};

export default () => {
  // comment the next line  and uncomment the following one
  // to see everything working, i.e., when we tap the blue box
  // we can see the red box growing
  return <MyButton interactionState="pressed" />;
  // return <MyButton />;
};

const styles = StyleSheet.create({
  blueBox: {
    backgroundColor: "blue",
    height: 100,
    margin: 50,
    width: 100
  },
  redBox: {
    backgroundColor: "red",
    height: 20,
    width: 20
  }
});
```

## Expected behavior

We see the inner red box animating right away, i.e., right after rendering the app, with no runtime errors.

## Link to repro

Here's a repo with a functional app:

https://github.com/flsilva/react-spring-rerender-issue

## Environment

- `react 16.8.6`
- `react-native 0.59.5`
- `react-spring 9.0.0-beta.5`

Thank you for your time and work.

**Comment by aleclarson** [comment]
Please try with 9.0.0-beta.7

Thanks 👍

**Comment by flsilva** [comment]
@aleclarson Thank you a lot for looking into this. I've just tested it, updating the reproduction repo to use `9.0.0-beta.7`, and although there are no runtime errors anymore (iOS and Android), the animation is not triggered either, i.e., I just see the inner red box at its initial state, but it should animate right away, increasing its size as its scale is animated, since it does runs the code inside this condition (which is what was causing the runtime error):

```js
if (interactionState === "pressed" && !isAnimating) {
  setIsAnimating(true);
  setAnimateToProps({
    config: { friction: 20, tension: 170 },
    to: { scale: 2 }
  });
}
```

**Comment by aleclarson** [comment]
You shouldn't call `useState` setters during render. You need to wrap that code with `useLayoutEffect` and it will work.
