### ISSUE TITLE
AnimatedValue Memory Leak

### ISSUE THREAD

**Issue by derindutz** [react-spring/react-spring#673]
## 🐛 Bug Report

AnimatedValues are being created but not deleted when using nextjs and SSR.

https://spectrum.chat/react-spring/general/animated-component-is-causing-memory-leak~1190af03-e0c9-4e6d-9d07-1419581424a2 may be relevant.

## To Reproduce

Create an AnimatedValue (animated.div) server-side using nextjs.

## Expected behavior

The AnimatedValues are properly cleaned up.

## Environment

- `react-spring` ^v8.0.18
- `react` ^v16.8.0

<img width="1212" alt="react-spring memory leak" src="https://user-images.githubusercontent.com/5715140/58056223-3e398f00-7b15-11e9-941d-2b1f079d0189.png">

**Comment by Tarpsvo** [comment]
The same seems to happen with `useTransition`. Left a Next.JS site with a `useTransition` carousel open overnight, Chrome stopped the site due to out-of-memory exception.

See this image: https://d.pr/i/PO1PYy

**Comment by ShanonJackson** [comment]
This is happening to me also.

**Comment by aleclarson** [comment]
Please try with `react-spring@next`. 👍 

If that doesn't work, run [`@react-spring/envinfo`](https://www.npmjs.com/package/@react-spring/envinfo) and create a gist with the output like [this](https://gist.github.com/aleclarson/ba281a405c11de494c5575696323307c). 
Then paste that link here. Thanks!

**Comment by VincentCtr** [comment]
Hello there,
We have the same issue here. react-spring@next fixed it and I did not see any regression (yet).

Thanks @aleclarson

**Comment by v-Bauer** [comment]
Hi,
is it possible that you still fix this bug in v8? We also have this problem and cannot update to v9beta due to other bugs.

**Comment by marcusthelin** [comment]
After upgrading to latest v9 version our memory usage stabilized. We've had this memory leak for a long time, and it took a while for us to figure out it was because of this lib. 
![image](https://user-images.githubusercontent.com/22647302/142992177-23ac41a0-41a5-4212-8154-d741eebf882d.png)
