### ISSUE TITLE
Animate SVG feDisplacementMap

### ISSUE THREAD

**Issue by gloompi** [react-spring/react-spring#674]
## 🤓 Question

Hello!

I've got a guestion, since in new version of spring we are using the animated elements, like animated.div etc, is there any animated.feDisplacementMap element, to forward dinamically some attributes like scale to it? Or any other ways to make it works, thanks in advance!

**Comment by drcmda** [comment]
You can make them yourself, see: https://codesandbox.io/embed/rloj7nw3pn

```jsx
const AnimFeDisplacementMap = animated('feDisplacementMap')

function App() {
  const { scale } = useSpring({ from: { scale: 10 }, scale: 150 })
  return <AnimFeDisplacementMap scale={scale} />
}
```

**Comment by gloompi** [comment]
> They're not part of the exported set, but you can make them yourself, see: https://codesandbox.io/embed/rloj7nw3pn
> 
> ```js-jsx
> const AnimFeDisplacementMap = animated('feDisplacementMap')
> 
> function App() {
>   const { scale } = useSpring({ from: { scale: 10 }, scale: 150 })
>   return <AnimFeDisplacementMap scale={scale} />
> }
> ```

Thanks a lot)
