### ISSUE TITLE
hooks api `native` option ?

### ISSUE THREAD

**Issue by littlee** [react-spring/react-spring#681]
I noticed render-props api can pass native to achieve better performance
https://www.react-spring.io/docs/props/performance

but I don't see this option in hooks api, how ?

**Comment by drcmda** [comment]
They’re native by default. :)

**Comment by aleclarson** [comment]
Note: The RN version does *not* execute animations in native land yet.

**Comment by drcmda** [comment]
"native" meaning it will animate outside of react but mutate the view directly, react-spring/native does this by default as well. RN would need some other flag i guess to indicate that the animation doesn't happen in javascript at all.
