### ISSUE TITLE
minification

### ISSUE THREAD

**Issue by a-m-dev** [react-spring/react-spring#682]
## 🐛 Bug Report
when i run yarn build with create react app , i got this error 
```
Failed to minify the code from this file: 

 	./node_modules/react-spring/renderprops.js:13 
```
but when i run yarn start every thing is ok.

## To Reproduce
boot up create react app  and install react-spring. use it and build the project to get it...

## Expected behavior
just build successfully...

## Environment

- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by drcmda** [comment]
Do you use terser? The old uglify cannot minify modern javascript, it's been deprecated.

**Comment by aleclarson** [comment]
Correct me if I'm wrong, but this seems like a problem with CRA.

**Comment by alphakennyn** [comment]
I'm getting a similar issue:

```
Failed to minify the code from this file:
   ./node_modules/react-spring/web.js:7
```

for `"react-spring": "^8.0.27"`

**Comment by myhendry** [comment]
Hi. Any solution to this issue? i get this error when i run yarn run build

Failed to minify the code from this file: 

        ./node_modules/react-spring/web.js:7

**Comment by alphakennyn** [comment]
@myhendry use CRA version 3+

**Comment by josh231101** [comment]
I am having a lot of troubles upgrading react-scripts :-1:  Same problems as you man, any help?

> Hi. Any solution to this issue? i get this error when i run yarn run build
> 
> Failed to minify the code from this file:
> 
> ```
>     ./node_modules/react-spring/web.js:7 
> ```
