### ISSUE TITLE
[HOOKS] Set spring velocity

### ISSUE THREAD

**Issue by MarcusCemes** [react-spring/react-spring#684]
## 🚀 Feature Proposal

Ability to set velocity using the hooks API

## Motivation

Gesture-based interaction. react-spring aims to create more natural movement by creating motion that obeys the laws of physics. While this creates natural movement, it doesn't obey gesture-based friction.

Gestures appear most fluid and performant when they use `setImmediate: true`. In reality, pushing something around with your finger should be instant. Dragging something across the screen should not lag behind, as it has a physical connection to your finger.

While `setImmediate` creates reactive motion, returning to a normal spring state (`setImmediate: false`) will reset the velocity to 0;

## Example

My use-case for this is a drag-out sidebar. At the moment, as soon as you release the gesture, it will essentially freeze and speed up again into the open position.

This would work well with the [react-use-gesture](https://github.com/react-spring/react-use-gesture) library, which exposes a `last` property, signifying that the gesture has been released and a two-dimensional `vxvy` vector (array). On the last callback, the velocity could be set using the `set` function of `useSpring`.

My proposal for an implementation is:

```
const [ lastPosition, setlastPosition ] = useState(CLOSED_POSITION);
const [ props, set ] = useSpring(() => ({ x: CLOSED_POSITION });

const bind = useGesture(() => {
  onDrag: ({ last, vxvy, delta }) => {
    if (last) {
      const snapTo = vxvy[0] > 0 ? OPEN_STATE : CLOSED_STATE;
->    set({ x: snapTo, immediate: false, config: {velocity: { x: vxvy }} });
      setLastPosition(snapTo);
      return;
    }
    set({ x: lastPosition + delta, immediate: true });
  }
});

return <Sidebar {...bind()} style={{ transform: props.x.interpolate(x => `translate3d(${x}, 0, 0)`) }} />
```

Please excuse me if something similar exists, but I haven't found any documentation/issues/pull requests that discuss this.

#### EDIT:
I just saw that my "proposal" above for setting velocity doesn't really work or make sense. What I meant was:

```set({ x: snapTo, immediate: false, config: {velocity: { x: vxvy[0] }} });```

where `vxvy` is a 2D array passed from useGesture (for example `[0.2, 0.5]`). I'm not sure how react-spring works internally, I assume that each variable in `useSpring` has its own independent spring, in which case each spring's velocity could be set with a single `number`, interpolation could make it confusing though.

**Comment by aleclarson** [comment]
Please provide a CodeSandbox so I can have a closer look. 👍

**Comment by MarcusCemes** [comment]
https://codesandbox.io/embed/reactspring-set-velocity-issue-w8s3g

This is a use-case that I came up with.

It features a sidebar that can be dragged open/closed, with a speed graph showing the current horizontal velocity of the sidebar.

While the gesture is active, `immediate` is enabled for real-time feedback, and once the gesture is released, `immediate` is disable to return to spring-like motion. However, when the spring is released, the speed is reset to zero, as if the spring "forgot" its motion.

![react-spring](https://user-images.githubusercontent.com/20288819/58705387-529c4800-83af-11e9-9146-e41acf6cd757.png)

I have exaggerated the spring config to be extra slow to allow you to notice this undesirable behaviour, it is less noticeable when using normal spring parameters, however, it remains noticeable when interacting with the sidebar. It just lacks that fluid movement (because it suddenly stops on release), but usually accelerates back up to (albeit a slightly lower) speed to not be *toooo* annoying.

The draggable pink ball example in the docs avoids using `immediate` altogether by providing a high tension/friction combination to try to follow the cursor as close as possible.

Personally, I find that the `immediate` option has no real use at the moment, as it's impossible to exit this state without resetting the object's velocity. A setVelocity option (or velocity config option when using hooks) would allow us to describe the spring's desired motion when re-entering the world of Newtonian physics, therefore providing a smooth transition between `immediate: true` and `immediate: false`.

Thoughts? Would it be difficult to implement internally? I don't actually understand the `velocity` config option, I haven't been able to figure out how it works, however, the docs claim it allows us to give an initial velocity when creating the spring?

**Comment by aleclarson** [comment]
Thanks for the write-up and example! Something definitely seems off. I'll take a look before releasing the next beta (which should be today).

**Comment by MarcusCemes** [comment]
Sorry for bumping this up, is there any progress on this? Is there any way I could help?

**Comment by dbismut** [comment]
Hey, I’m on my phone and haven’t tested the sandbox, but try this: useGesture will give you velocity per axis (vxvy). When releasing the element, you can set config to have an initial velocity based on vxvy.

However, react-spring uses a velocity / s while useGesture (and many other libs) uses a velocity / ms. To properly set the initial velocity in react-spring, you’ll need to multiply it by `1000`. 

I’ve submitted the PR #797 that among other things should normalize all velocities in milliseconds. 

Hope that helps, apologies if not, I’ve read this quickly on my phone!

**Comment by aleclarson** [comment]
After taking a closer look at [this sandbox](https://codesandbox.io/embed/reactspring-set-velocity-issue-w8s3g), I don't think there's an issue here.

```js
setX({ x: nextState, config: { velocity: vxvy[0] } });
```
Replacing line 41 in `sidebar.js` with the line above works as expected.

Let me know if I'm missing something! 👍

**Comment by MarcusCemes** [comment]
https://codesandbox.io/embed/react-spring-set-velocity-issue-example-2-d358q

Just tried another variant here. It seems to be working good, I don't remember setting the velocity in the config working after initialization... But perhaps I was forgetting the factor of 1000 that @dbismut mentioned due to the unit difference.

Thank you to both of you for your time on this issue!

**Comment by aleclarson** [comment]
> Another thing to note, setting the velocity via `config` will wipe any previous config... Custom spring parameters have to be re-specified each time.

Not in v9 ;)

**Comment by aleclarson** [comment]
> Another thing to note, setting the velocity via `config` will wipe any previous config... Custom spring parameters have to be re-specified each time.

Thanks for pointing this out. It will be fixed before v9 is released. 👍
