### ISSUE TITLE
[TypeScript] Missing scrollTop and scrollLeft typings

### ISSUE THREAD

**Issue by RafalFilipek** [react-spring/react-spring#692]
## 🐛 Bug Report

`scrollTop` and `scrollLeft` are missing in `animated.*`

## Link to repro (highly encouraged)

https://codesandbox.io/s/inspiring-cookies-grx45

## Environment

- `react-spring` v8.0.20, 9.0.0-beta.8
- `react` v16.8.4
- `typescript` v3.5.1, v3.3.3

**Comment by aleclarson** [comment]
Fixed in v9.0.0-beta.9
