### ISSUE TITLE
[TypeScript] Interpolate range shortcut error

### ISSUE THREAD

**Issue by TheBear44** [react-spring/react-spring#696]
## 🐛 Bug Report

Typescript reports error when using interpolate range shortcut.

`Expected 1 arguments, but got 2.ts(2554)`

## To Reproduce

Steps to reproduce the behavior: Use interpolate range shortcut.

```
value.interpolate([0,1], [1,100])
```

## Expected behavior

No error.

## Link to repro
https://codesandbox.io/s/zen-nash-d79rp

## Environment

- `react-spring` v8.0.22
- `react` v16.8.6

**Comment by aleclarson** [comment]
Unlikely that this will be fixed. You could try using `react-spring@next` instead.
