### ISSUE TITLE
animated(<custom functional React component>) doesn't animate

### ISSUE THREAD

**Issue by quickhand** [react-spring/react-spring#697]
## 🐛 Bug Report

I wish to animate a prop on a functional component, but updates are never triggered. The component is wrapped with animated. Converting the component to a class component solves the problem, but the whole purpose of using the hooks-based interface is to get away from using class components. "Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?" appears in the console. 

## Link to repro

https://codesandbox.io/embed/react-spring-animated-custom-components-ijh22

## Environment

- `react-spring` v8.0.21
- `react` v16.8.6

**Comment by drcmda** [comment]
this should be fixed now. made a patch.

**Comment by runemadsen** [comment]
I am running into the same problem with `9.2.3`. This warning is shown in the dev console:

```
index.js:27 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

Same sandbox as above, but changing `react-spring` to `9.2.3` will display the warning.
