### ISSUE TITLE
[useSpring] get current animated value

### ISSUE THREAD

**Issue by aamorozov** [react-spring/react-spring#698]
#### react-spring version: 9.0.0-beta.8

It used to be possible to access the value with the render props api, but I've been trying to do so with useSpring hook for a good few hours already and wasn't able to. My use case is basically trying to calculate the size of an element to determine whether or not to render its child. 

#### render props api
```jsx
 <Spring
      from={{
        height: 0,
      }}
      to={{
        height: expanded ? ELEMENT_HEIGHT : 0,
      }}
 >
 {({height, opacity, padding}) => (
        // height value is accessible here throughout interpolation.
```

#### useSpring hook 
```jsx
const {height} = useSpring({
  height: expanded ? ELEMENT_HEIGHT : 0,
});
// height value is accessible when doing interpolation
<animated.div style={{height: height.interpolate(v => `${v}px`)} />

// but not if i want to render a child conditionally 
<animated.div style={{height: height.interpolate(v => `${v}px`)}>
    {height > 50 && <p>hello</p>}
</animated.div>
```

Am I doing something wrong here? Thank you in advance for looking into this.

**Comment by aleclarson** [comment]
Try something like this:
```js
const [visible, setVisible] = React.useState(false)
const {height} = useSpring({
  onFrame({ height }) {
    if (height > 50) setVisible(true)
  }
})
```

**Comment by aamorozov** [comment]
Thank you! It worked like a charm 🎉

**Comment by vuthpov** [comment]
hi,
I tried to put the onFrame on version 9.0.0-rc.3
nothing happend

**Comment by aleclarson** [comment]
@vuthpov See the [Breaking Changes](https://aleclarson.github.io/react-spring/v9/breaking-changes/#The-onFrame-prop) section.
