### ISSUE TITLE
useTransition does not apply animation when items are sorted

### ISSUE THREAD

**Issue by quiin** [react-spring/react-spring#700]
## 🐛 Bug Report
Hello, I'm trying to apply a fade-in animation on a list of items when they're displayed and when they're being sorted. 
To do that, I'm using the `useTransition` hook and it seems to be working just fine the very first time the list of items is displayed. However, whenever the list is sorted, the animation is just not triggered at all.
Am I doing something wrong? 
Is this the expected behavior? 
if so, how could I trigger the animation when sorting changes?

## To Reproduce
Sort the items list by either number, title, date or type
https://codesandbox.io/s/late-mountain-iesd2

## Expected behavior
Fade-in animation to be applied when items are changed (e.g sorted)

## Link to repro (highly encouraged)
https://codesandbox.io/s/late-mountain-iesd2

## Environment
- `react-spring` v8.0.23
- `react` 16.8.6

**Comment by aleclarson** [comment]
There's an demo for list reordering: https://github.com/react-spring/react-spring-examples/blob/111bd7eb6308b95213e963712660a0441e3a4bd2/demos/hooks/list-reordering/index.js#L15-L25

**Comment by GfxKai** [comment]
Any simple way of doing this for variable height elements? In the demo, height is passed explicitly for each element which is kinda cheating 😜
