### ISSUE TITLE
v9 type errors with typescript

### ISSUE THREAD

**Issue by kodai3** [react-spring/react-spring#702]
## 🤓 Question
Thanks for the great work!!
I believe it is because style require React.CSSProperty rather than any since v9.

when I try like [this](https://codesandbox.io/s/great-babbage-c39po?fontsize=14) or 
```style={props}```
is shows error because props returns SpringValue<T>

and when like [this](https://codesandbox.io/s/dreamy-morse-ejjmn?fontsize=14) or ```interpolate()```
is shows error because string dose not meet PositionProperty type

so, how should I use position propperty with typescript

**Comment by dagstuan** [comment]
I noticed this too. With the new typings for the v9 beta `interpolate` is not working properly anymore if it's used for certain CSS properties such as `visibility`. Example here: https://codesandbox.io/s/flamboyant-tu-npoxr

**Comment by aleclarson** [comment]
As you've noticed, the `position` and `visibility` props have a string union type, rather than the wider `string` type. You need to cast your string to ensure it has the right type.

```ts
type Position = React.CSSProperties['position']

// In your `useSpring` call or similar:
from: { position: "absolute" as Position, opacity: 0 },
```

It would be unsafe for `react-spring` to widen those props to `string`, so you (unfortunately) need to manually ensure your values are the correct type.

**Comment by dagstuan** [comment]
@aleclarson would it be possible to define a generic overload for `interpolate`? Casting the result doesnt seem to be working: https://codesandbox.io/s/flamboyant-tu-npoxr

Ideally I would like to be able to call `interpolate` such as this: `opacity.interpolate<Visibility>(x => x === 0 ? "hidden" : "visible")`

**Comment by aleclarson** [comment]
@dagstuan I've made it less strict about the return type, so casting should work now. 👍

**Comment by dagstuan** [comment]
@aleclarson perfect, works great now, thank you! 👍

**Comment by aleclarson** [comment]
**Note:** For 100% type safety, you should be using `as const` instead.

**Comment by louisgv** [comment]
> **Note:** For 100% type safety, you should be using `as const` instead.

Can you please elaborate? If you can give a quick code example. Thanks in advance!
