### ISSUE TITLE
onRest is not a function

### ISSUE THREAD

**Issue by danielhusar** [react-spring/react-spring#703]
## 🐛 Bug Report

Hey guys,
this error keep getting into our sentry.
I'm not even sure why as I'm not using `onRest` callback in any of our animations.

Error looks like this:

<img width="407" alt="Screen Shot 2019-06-16 at 19 03 12" src="https://user-images.githubusercontent.com/1857751/59573790-788d4200-9069-11e9-8638-9fe2a9d8f18b.png">

It happens pretty much solely in chrome:
<img width="1281" alt="Screen Shot 2019-06-16 at 19 03 28" src="https://user-images.githubusercontent.com/1857751/59573802-804ce680-9069-11e9-805e-a4d75f7263bd.png">

## To Reproduce

I wasn't been able to reproduce, but our app runs in all sort of crazy environments. (It's an app customers embed in their pages).

Posting here mainly for visibility in case anybody sees something similar.

## Environment

- `react-spring` 9.0.0-beta.8
- `react` v16.8.6

**Comment by aleclarson** [comment]
We don't minify the build anymore, so you should try deploying the latest beta.

**Comment by danielhusar** [comment]
Thanks! I ll try new version and post here if errors occurs again.

**Comment by danielhusar** [comment]
BTW not sure if related but I'm using cjs version, otherwise I would need to run babel on `node_modules` dependency.

**Comment by danielhusar** [comment]
Still the same:

![sentry io_organizations_intercom_issues_1084187702__project=24287 query=is%3Aunresolved statsPeriod=14d (1)](https://user-images.githubusercontent.com/1857751/60057249-b822e200-9698-11e9-9955-845af8c77fe6.png)

**Comment by aleclarson** [comment]
I don't think that's possible. Could that error be from an older version of your app?

There is no variable named `t` being called like a function in `@react-spring/core/index.cjs.js`.

**Comment by danielhusar** [comment]
I think `t` is there from minified build: (somehow sentry is not picking up the proper function name, not sure why)

<img width="384" alt="Screen Shot 2019-06-24 at 16 31 37" src="https://user-images.githubusercontent.com/1857751/60058543-911adf00-969d-11e9-8eaa-02c46fa7d644.png">

It's basically this line:
<img width="547" alt="Screen Shot 2019-06-24 at 16 32 33" src="https://user-images.githubusercontent.com/1857751/60058564-b1e33480-969d-11e9-850a-1612ea3ebd86.png">

Its latest version from today.

Maybe `if (onRest) onRest(_this3.merged);` can be changed to `if (typeof onRest === 'function') onRest(_this3.merged);` ?

**Comment by aleclarson** [comment]
Added a bunch of type guards in 038e741a3e98372af2186423552f7b19b5297a16

In the newest beta, you can use `onAnimate` to investigate the issue further (if you care):

```js
// This prop works with all hooks/renderprops
onAnimate(props, controller) {
  if (typeof props.onRest !== 'function') {
    console.error('Hey sentry, check this out: onRest ===', props.onRest)
  }
}
```

**Comment by littlee** [comment]
I had the same issue with `beat.23`.

`v9.0.0-beta.24` is ojbk !!!
