### ISSUE TITLE
Parallax - The amount of pages does not equal accumulated factor and offset

### ISSUE THREAD

**Issue by ddennis** [react-spring/react-spring#707]
## 🐛 Bug Report

The amount of pages does not equal the accumulated factor and offset

## To Reproduce

[https://codesandbox.io/s/react-spring-parallax-dpqb5](https://codesandbox.io/s/react-spring-parallax-dpqb5)

## Expected behavior
<ParallaxLayer **factor={0.5} offset={0}** speed={1}>
<ParallaxLayer **factor={0.5} offset={0.5}** speed={1}>
<ParallaxLayer **factor={1} offset={0.99}** speed={1}>

I would expect that the three layers would fill up 2 pages.
Further more changing the last layers offset to **1**, instead of **.99**, moves the last layer to the bottom causing a gap 

## Environment

- `react-spring` v8.0.25

**Comment by aleclarson** [comment]
> The amount of pages does not equal the accumulated factor and offset

That's not true. You have `speed={1}` on the last layer, so it's moving up the page as you scroll, thus creating an empty space on the last page. If you do `speed={0}`, the last layer stays put and the empty space disappears.
