### ISSUE TITLE
Invalid prop.style key error on expo/styled components project

### ISSUE THREAD

**Issue by bgazzera** [react-spring/react-spring#709]
## 🐛 Bug Report

The [docs](https://www.react-spring.io/docs/hooks/basics) say that to apply an animation to a styled component you must do:
```
const AnimatedHeader = styled(animated.h1)`
  ...;
`
```
In the context of trying this in an expo project running in web and native I found that the order in which animated() and styled() are applied is important.
If I try the documented way `styled(animated(Text))`there is an error. 
![Screen Shot 2019-06-19 at 18 29 16](https://user-images.githubusercontent.com/6751553/59802947-7b35a480-92c0-11e9-8572-2164d0d843ec.jpg)

If I invert the order `animated(styled(Text))` it works. 
![Screen Shot 2019-06-19 at 18 16 51](https://user-images.githubusercontent.com/6751553/59802938-753fc380-92c0-11e9-896e-bff3eb76c84b.jpg)

## To Reproduce
Assuming your dev machine is a Mac

1. Install expo-cli (I'm using 2.20.1)

2. git clone git@github.com:bgazzera/react-spring-9.0.0-beta.22-bug-repro.git
3. cd react-spring-9.0.0-beta.22-bug-repro
4. yarn
5. expo start -w -i
6. You should see an animated "Hello world" message both on your browser and iOS simulator
7. Uncomment lines 8-14 and comment lines 50-56 on `App.tsx` 
8. You should see the error in the iOS simulator:

> Warning: Failed prop type: Invalid props.style key `0` supplied to `Text`.
Bad object: {
  "0": {
    "fontSize": 15,
    "textAlign": "center",
    "color": "palevioletred",
    "opacity": 1
  },
  "1": {
    "opacity": {
      "children": [],
      "animatedStyles": {},
      "done": true,
      "value": 0,
      "startPosition": 0,
      "lastPosition": 0
    }
  }
}
Valid keys: [
  "display",
  "width",
  "height",
  "start",
...

## Expected behavior

I expected the documented way of applying an animation to a styled component should work.

## Link to repro (highly encouraged)

https://github.com/bgazzera/react-spring-9.0.0-beta.22-bug-repro

## Environment

-     "expo": "^33.0.0",
-     "react": "16.8.3",
-     "react-dom": "^16.8.6",
-     "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
-     "react-native-web": "^0.11.4",
-     "react-spring": "^9.0.0-beta.22",
-     "styled-components": "^5.0.0-beta.3"
-     "@types/react": "^16.8.19",
-     "@types/react-native": "^0.57.60",
-     "babel-preset-expo": "^5.1.1",
-     "typescript": "^3.4.5"

**Comment by bgazzera** [comment]
Of course this issue may not be originated in react-spring, but rather on SC or elsewhere. 

Just a day's worth of experience with the library but I'll be happy to help anyway I can on this.

**Comment by aleclarson** [comment]
I recently updated the `animated` function, so this might be fixed in the latest beta. Let me know! 👍

**Comment by aleclarson** [comment]
Closing this until you try with the latest beta.
