### ISSUE TITLE
BUG | trail.map does not handle invalid items?

### ISSUE THREAD

**Issue by louisgv** [react-spring/react-spring#713]
## 🐛 Bug Report

trail.map throws error on invalid item. This in turn causes a domino-like effect that make other react-sprint component not render properly(?).

## To Reproduce

1. Create a trail component
2. If the items turned empty or null, an error is thrown: https://pastebin.com/Xs0tmxey

## Expected behavior

Trail should handle null items.

## Link to repro (highly encouraged)

I tried my best to create a repro but can't get as close to show the error in pastebin. I got it to fix on my project by doing a prop check and return null ( as shown in the codesandbox )

https://codesandbox.io/embed/icy-river-yjdtc

## Environment

- `react-spring` v9.0.0-beta.23
- `react` v16.8.x (or `react-native` v0.58.x)

Refer to the convo in https://github.com/react-spring/react-spring/issues/642#issuecomment-504468621

**Comment by aleclarson** [comment]
Default props only work for undefined values, but you're passing a null value as the `letter` prop. This isn't anything to do with react-spring. It's how JS works.
