### ISSUE TITLE
How can I slow down useTransition?

### ISSUE THREAD

**Issue by rchrdnsh** [react-spring/react-spring#715]
So I finally have useTransition working properly (YAY!) but the fade out and in again is just a little bit too fast for my tastes.

Is there any way to slow down the animation a bit?

Here's my code:

```js
const ViewContainer = (props) => {
  const [state] = useState(true);
  const transition = useTransition(state, null, { 
    from: { opacity: 0 },
    enter: { opacity: 1 },
    leave: { opacity: 0 }
  });
  return transition.map(({ item, key, props: fade }) =>
    item && <Container key={key} style={fade}>{props.children}</Container>
  )
}
```

**Comment by aleclarson** [comment]
See here: https://www.react-spring.io/docs/hooks/api

**Comment by rchrdnsh** [comment]
so, first i tried this, and nothing seemed to change:

```js
const ViewContainer = (props) => {
  const [state] = useState(true);
  const transition = useTransition(state, null, { 
    from: { opacity: 0, config: config.molasses },
    enter: { opacity: 1, config: config.molasses },
    leave: { opacity: 0, config: config.molasses }
  });
  return transition.map(({ item, key, props: fade }) =>
    item && <Container key={key} style={fade}>{props.children}</Container>
  )
}

export default ViewContainer
```

then I tried this:

```js
const ViewContainer = (props) => {
  const [state] = useState(true);
  const transition = useTransition(state, null, { 
    from: { opacity: 0, config: { duration: 1000 } },
    enter: { opacity: 1, config: { duration: 1000 } },
    leave: { opacity: 0, config: { duration: 1000 } }
  });
  return transition.map(({ item, key, props: fade }) =>
    item && <Container key={key} style={fade}>{props.children}</Container>
  )
}

export default ViewContainer
```

...and got a few error messages, including:

<img width="395" alt="Screenshot 2019-06-23 19 13 51" src="https://user-images.githubusercontent.com/7884263/59986292-0f6a7900-95eb-11e9-939c-be962c439204.png">

so, I guess I don't quite get how to implement things from the common API in the useTransition hook specifically. I can get them to work in the useSpring hook, but the useTransition hook seems to work differently, no?

**Comment by aleclarson** [comment]
1. You should **always** provide a repro (eg: CodeSandbox or git repository)
2. Make sure your `Container` component is wrapped with `animated()`
3. The `from` prop must only contain animated values, so `config` is invalid

If 2 and 3 don't fix your problem, come back with 1. Thanks 👍

**Comment by jakewtaylor** [comment]
I have a somewhat similar issue, not sure what I'm doing wrong here.

I have a component like this (bezier method is from `bezier-easing` package):
```JSX
const easing = bezier(.61,.16,.24,1.53);

const Button = ({ onClick, children }) => {
    const { expanded, setExpanded } = useContext(FabContext);
    const transitions = useTransition(expanded, null, {
        from: { transform: 'scale(0)' },
        enter: { transform: 'scale(1)' },
        leave: { transform: 'scale(0)' },
        config: {
            duration: 100,
            easing: t => easing(t),
        },
    });

    const handleClick = (e) => {
        e.preventDefault();
        setExpanded(false);

        onClick();
    };

    return transitions.map(({ item, key, props }) => item ? (
        <animated.button key={key} style={props} onClick={handleClick} className="fab --child">
            {children}
        </animated.button>
    ) : null);
};
```
For some reason, the easing doesn't ever seem to do anything for me. Any ideas?

Sorry if this is the wrong place to ask.

**Comment by aleclarson** [comment]
@jakewtaylor 	Please open a new issue.
