### ISSUE TITLE
unmet peer dependency "react-native@>=0.58"

### ISSUE THREAD

**Issue by danielhusar** [react-spring/react-spring#719]
## 🐛 Bug Report

React spring show this warning when installing latest bets.
Im not using react-native so it seems weird to have peer dependency on it.

```
warning "react-spring > @react-spring/native@9.0.0-beta.24" has unmet peer dependency "react-native@>=0.58".
warning "react-spring > @react-spring/konva@9.0.0-beta.24" has unmet peer dependency "konva@>=2.6".
warning "react-spring > @react-spring/konva@9.0.0-beta.24" has unmet peer dependency "react-konva@>=16.8".
warning "react-spring > @react-spring/three@9.0.0-beta.24" has unmet peer dependency "react-three-fiber@>=2.0".
warning "react-spring > @react-spring/three@9.0.0-beta.24" has unmet peer dependency "three@>=0.104".
warning "react-spring > @react-spring/zdog@9.0.0-beta.24" has unmet peer dependency "react-zdog@>=1.0".
warning "react-spring > @react-spring/zdog@9.0.0-beta.24" has unmet peer dependency "zdog@>=1.0".
```

## To Reproduce

`npm install react-spring@9.0.0-beta.24`

## Expected behavior

No unmet peer dependency warnings

## Environment

- `react-spring` 9.0.0-beta.24
- `react` v16.8.6

**Comment by aleclarson** [comment]
The `react-spring` package is now an umbrella for all platforms. You can safely ignore those warnings for the platforms you're not using. To remove those warnings, you can use a platform-specific package like `@react-spring/web`. 👍

**Comment by aleclarson** [comment]
Also, if you want to keep your imports the same but also remove those warnings, you can use dependency aliasing like so:

```json
"dependencies": {
  "react-spring": "npm:@react-spring/web@^9.0.0-beta.24"
}
```

**Comment by danielhusar** [comment]
Nice, sorry for issue!
I was trying find documentation for v9 but I guess it doesn't exists yet?

**Comment by aleclarson** [comment]
Yeah, not yet. I'll need to find time for that, but I'm trying to ship products atm. 😊
