### ISSUE TITLE
Component re-render during sprint animation stops the browser

### ISSUE THREAD

**Issue by bginsburg** [react-spring/react-spring#721]
I have this sprint animation that draws a bouncing ball on the screen:
```
export default function Visual() {
  const { radians } = useSpring({
    to: async next => {
      while (1) {
        await next({ radians: 2 * Math.PI })
      } 
    },
    from: { radians: (5 * Math.PI) },
    config: { duration: 3500 },
    reset: true,
    reverse:true,
  })

  return items.map(i => <animated.div id='ball' key={i} className='ball-motion' style={{ transform: radians.interpolate(interp(i)) }} />)
}
```

Its called from App.js this way:
```
      render () {
            {this.state.shouldRender && <Visual/>}
      }
```

If a different prop from the App component state changes (causing re-rendering) and the `shouldRender` is true the whole time the browser will jam and stop working

I would expect it to stop the current render and re-render as react does.

## Environment

- `react-spring` v8.0.25
- `react` v16.8.6

**Comment by aleclarson** [comment]
Try with the latest beta:
```
npm install react-spring@next
```
If that doesn't work, please provide a CodeSandbox. Thanks 👍

**Comment by bginsburg** [comment]
Hi @aleclarson `9.0.0-beta.25` solved it!!  is it a known issue?
Can you refer me to the issue/commit it was resolved in?

**Comment by aleclarson** [comment]
Good! 👍 Not sure which commit fixed it, but the problem seemed to be that `await next(...)` never resolved.
