### ISSUE TITLE
Delay between onRest/unmount and animation end

### ISSUE THREAD

**Issue by ericbf** [react-spring/react-spring#724]
## 🐛 Bug Report

This is pretty much the same as #99, but the solution mentioned in that issue, as well as referenced in #85 and #154 (restSpeedThreshold, restDisplacementThreshold, overshootClamping) doesn't seem to be present in the code anymore (at least, doing a search of the code doesn't find these properties, and they don't seem to change anything in the behavior. Not to mention "undocumented" properties breaking the typescript type definitions).

## To Reproduce

Use a Transition to mount/unmount an overlay with opacity. When the overlay is unmounting, see that it still blocks clicks for a good 500ms after it's functionally invisible (so not present as far as the user is concerned).

## Expected behavior

Once the component is functionally done animating (as far as the user can perceive), the animation should be done.

## Link to repro (highly encouraged)

https://codesandbox.io/embed/upbeat-oskar-xlhom

Click the button to show the overlay, then click the overlay to hide it. Wait for the overlay to be gone, then click the button again. You'll see that there's a pause between when the overlay is fully invisible and when the button can be clicked again (not obscured by the invisible overlay).

## Environment

- `react-spring` v8.0.25
- `react` v16.8.6

**Comment by aleclarson** [comment]
You want the `config.precision` and `config.clamp` props. Also, consider using `pointerEvents: 'none'` to allow interactions before the fade out is finished.

**Comment by ericbf** [comment]
> You want the `config.precision` and `config.clamp` props.
Not really. These only change the fidelity with which the calculations are done, and cuts off the animation once it hits the target (which would break "bouncy" animations, wouldn't it?).

> Also, consider using `pointerEvents: 'none'` in your component style to allow interactions before the fade out is finished.
This is also a non-solution. Users shouldn't be able to click through the overlay, that'd be silly in most cases (ours included).

**Comment by aleclarson** [comment]
> Not really. These only change the fidelity with which the calculations are done, and cuts off the animation once it hits the target (which would break "bouncy" animations, wouldn't it?).

You were using `config.overshootClamping` in your sandbox, which has been renamed to `config.clamp` in this library. The `config.precision` prop replaces `config.restSpeedThreshold` and `config.restDisplacementThreshold` (notice the similarity between [this](https://github.com/animatedjs/animated/blob/c0429818a927eca68dfd5abdc562897cf1c109a2/src/SpringAnimation.js#L198-L202) and [this](https://github.com/react-spring/react-spring/blob/4803f24539ee949c6c547b932df4bfe44f3be4f5/packages/core/src/FrameLoop.ts#L197-L201)).

> This is also a non-solution. Users shouldn't be able to click through the overlay, that'd be silly in most cases (ours included).

You would set `pointerEvents` to `none` only when the "fade out" animation starts. And when the "fade in" animation starts, you would set it back to `auto` or whatever.

**Comment by ericbf** [comment]
@aleclarson I'll take a look :)
