### ISSUE TITLE
useTransition: how to update enter state value

### ISSUE THREAD

**Issue by crazyxhz** [react-spring/react-spring#725]
## 🤓 Question
I want to build an upload FileList with collapse and upload progress animation. When a bunch of files is uploaded, the FileList expands to 48px height with a progress bar. After uploaded completed. the progress bar is gone and the height shrink to 32px. But using the code below the FileList Item Container will always stay on 48px height.
I think this scenario is some what related to useTrail ? Maybe combine useTransition and useTrail?
```
const transitions = useTransition(uploaded, k => k.uid, {
        from: { height: 0 },
        enter: (item: any) => async (next: any) => await next({ height: item.isLoading ? 48 : 32 }),
        leave: { height: 0, overflow: 'hidden' },
        config: {
            tension: 300,
            clamp: true,
        },
    } as any);
```

**Comment by crazyxhz** [comment]
seems change `k => k.uid` to `k => k.uid + k.isLoading` solved the above problem. But the uploaded item seems to be rendered multiples times for a short time
![ezgif-4-1f87523493f5](https://user-images.githubusercontent.com/6551888/60332716-ff2b1300-99c9-11e9-99c4-6d0f373b1df9.gif)

**Comment by aleclarson** [comment]
To avoid the duplicate render issue, set `unique: true`.
