### ISSUE TITLE
Invalid .cjs.js imports for @react-spring/shared

### ISSUE THREAD

**Issue by nhardy** [react-spring/react-spring#730]
## 🐛 Bug Report

It looks like 274afad introduced an issue with CommonJS imports. `@react-spring/shared` does not currently have a rollup config that would output `.cjs.js` files, yet these are now being referenced as a result of that change.

I've added [a comment](https://github.com/react-spring/react-spring/issues/642#issuecomment-507108860) to the beta feedback issue already.

## To Reproduce

Install v9.0.0-beta.28 and use a commonjs entrypoint. This will then complain about being unable to resolve `@react-spring/shared/global.cjs.js` as this file does not exist.

## Environment

- `react-spring` v9.0.0-beta.28
- `react` v16.8.6

**Comment by aleclarson** [comment]
Thanks for the bug report! I'm gonna revert that commit and publish a new beta. 👍
