### ISSUE TITLE
Export just a few more interfaces

### ISSUE THREAD

**Issue by natew** [react-spring/react-spring#733]
Just a small request, I'm trying to use `SpringsUpdateFn` as a argument to a function and it's not currently exported, could we export that and the other UpdateFn types?

**Comment by aleclarson** [comment]
Looks like `SpringsUpdateFn` is the only missing export related to the "update" functions. Are there any other types you had in mind?

**Comment by natew** [comment]
If the others are exported that's great!

**Comment by natew** [comment]
Actually, related but different:

```
import { withAnimated } from '@react-spring/animated'
import { config as configs, Controller, SpringConfig } from '@react-spring/core'
import { useOnce } from '@react-spring/shared'
import { defaultElement as View, requestAnimationFrame } from '@react-spring/shared/globals'
```

I've forked Parallax and am changing a few things in it. For now I had to add these to my package.json, any reason they aren't exported through the main package, or am I mistaken and they are? It's a little weird adding three sub-packages to the package.json for these.

**Comment by aleclarson** [comment]
Did you try importing them first? 😉 Those are all exported by `react-spring`, except `useOnce` which isn't meant to be part of the public API.

```ts
import { Globals, withAnimated, config, Controller, SpringConfig } from 'react-spring'

const { defaultElement: View, requestAnimationFrame } = Globals
```

Of course, I didn't expect you to know that `Globals` exists. Each platform-specific package like `@react-spring/web` (whose exports are [here](https://github.com/react-spring/react-spring/blob/v9/targets/web/src/index.ts)) re-exports all of `@react-spring/core` (whose exports are [here](https://github.com/react-spring/react-spring/blob/v9/packages/core/src/index.ts)).

Hope that helps!

**Comment by natew** [comment]
Ah, I see, the renaming withAnimated + Globals. useOnce I can deal with importing a package, thanks for the help!

**Comment by natew** [comment]
I do get a type error using `animated` I don't get using `withAnimated`:

![image](https://user-images.githubusercontent.com/12100/60539012-9ccf5c80-9cc0-11e9-9d4f-90e02b805020.png)

It's not happy with potentially getting a string.

**Comment by aleclarson** [comment]
@natew The `animated` function is platform-specific, so it only allows strings from `keyof JSX.IntrinsicElements` (at least in the case of `@react-spring/web`).

As a workaround, you can do this instead:
```js
import { withAnimated } from '@react-spring/animated'
```

**Comment by gonzarodriguezt** [comment]
Following this, i'm trying to use `react-spring/three` in a typescript project, but i got this error: 
```
Could not find a declaration file for module 'react-spring/three'
```
I've tried to add some types myself but i'm not getting to run my fork locally, it doesn't recognize `react-string/three` as a module. 

Any suggestions? @aleclarson
