### ISSUE TITLE
Rename "props" to "styles" or something else

### ISSUE THREAD

**Issue by dongepulango** [react-spring/react-spring#734]
The name `props` that is pass to `style={}` is very confusing with the regular React `props.value`. I'm sure I'm not the only one thinking this. I've seen some tutorials that says it's confusing to them as well.

I'm sure there is a reason why this is called **props**, but for me it's not helping. `styles` or `animations` is my suggestions.

**Comment by aleclarson** [comment]
You can name it whatever you like, no?

**Comment by dongepulango** [comment]
You can, but would it be better if you don't have to?

**Comment by aleclarson** [comment]
I don't understand. Can you give an example that would be easier?

**Comment by dongepulango** [comment]
![Screen Shot 2019-07-02 at 8 56 59 PM](https://user-images.githubusercontent.com/5156884/60514408-02950600-9d0c-11e9-8b14-95267db24b87.png)
I mean there ^

**Comment by aleclarson** [comment]
Ahh, you didn't mention `useTransition` specifically.

**Comment by dongepulango** [comment]
Sorry about that. I know you can rename them `props: styles` but I just find it confusing sometimes, as well as other people in tutorials.

**Comment by drcmda** [comment]
the thing is, they're not styles, they can be, but essentially you're just interpolating arbitrary props, which you then cast into styles/attributes/etc.

but i dislike that we have to give it names and sometimes i think that going for an object was a mistake over:

```jsx
transitions.map(([visible, key, styles]) => ...
```

upside: naming, downside: you people have to remember the correct order.

we also had some other ideas, see: https://github.com/react-spring/react-spring/issues/665

**Comment by dongepulango** [comment]
Thanks for the explanation.

**Comment by drcmda** [comment]
wait, you're too quick : D this is a totally valid point, we can sure discuss how we can maybe solve it in a better way. feel free to give us your suggestions. do you like the array destructure for instance?
