### ISSUE TITLE
Overlapping componnts when using useSpring and animated

### ISSUE THREAD

**Issue by Aerts83** [react-spring/react-spring#735]
## 🐛 Bug Report

I used react-spring to make a simple toggleable slide down menu and it made components overlap. I turned down the opacity and I could see 2 div's stacked upon eachother. I didn't use any positioning. When I removed the animated.div it all worked fine again, minus not having the animation ofcourse. 

## To Reproduce

Create a div on the top of the page and a div with the animation below it.

## Expected behavior

I expected the div to behave like a normal block div.

- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by aleclarson** [comment]
This needs a CodeSandbox for anyone to help you
