### ISSUE TITLE
button TypeError: entry.interpolation.calc is not a function

### ISSUE THREAD

**Issue by gabrielmoncea** [react-spring/react-spring#740]
Hello!
## 🐛 Bug Report
I'm creating a React component library and when the value for disabled prop changes from true to false it throws me a TypeError: entry.interpolation.calc is not a function error.
The disabled prop is used to return a value that's passed to the useSpring object.

## To Reproduce

const colorSpring = props.disabled ? "default" : "green"
const springProps = useSpring({
  from: { opacity: 0 },
  opacity: 1,
  color: colorSpring,
})

## Expected behavior

Change the color to green.

## Link to repro (highly encouraged)
In this sandbox it also crashes but I'm not sure if it's because of the sandbox the error is a bit different.
https://codesandbox.io/s/nifty-banach-cm3h2

## Environment

- `react-spring` v8.0.27
- `react` v16.8.6

**Comment by aleclarson** [comment]
There is no `"default"` color. See here: https://github.com/react-spring/react-spring/blob/512f1e849d6d94729f0fce929e531e1a3249a318/packages/shared/src/colors.ts#L3-L152
