### ISSUE TITLE
Constant animations still perform even after successful component Unmount

### ISSUE THREAD

**Issue by mgolawski** [react-spring/react-spring#741]
## 🐛 Bug Report
There is an issue with the way how constant `useSpring` animations based on `while` loop are behaving after successful animated component unmount. Given examples on react-spring website rely on this approach to perform infinite animations:
https://codesandbox.io/embed/8ypj5vq6m9
https://codesandbox.io/embed/141nrz6v73

While you unmount that animated components, the asynchronous functions are still called in the background.

## To Reproduce
1. Create a functional component
2. Adds async `useSpring` animation with `while` loop inside 
```
  const { radians } = useSpring({
    from: { radians: 0 },
    to: async next => {
      while (1) {
        console.log(`Playing animation ${new Date()}`);
        await next({ radians: 2 * Math.PI });
      }
    },
    reset: true
  });
```
3. Unmount component in any way
4. Observe the console

## Expected behaviour
The callstack for this animation method should be terminated in parallel to the component unmount effect. It is a memory leak, that can cause to the browser card freeze for more complicated SVG animations (which happened in my case)

## Link to repro (highly encouraged)
I created the [CodeSandbox example](https://codesandbox.io/s/gmlq8) that helps to spot this issue.

## Environment

- `react-spring` v8.0.18
- `react` v16.8.3

**Comment by aleclarson** [comment]
This is fixed in v9

```sh
npm install react-spring@next
```

**Comment by steady-join** [comment]
@aleclarson When is it released?v9

**Comment by aleclarson** [comment]
@steady-join Before the end of the year, probably. You can use it today, just pin the version instead of using caret ranges.

**Comment by brunolemos** [comment]
I just noticed this on my app using v8. Here's how you can fix it on user land:

```jsx
const isMountedRef = useRef(true)
  useEffect(() => {
    return () => {
      isMountedRef.current = false
    }
  }, [])
```

```diff
-while (true) {
+while (isMountedRef.current) {
```

I think this should be fixed on v8 as well, since v9 is still months away.
