### ISSUE TITLE
Using with Rollup to bundle together

### ISSUE THREAD

**Issue by raunofreiberg** [react-spring/react-spring#742]
I can't figure out how to use `react-spring` (`v8.0.27`) while building a React component library. All the hooks (`useTransition` etc) work fine until I bundle everything together into a ES module (note that I also use `rollup-plugin-terser` which seems to maybe be the problem?)

After rolling the library into a ES module, I try to use it in a CRA app by importing the component using `react-spring` and I get the following error:

`react__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function`

which traces itself back to

![image](https://user-images.githubusercontent.com/23662329/60677283-c5568280-9e89-11e9-9301-810c2ecffb8d.png)

and it seems to come from `AnimatedValue`

**Comment by aleclarson** [comment]
Have you tried disabling Terser to see if the error persists?

**Comment by raunofreiberg** [comment]
Disabling Terser does indeed get rid of the error, but I'd like to use it.

**Comment by aleclarson** [comment]
If it works without Terser, then this is a Terser issue, no?

**Comment by raunofreiberg** [comment]
I'm not 100% sure, hence the question here. 

Funnily enough, I took the same bundle (with Terser) and inserted it as a JS file in a React Codesandbox and it does not throw the error there. 

Codesandbox with minimal bundle: https://codesandbox.io/s/blue-dawn-2g5x2

Now, using the same bundle in a CRA in the same manner throws:

`TypeError: react__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function`

**Comment by aleclarson** [comment]
Then it must be a webpack issue. 😆

**Comment by raunofreiberg** [comment]
I think Codesandbox uses the same configuration as CRA does, yes :-)

**Comment by aleclarson** [comment]
cc @gaearon

**Comment by raunofreiberg** [comment]
For now, as a workaround I set `react-spring` as a peer dependency in my library, instead of bundling it together with components.
