### ISSUE TITLE
IOS9 SyntaxError: Unexpected keyword 'const'.

### ISSUE THREAD

**Issue by licong96** [react-spring/react-spring#754]
## 🐛 Bug Report

Mobile phone：IOS 9.3.5
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

## Environment

- `react-spring` v8.0.23
- `react` v16.8.8

**Comment by licong96** [comment]
The reason is that webpack does not compile the files below node_modules.

**Comment by slorber** [comment]
Also got this error on older Edge which does not support some syntax.

Seems related to this https://github.com/react-spring/react-spring/issues/552
