### ISSUE TITLE
Any way to pause animation at certain values?

### ISSUE THREAD

**Issue by cosmophile** [react-spring/react-spring#755]
I'm scrolling a few short lines of banner text using the scrollTop property on an overflow-hidden style div. (config is duration based for now.)

Is there any way I could possibly pause the animation for short periods at certain values of the scroll property? Don't mind getting my hands dirty, but would appreciate some guidance on where to look.

Thanks!

**Comment by danieloi** [comment]
sounds like a chain animation of some kind
