### ISSUE TITLE
Parallax & ParallaxLayer wrong typescript types (TS2322 on official example)

### ISSUE THREAD

**Issue by RUVATA** [react-spring/react-spring#762]
## 🐛 **Bug Report**

In fact the ParallaxLayer and Parallax (wrapper) classes signature should implements HTMLDivElement and abstract HTMLElement.
Placed to them properties are provided to native element 'as is', realization talks thats it is intention of developer.
Another argument that the official example of usage of Parallax, actively used placement props as 'style', 'onClick' handler and other.

**Steps to reproduce the behavior:**

## Link to repro (highly encouraged)

see fork of official example, where index file extension changed to TSX
[React-Spring Prallax TS2322 Errors](https://codesandbox.io/embed/react-spring-prallax-ts2322-errors-15m21)

## Environment

- `react-spring` v8.x.x
- `react` v16.8.x

**Comment by RUVATA** [comment]
#761

**Comment by aleclarson** [comment]
The newest types are at `@react-spring/parallax`. Could you give those a try, and report back if you have any issues? Thanks 👍
