### ISSUE TITLE
Non interpolatable values block animation

### ISSUE THREAD

**Issue by dbismut** [react-spring/react-spring#765]
## 🐛 Bug Report

I'm not sure if this is by design, but when adding non-interpolable attributes to the spring (such as `position` moving from `relative` to `absolute`) prevents other interpolable values from animating.

The reason why this is important is that I'm in a situation where I need to change the `position` depending on if I'm in a transition phase.

## Expected behavior

I would expect `position` to jump from its start to end value, while the rest of the values animate as usual.

## Link to repro

https://codesandbox.io/s/react-use-gesture-template-cecz9

If you click on the button, you should see the pink square jumping from one position to another instead of smoothly moving.

The `animating` object set as the `from` attribute of the spring (line 32) is responsible for blocking the animation. If you add `left` and `top` properties to it, the animation runs smoothly though.

## Environment

- `react-spring` v9.0.0b31
- `react` v16.8.6

**Comment by aleclarson** [comment]
The sandbox was using v8, since `latest` doesn't point to the beta. It seems to work fine with v9.

**Comment by dbismut** [comment]
You're right. That's so weird as hovering on the version showed the beta as being installed. Thanks for the help and sorry for this.
