### ISSUE TITLE
v9 type definition for the return of the interpolation/to 

### ISSUE THREAD

**Issue by brunolemos** [react-spring/react-spring#769]
## 🐛 Bug Report

The `interpolation` and `to` methods should accept any return type, not only the same one from the interpolated value.

For example, when interpolating a `height` of type `number`, if I want to return a `boolean` it complains. See example below.

## To Reproduce

```jsx
<AnimatedView hidden={animatedStyles.height.to(value => (value > 0 ? false : true))} />
```

` Type 'boolean' is not assignable to type 'number'.`

## Environment

- `react-spring` v9.0.0-beta.31
- `react` v16.8.6

**Comment by aleclarson** [comment]
Fixed in #808
