### ISSUE TITLE
Custom easing

### ISSUE THREAD

**Issue by brumeregan** [react-spring/react-spring#774]
## 🤓 Question

Hi, 
I want to use custom ease function like https://cubic-bezier.com/#.69,.28,0,1.09 . How can I do this with react-spring?
Thanks for helping or any suggestions in advance!)

**Comment by ahmedu007** [comment]
You can pass a `config` property to `useSpring` with whatever you want to do with it. 
If you look at the link below it should give you a good starting point.

https://www.react-spring.io/docs/hooks/api

**Comment by brumeregan** [comment]
@ahmedu007 thanks for respond, but config.easing accept function (t) => t, and I asked about bezier curves, like in CSS without any transformations like "bezier to system equation" )

**Comment by aleclarson** [comment]
https://www.npmjs.com/package/bezier-easing
