### ISSUE TITLE
SVG animation bug on iphone

### ISSUE THREAD

**Issue by skrichten** [react-spring/react-spring#775]
## 🐛 Bug Report

Animating the baseFrequency of feTurbulence does not work on iphone safari and chrome.

## To Reproduce

Use a spring interpolated value as the baseFrequency for feTurbulence. Works on desktop, but not on an iphone.

## Expected behavior

Should work the same as it does on desktop.  I have seen other working examples of this done with vanilla javascript
https://tympanus.net/codrops/2019/02/19/svg-filter-effects-creating-texture-with-feturbulence/.

## Link to repro (highly encouraged)

https://github.com/skrichten/ThreeDeeTalks/blob/master/src/components/DistortedImage.js
https://three-dee.netlify.com/wave

## Environment

- `react-spring` v8.0.20
- `react` v16.8.6

**Comment by danieloi** [comment]
I have a similar issue that appears here: 
https://codesandbox.io/embed/compassionate-galileo-e12pi

If you follow it on Chrome, the animation runs without issue but on safari for the desktop and iPhone no bueno

**Comment by danieloi** [comment]
Using breakpoints in Safari isn't as smooth as it is in Chrome. 

It's like the source map isn't working as it does with Chrome and Firefox. 

I create a StackOverflow question for my issue and I'll paste it here too. 

It's essentially the same code with the codesandbox from my previous comment but with more English descriptions. 

Here's the link to the StackOverflow question I just created: https://stackoverflow.com/questions/57694936/react-spring-svg-dashoffset-doesnt-animate-in-safari


Here's the additional info: 
The strokeDashoffset value is supposed to animate but it doesn't The logs to the console in the useCallback block show that when the DOM node is measured with getTotalLength(), the value is initially 0 in Safari unlike Chrome and Firefox but returns the proper value when the component unmounts.

Thank you

**Comment by aleclarson** [comment]
There have been other bugs with animating `<svg>` children in Safari (eg: #944), so I don't think there's much we can do.
