### ISSUE TITLE
Getting "TypeError: Cannot read property 'createElement' " on useSpring inside eact functional element

### ISSUE THREAD

**Issue by shubhamgautam** [react-spring/react-spring#780]
## 🐛 Bug Report
I was trying to play around with react-spring, while incorporating useSpring I am getting error as "TypeError: Cannot read property 'createElement' ", though it work for sometime and crash afterwards and useSpring doesn't work if I want to use it to transform the position of an element. 

## code snippet

import React, { useState, useEffect } from "react";
import { useSpring, animated, interpolate } from "react-spring";

const containerStyles = {
	width: "80%",
	height: "60vh",
};
const ShapeSelectorContainer = props => {
	let container = {
		height: 0,
		width: 0,
	};

	const style = useSpring({
		from: {
			left: "0%",
			top: "0%",
			width: "0%",
			height: "0%",
			background: "lightgreen",
		},
		to: async next => {
			while (1) {
				await next({
					left: "0%",
					top: "0%",
					width: "100%",
					height: "100%",
					background: "lightblue",
				});
				await next({ height: "50%", background: "lightgreen" });
				await next({
					width: "50%",
					left: "50%",
					background: "lightgoldenrodyellow",
				});
				await next({ top: "0%", height: "100%", background: "lightpink" });
				await next({ top: "50%", height: "50%", background: "lightsalmon" });
				await next({ width: "100%", left: "0%", background: "lightcoral" });
				await next({ width: "50%", background: "lightseagreen" });
				await next({ top: "0%", height: "100%", background: "lightskyblue" });
				await next({ width: "100%", background: "lightslategrey" });
			}
		},
	});
	return (
		<div style={containerStyles} className="shapeSelectorCont shape-container">
			{<animated.div className="rectangle" style={style} />}
		</div>
	);
};

export default ShapeSelectorContainer;
## Environment

- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by aleclarson** [comment]
Please provide a sandbox, and test with v9. Thanks!
