### ISSUE TITLE
Testing with Jest, Enzyme & Typescript: `Warning: React.createElement: type is invalid`

### ISSUE THREAD

**Issue by jimmy-e** [react-spring/react-spring#781]
## 🐛 Bug Report

Writing Jest / Enzyme tests with Typescript using React-Spring returns a warning.

## To Reproduce

Clone [this repo](https://github.com/jimmy-e/spring-test-debug).
Run `yarn`.
Run `yarn test navigation.test.tsx`

The expected warning is as follows:

```
  console.error node_modules/react/cjs/react.development.js:172
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

## Expected behavior

No warning should be returned. If you run `yarn test navigationTwo.test.tsx`, no warning is returned. This is a similar component, but instead it does not use React-Spring.

## Environment

- `react-spring` v8.0.27
- `react` v16.4.0

**Comment by jimmy-e** [comment]
@aleclarson was wondering if I could get an update?

**Comment by aleclarson** [comment]
Try with v9 beta:
```sh
npm i react-spring@next
```

**Comment by jimmy-e** [comment]
@aleclarson , I have updated [the repo](https://github.com/jimmy-e/spring-test-debug) with the latest version of react-spring (`^9.0.0-beta.33`) and updated importing but am still getting the same error message.

**Comment by jimmy-e** [comment]
@aleclarson is there any update with this?

**Comment by aleclarson** [comment]
I get this error when I run `yarn` in your repo:
```
An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.2.21.tgz: Request failed \"401 Unauthorized\"".
```

**Comment by jimmy-e** [comment]
@aleclarson , that issue should be resolved now.

**Comment by jimmy-e** [comment]
@aleclarson is there an update with this?

**Comment by aleclarson** [comment]
In `jest.config.js`, you should be using:
```js
'^react-spring$': '<rootDir>/node_modules/react-spring/web.cjs',
```
Without the `^` and `$`, you'll accidentally use that module for every package in the `@react-spring` package scope.

Your test ran fine when I removed that line entirely, so I don't think you even need it.
