### ISSUE TITLE
IE, Edge:) useTransition bug

### ISSUE THREAD

**Issue by n-ow** [react-spring/react-spring#784]
## 🐛 Bug Report

If make a page transition effect from IE, Edge to useTransition, the screen keeps flickering and broken. 😂

There is no problem in the chrome environment. Firefox is a bit unstable.

Is there a way to fix it?

## repro

https://codesandbox.io/embed/loving-jepsen-96eny

## Environment

- `react-spring` v8.0.19
- `react` v16.8
- `react-router-dom` v5.0.0
- `chrome` v76
- `firefox` v68.0.1
- `IE` v11
- `Edge` v44

**Comment by marcuslindfeldt** [comment]
useTransition does not animate at all for me in Edge. Tried both 8.0.19 and 9.0.0-beta.33

**Comment by n-ow** [comment]
Yes In the latest version of Windows Edge, your sandbox address works exactly. but sandbox address I uploaded doesn't work.

**Comment by aleclarson** [comment]
@n-ow Using `react-spring@9.0.0-canary.808.9.7e75a67`, your sandbox works fine after some minor changes. See [here](https://codesandbox.io/s/react-page-transition-effect-9fc3i) (will delete later).
