### ISSUE TITLE
Animations stop working after building with CRA

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring#787]
## 🐛 Bug Report

I have a weird issue. I've created a modal with below springs and I am using useChain hook to control them. Locally the animations work but once I build the React project (created from CRA) `npm run build` and host it either locally or somewhere in the cloud then only one animation is being triggered (I can see that based on the styles in code inspector).

## To Reproduce

Config:
```
const aProps = useSpring({
    ref: modalContentRef,
    config: { mass: 2, tension: 364, friction: 31 },
    from: { transform: "translate(-50%,-50%) scale(0)", opacity: 0 },
    to: {
      transform: isOpen
        ? "translate(-50%,-50%) scale(1)"
        : "translate(-50%,-50%) scale(0)",
      opacity: isOpen ? 1 : 0
    }
  });
  const bgOpacity = useSpring({
    ref: opacityRef,
    from: {
      opacity: 0
    },
    to: [
      {
        opacity: isOpen ? 0.32 : 0
      }
    ]
  });
  const bgScale = useSpring({
    ref: scaleRef,
    from: {
      transform: "scale(0)"
    },
    to: {
      transform: isOpen ? "scale(1)" : "scale(0)"
    },
    config: {
      duration: 1
    }
  });
```
Chain:
```
useChain(
    isOpen
      ? [scaleRef, opacityRef, modalContentRef]
      : [modalContentRef, opacityRef, scaleRef],
    isOpen ? [0, 0, 0.3] : [0, 0.3, 0.7]
  );
```

EDIT:
I've just downgraded to the latest version `8.0.27` and everything is working as expected with the same config.

_Originally posted by @mbaranovski in https://github.com/react-spring/react-spring/issues/642#issuecomment-515738586_

## Environment

- `react-spring` v9.0.0-beta.31
- `react` (unknown)

**Comment by aleclarson** [comment]
@mbaranovski Please provide a sandbox to make it easier to debug when someone gets time to look into this. Thanks!

**Comment by Spring3** [comment]
Could this be related? https://github.com/gatsbyjs/gatsby/issues/16718
