### ISSUE TITLE
Scrolling any Parallax scrollable children causes transform on them

### ISSUE THREAD

**Issue by hayyaun** [react-spring/react-spring#798]
I was using parallax with some div that scrolls horizontally,
when the content inside child div scroll, parallax starts transforming it's children vertically,
I first thaught it is my scroll event listener which listens to parallax.container
but after disabling that, I noticed that its parallax that causing this transform...
how can I stop this default reaction?

**Comment by aleclarson** [comment]
Please provide a sandbox that demonstrates the issue. 👍

**Comment by hayyaun** [comment]
I'll try to make a sandbox asap...
but there I find a way to stop that... 
by changing ParallaxLayer speed to 0 that layer won't transform on scroll

**Comment by hayyaun** [comment]
I'll try to make a sandbox asap...
but there I find a way to stop that... 
by changing ParallaxLayer speed to 0 that layer won't transform on scroll
