### ISSUE TITLE
Difficulty understanding the duration of physics-based animations

### ISSUE THREAD

**Issue by jmar777** [react-spring/react-spring#799]
I've spent some time reading the documentation and watching the announcement video, but I feel like I'm still missing something quite fundamental about how this library works.

Starting with a basic example from the documentation:

```js
import {useSpring, animated} from 'react-spring'

function App() {
  const props = useSpring({opacity: 1, from: {opacity: 0}})
  return <animated.div style={props}>I will fade in</animated.div>
}
```

As advertised, no durations are present in the API. The part I'm struggling to understand is how and why the values are manipulated at a given rate, as opposed to any other arbitrary rate. The lack of a duration config is attributed in various places to the fact that it's "based on physics, not time + curve". I don't doubt that this is a helpful explanation for someone who understands the part that I'm not understanding, but for a newcomer like me I'm still left wondering why the animation lasted roughly a second or so, and not, say, 100 milliseconds or 3 hours or any other "duration".

Perhaps this is already documented somewhere that I missed, but could someone maybe explain how to get from "it's based on physics, you don't need a duration" to the point where it makes sense why the animation completes in the time that it does?

Thanks in advance for any help!

**Comment by scottalan** [comment]
@jmar777 

Using the [Render-props Api](https://www.react-spring.io/docs/props/spring) you can add configuration to handle the `duration` and `delay`.

```
<Spring
      from={{ opacity: 0 }}
      to={{ opacity: 1 }}
      config={{ duration: 500, delay: 4000 }}
    >
      {(props) => (
        <div
          id="my-div"
          className="bg-white"
          style={props}
        >
          I will fade in
        </div>
      )}
</Spring>
```

When using the [Hooks Api](https://www.react-spring.io/docs/hooks/use-spring) you can add configuration as well.

```
const props = useSpring({
    opacity: 1,
    from: { opacity: 0 } ,
    config: {
      delay: 500,
      duration: 4000,
    },
  });
  return <animated.div
    className={`bg-white`}
    style={props}
  >
    I will fade in
  </animated.div>
```

Hope that helps!

**Comment by scottalan** [comment]
I've been playing around with the hook and it seems as though it doesn't respect `delay`. Based on what I'm seeing in [renderprops-universal.d.ts](https://github.com/react-spring/react-spring/blob/master/types/renderprops-universal.d.ts#L18) it should, right?

This is an amazing library but I agree with you. As a newcomer myself, it would be nice if the [examples](https://www.react-spring.io/docs/props/spring) were a little more verbose.

If I find a solid answer I'll post back 😉

**Comment by scottalan** [comment]
Found [this post](https://usehooks.com/useSpring/), maybe it will provide some insight. I haven't tested it myself...

**Comment by drcmda** [comment]
> As advertised, no durations are present in the API. The part I'm struggling to understand is how and why the values are manipulated at a given rate, as opposed to any other arbitrary rate. The lack of a duration config is attributed in various places to the fact that it's "based on physics, not time + curve". I don't doubt that this is a helpful explanation for someone who understands the part that I'm not understanding, but for a newcomer like me I'm still left wondering why the animation lasted roughly a second or so, and not, say, 100 milliseconds or 3 hours or any other "duration".

The elements are driven by force and resistance, not time. 

In front of you is a table, there's a glas on it, slide it to the other end, how long will it take? You see already, that question doesn't make sense, it just depends: how long is the table, how much force do you use, how heavy is the glas, is the tables surface smooth or will it give friction, etc.

The point is, forget time, forget everything you thought you know about animation. Just let these springs be, they work in accordance with the natural laws in their environment and everything in it moves in harmony. 

If you feel something should be lighter or heavier, or have bounce, that's something else. You either give it a preset in that case or define your own. But in no case will you ever have to think about it much. Just like when you slide the glas, you just do.

**Comment by nikparo** [comment]
> I'm still left wondering why the animation lasted roughly a second or so, and not, say, 100 milliseconds or 3 hours or any other "duration".

React Spring uses the `config.default ({ mass: 1, tension: 170, friction: 26 })` preset by default. As far as I can tell those values are somewhat arbitrary, but you can tweak them as you want to make your animation feel more responsive, softer, heavier, harsher, etc.

**Comment by aleclarson** [comment]
You can use this: https://chenglou.github.io/react-motion/demos/demo5-spring-parameters-chooser/

The "stiffness" is `tension` in react-spring. The "damping" is `friction`.

Eventually, we'll have a copy of that in the docs.

**Comment by aleclarson** [comment]
Another tool for playing with spring feel: https://springs.pomb.us/
