### ISSUE TITLE
TypeScript: UseTransitionProps does not implement onRest

### ISSUE THREAD

**Issue by TimoP** [react-spring/react-spring#800]
Maybe I miss something but UseTransitionProps Type does not implement onRest. UseTransitionProps extends HooksBaseProps and that extends SpringBaseProps. SpringBaseProps does not implement onRest. Only SpringProps implement also onRest.

**Comment by danieloi** [comment]
Proptype aside, I can confirm that onRest is actually being called with vanilla. 

Also, haven't used typescript to any large degree but I'm thinking it might be some kind of omission in type-definitions

**Comment by danieloi** [comment]
#760 looks like it's resolved this issue
