### ISSUE TITLE
Use react-spring on non-react context

### ISSUE THREAD

**Issue by phaistonian** [react-spring/react-spring#801]
## 🚀 Feature Proposal

Since we use, i.e import, react-spring into our bundles, how about enabling us to use those spring helpers in vanilla (DOM) context too?

## Motivation

See above

## Example

```js
import spring from 'react-spring/DOM';

spring(element, props).then(done);
```

(Please provide an example for how this feature would be used.)

**Comment by drcmda** [comment]
i think it would be easier to just use something like wobble in this case. there's a lot more going on here than just the spring, it keeps a persistent handle, which may update the view at any time, which also gets us interruptible animation. the whole hooks thing, etc.

**Comment by drcmda** [comment]
@aleclarson @phaistonian https://codesandbox.io/s/adoring-feather-onlso

```jsx
import { Globals, Controller } from "@react-spring/web";

function App() {
  const ref = useRef();
  useEffect(() => {
    const ctrl = new Controller();
    ctrl.update({
      color: "hotpink",
      from: { color: "black" },
      onFrame: props =>
        Globals.applyAnimatedValues(ref.current, { style: props })
    });
    ctrl.start();
  }, []);

  return <h1 ref={ref}>Hello CodeSandbox</h1>
}
```

**Comment by aleclarson** [comment]
That won't work once we start injecting `Globals.applyAnimatedValues` into `withAnimated` in a future commit.

**Comment by drcmda** [comment]
is the apply function accessible somewhere in the upcoming commits?

**Comment by aleclarson** [comment]
It could easily be exported by `@react-spring/web`
