### ISSUE TITLE
Setting state from onStart when using useTransition causes infinite render loop

### ISSUE THREAD

**Issue by psachs21** [react-spring/react-spring#802]
## 🐛 Bug Report

It should be possible to track the rest status of any given animation. Usually, i would do this with state but currently, this causes a render infinite loop. I've tried to use a ref instead, but that causes issues if the UI changes its render based on that value, which is exactly when you want to use state instead. This feels like a deps problem.

## To Reproduce

See attached code sandbox. Basically, use setState inside your onStart handler.

Reproduce:
- Try to trigger notifications by clicking anywhere

## Expected behavior

Changing state of the component shouldn't retrigger onStart. 

## Link to repro (highly encouraged)

[sandbox](https://codesandbox.io/s/messagehub-oii8i)

## Environment

- `react-spring` 8.0.27
- `react` v16.8.6

**Comment by psachs21** [comment]
This works fine with renderProps equivalent, fyi.

**Comment by aleclarson** [comment]
Your sandbox works fine with the [latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). Though, you'll need to change the `useTransition` syntax slightly.

```ts
const transition = useTransition(items, {
	key: item => item.key,
	...etc,
})
return transition(({ life, ...style }, item) => (
  // JSX goes here (no need for a "key" prop, it's added automatically)	
))
```

**Comment by psachs21** [comment]
@aleclarson that's good to know. Though after making the modifications you suggested, the animation doesn't actually seem to work (doesn't crash though). Probably related to some other api changes so probably nothing to worry about. Thanks!
