### ISSUE TITLE
v9 UseTransitionProps Type should implement ref property.

### ISSUE THREAD

**Issue by TimoP** [react-spring/react-spring#803]
## 🐛 Bug Report

If i use UseTransitionProps to create an useTransition config incl. ref than TS is complaining that ref is not part of UseTransitionProps. I take a look at the types an ref is realy not part of UseTransitionProps. If i put the config directly in the useTransition() hook than no error is appearing because of the UnknownProps extendtion direct in function declaration.

![image](https://user-images.githubusercontent.com/265404/64345802-44cf1200-cff1-11e9-94da-164e32425244.png)

## To Reproduce

Use UseTransitionProps type and set ref.

## Expected behavior

ref should be part of UseTransitionProps type.

## Link to repro (highly encouraged)

[CodeSandbox demo](https://codesandbox.io/s/mystifying-architecture-9bk5x)

## Environment

- `react-spring` v9.0.0-beta.34
- `react` v16.8.4
- `typescript` v3.3.3

**Comment by TimoP** [comment]
Updated with more information and added the bug report layout.

**Comment by aleclarson** [comment]
This is fixed in #809
