### ISSUE TITLE
Velocity property is non-functional

### ISSUE THREAD

**Issue by Chris-Lorance** [react-spring/react-spring#805]
## 🐛 Bug Report

The velocity parameter currently has no effect on spring motion.

## To Reproduce

Define any value for velocity on a spring animation and compare to an identical spring with velocity 0.

## Expected behavior

Expect motion to begin with the defined initial velocity, rather than beginning from a full rest. 

## Environment

- `react-spring` v9.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by aleclarson** [comment]
Please provide a CodeSandbox or git repo. Thanks! 👍
