### ISSUE TITLE
KeyFrames component missing

### ISSUE THREAD

**Issue by zenios** [react-spring/react-spring#806]
I could not find  Keyframes component in v9 (Beta 34).  Is that intentional?

Thanks

**Comment by drcmda** [comment]
as of v8 keyframes is inbuilt in any spring. the "to" prop can be an array or a function.

```jsx
to: [{x: 1}, {x: 10}, {x: 0}]
```

or

```jsx
to: async set => {
  await set({ x: 1 })
  await set({ x: 10 })
  await set({ x: 0 })
}
```
