### ISSUE TITLE
SVG Filter animation not working in Safari

### ISSUE THREAD

**Issue by skrichten** [react-spring/react-spring#812]
## 🐛 Bug Report

Animating some SVG filter attributes does not work in Safari 12.

## To Reproduce

Create a spring that changes values on an SVG filter, for example the values of feColorMatrix.

## Expected behavior

The values should animate as they do in all the other browsers. 

## Link to repro (highly encouraged)

https://codesandbox.io/s/laughing-sinoussi-oj1gx

## Environment

- `react-spring` v9.0.0-beta.34 and v8.0.27
- `react` v16.8.x

**Comment by aleclarson** [comment]
If it works in other browsers, I don't think it's an issue with react-spring

**Comment by aleclarson** [comment]
[Related question](https://stackoverflow.com/questions/39332798/svg-fecolormatrix-doesnt-work-in-safari) on StackOverflow.

The issue is an unnecessary space at the beginning of a matrix:
```tsx
          <AnimColorMatrix
              type="matrix"
              in="turbulence"
              result="gray"
              values={val.interpolate(c =>
  				// 👇🏻 Right here
                ` 0   0   ${c}  0   0
                  0   0   ${c}  0   0
                  0   0   ${c}  0   0
                  0   0   0     1   0 `)}
            />
```
Remove the space before the first `0` in that string.
