### ISSUE TITLE
How to chain useSprings with other hooks.

### ISSUE THREAD

**Issue by majkelbed** [react-spring/react-spring#814]
Hi guys,
was looking for solution on my own here yet I didnt found one.

How to chain useSprings with other animations with useChain or inside useSprings, when using [get,set] dynamic setter?

Passing ref causing `TypeError: rangeValue.replace is not a function` so I can't use useChain hook

Passing function won't work (error `next is not a function`)
``` 
const func=async (next, cancel) => {
    await next(props)
    await next(props)
  },
...
  setSprings(i=>func())
```
Passing array of objects won't work either. (`TypeError: rangeValue.replace is not a function`)

Using useState variable to manage connection between useSprings and useTransition was causing to flicker every state change.

Finally I had to use double useSprings and manipluate delay for second one, but it don't feel right and I have to do a bit of looping so probably performance could be better.

Would be nice if something like setSprings({props},index) instead of looping all of them if you don't need it.

Code if needed https://github.com/majkelbed/AccordionCards/blob/master/src/pages/index.js

**Comment by aleclarson** [comment]
Please provide a sandbox for your issue. Thanks 👍
