### ISSUE TITLE
Values don't interpolate in my development environnement

### ISSUE THREAD

**Issue by guins** [react-spring/react-spring#815]
Any Idea why, in my project environnement only, react-spring isn't working ? (but no errors in the console) All animated values are staying at their initial `from` state.

I tried to copy and paste just part of my application in code sandbox to isolate the problem and found out that my code is working right away... so it's definitely in my environnement :(
https://codesandbox.io/s/solidify-lib-with-react-spring-tests-md45e

But in my entire application, all AnimatedValue are getting several `undefined` values like this : 
```
done: false
lastPosition: 0
lastTime: undefined
lastVelocity: undefined
payload: undefined
startPosition: 0
startTime: 1568965105041
```
For me, the only difference with the code sandbox is the compiler/bundler (FuseBox). So I already tried to remove the HMR and code splitting to have it all the same big file loaded all at once, but the problem still remain.

Any hint why react spring doesn't seem to work ? (Even thought I have no errors at all)

**Comment by guins** [comment]
Okay, this is a ES6 to ES5 compilation issue :(

Fusebox ES5 default config is for exemple wrongly compiling "for of" loops of Set objects. Indeed, the resulting ES5 "for" loops are being skipped by React Spring "update" function because `controllers.length` test doesn't pass the condition - because this is a Set object and not a regular Array.

I found the issue, but didn't find a way to support ES5 though, so Let me know if you found a workaround...

**Comment by aleclarson** [comment]
Have you tried with v9?  `npm install react-spring@next`
