### ISSUE TITLE
Problems with useTransition and certain CSS properties on components beneath animation

### ISSUE THREAD

**Issue by michaeljblum** [react-spring/react-spring#816]
I am animating a nav overlay with useTransition. Here is a gist of the component: https://gist.github.com/michaeljblum/aded457ce603a2bea6a91605986bcac7.

It works well, unless there is an element with properties like `filter: blur(__px)` or `position: absolute` beneath the overlay that is animating with useTransition.

In this event, the overlay component mounts and begins to fade in (as per my animation instructions), but the elements with, say, `filter: blur()` applied on them (on the component beneath the overlay) persist for the duration of the useTransition animation. They are fully visible during this time (only the elements with the problematic CSS properties though - nothing else). I've tried adjusting z-indexes in various ways but that didn't help anything. Using text-shadow instead of filter:blur() resolves the issue, but I still need to use filter:blur() for some elements. 

Is there a way around this?

**Comment by michaeljblum** [comment]
Just a heads up, I'm getting the same issue when there are images behind the component that is animating upon mount with useTransition. I'd like to make this post's label "bug" rather than "question" at this point, because I'm really not sure what I'm doing wrong (you can find the component that is use useTransition in the gist above).

**Comment by aleclarson** [comment]
Please provide a repro so I have something to test with when I get around to looking at it. 👍

**Comment by michaeljblum** [comment]
Hey, thanks so much - so I threw together this simple/ugly example: https://codesandbox.io/s/restless-frog-dc0e9

Are you seeing the same things I am? And I'm getting this on the latest React-Spring version.

**Comment by aleclarson** [comment]
This bug is unrelated to `react-spring`. You can fix it by adding `position: absolute` and `z-index` to both the `nav` and `.MenuLinks` selectors, or whatever works for you.

**Comment by michaeljblum** [comment]
I don't know, I tried the properties you suggested and am still having difficulties. With an overlay animating with pure CSS transitions, on the other hand, and with the same properties, I'm not having issues.
