### ISSUE TITLE
React-native horribly broken (and seemingly undocumented)

### ISSUE THREAD

**Issue by traviswimer** [react-spring/react-spring#817]
## 🐛 Bug Report

- When using `react-native` elements don't seem to transition between states. It only ever applies the styles in the `from` property.
- Elements aren't always removed after transitioning. Setting a higher duration seems to "fix" this, so it seems like it is somehow dependent on the performance of the device.
- There appears to be no documentation for using `react-spring` with `react-native`. Although I did come across several broken links to documentation that once existed.

## To Reproduce

Using one of the web examples as a base, I created a very simple component. (I couldn't find any `react-native` examples). Running this, you will only see the components displayed with `opacity: 0.3`. (The `from` value`)

I should note that I have been testing this on a somewhat old Android device.

```javascript
import React, { useState } from "react";
import { View, Text, Button } from "react-native";
import { useTransition, animated } from "react-spring";

let AnimatedView = animated(View);

export default function TestAnimation(props) {
	const [toggle, setToggle] = useState(false);
	const transitions = useTransition(toggle, null, {
		from: { position: "absolute", opacity: 0.3 },
		enter: { opacity: 1 },
		leave: { opacity: 0.1 },
	});
	return transitions.map(({ item, key, props }) =>
		item ? (
			<AnimatedView key={key} style={props}>
				<Text>Hello 😄</Text>
				<Button title="Toggle" onPress={() => setToggle(true)} />
			</AnimatedView>
		) : (
			<AnimatedView key={key} style={props}>
				<Text>Gahhh 🤪</Text>
				<Button title="Toggle" onPress={() => setToggle(true)} />
			</AnimatedView>
		)
	);
}

```

## Expected behavior

Animate and add/remove components as it does on the web.

## Link to repro (highly encouraged)

*See example above*

## Environment

- `react-spring` v8.0.27
- `react-native` v0.60.5

**Comment by aleclarson** [comment]
Have you tried with v9? `npm install react-spring@next`
