### ISSUE TITLE
Spring effect stacking order and z-index

### ISSUE THREAD

**Issue by rhulse** [react-spring/react-spring#819]
## 🤓 Question

I believe I know the answer, but wanted to check this is correct behaviour and not a bug. I have a carousel that uses Springs and useGesture. There is also a screensaver in the app that use Transitions to fade in and out periodically.

When the saver component is first in the source order, the text content in the carousel bleeds through, whereas when it is last in the source, the saver covers the content. Z-index does nothing.

It appears the effects stack in source order and ignore any z-index in CSS that is applied. 

Is this expected?

**Comment by aleclarson** [comment]
Hard to say without any code.

**Comment by rhulse** [comment]
Of course, sorry. Quickest way is to see it in context of [my project](https://github.com/rhulse/kiosk-application-framework). Set screensaver:idleTimeout to 5 (seconds), and move the ScreenSaver component in Kiosk.js above the container div.

Or I could try to put together a minimal test case on codepen if that's preferable?

**Comment by aleclarson** [comment]
Yeah, some kind of minimal sandbox is preferred. Thanks :+1:
