### ISSUE TITLE
V9 useSpring set Typescript error symbol iterator

### ISSUE THREAD

**Issue by jwmann** [react-spring/react-spring#822]
I recently upgraded to the latest v9 beta 34 

This line is now throwing a Typescript error:
```
const [{ y : springY }, setSpringY] = useSpring( () => ( { y: 0 } ) );
```

```
const setSpringY: any
Type 'AnimatedValue<Pick<object, never>>' must have a '[Symbol.iterator]()' method that returns an iterator.ts(2488)
```

Everything still works as before though.
Maybe related to #723 ?
#642

**Comment by aleclarson** [comment]
What's your TypeScript version?

**Comment by jwmann** [comment]
I had the same issue as before where my VSCode took actual 20 minutes to get the proper types.
No errors anymore.
