### ISSUE TITLE
feat: add SpringContext component

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring#824]
## 🚀 Feature Proposal

Add a `SpringContext` component that can pause, cancel, or finish any animation within its child components.

```jsx
// Every react-spring animation inside "Home" is affected.
const App = () => (
	<SpringContext pause={true} cancel={true} immediate={true}>
		<Home />
	</SpringContext>
)
```

You can nest `SpringContext` components to override props for a subtree.

## Motivation

Provide an easy way to reduce CPU cycles by pausing animations when they're not visible.

**Comment by aleclarson** [comment]
The `immediate` prop works well with  https://github.com/react-spring/react-spring/issues/811#issuecomment-538539538

**Comment by ShanonJackson** [comment]
Don't feel like this is neccessary; you can already achieve this yourself through providing your own context + listening for that context in component's that useSpring and setting immediate/cancel/paused etc.

If you want it natively (I.E Inbuilt context listeners) then just extend animated.div yourself
