### ISSUE TITLE
UseChain run animations multi time

### ISSUE THREAD

**Issue by GuilhemBarboux** [react-spring/react-spring#826]
Hi, this is the code from the react-spring for useChain :

```
function useChain(refs, timeSteps, timeFrame) {
  if (timeFrame === void 0) {
    timeFrame = 1000;
  }
  const previous = useRef();
  useEffect(() => {
    if (is.equ(refs, previous.current)) refs.forEach((_ref) => {
      let current = _ref.current;
      return current && current.start();
    });else if (timeSteps) {
      refs.forEach((_ref2, index) => {
        let current = _ref2.current;
        if (current) {
          const ctrls = current.controllers;
          if (ctrls.length) {
            const t = timeFrame * timeSteps[index];
            ctrls.forEach(ctrl => {
              ctrl.queue = ctrl.queue.map(e => _extends({}, e, {
                delay: e.delay + t
              }));
              ctrl.start();
            });
          }
        }
      });
    } else refs.reduce((q, _ref3, rI) => {
      let current = _ref3.current;
      return q = q.then(() => current.start());
    }, Promise.resolve());
    previous.current = refs;
  });
}
```

When the array of refs is the same that previous render, useChain run all animation without wait the others "if (is.equ(refs, previous.current)) refs.forEach((_ref) => {...". The result is animation running all in the same time, and cancel chain effect.

Do you know this problem ?

## Environment

- `react-spring` v8.0.27
- `react` v16.10.2

**Comment by aleclarson** [comment]
This is the latest `useChain` implementation: https://github.com/react-spring/react-spring/blob/a097eaf5484686a8d255da78e92664b9c44dbf65/packages/core/src/useChain.js

Can you highlight the lines you're talking about with shift-clicking the line numbers on that page?

**Comment by Soundvessel** [comment]
There is a workaround but I noticed is causes start to be undefined in console message.

https://spectrum.chat/react-spring/general/unable-to-get-usechain-to-work-with-two-springs~90f925a7-8233-4b27-afb0-ca07dea2a235?m=MTU4MjI1Nzg1NTUxNA==
