### ISSUE TITLE
Where is the "panel keyframes" source code?

### ISSUE THREAD

**Issue by tayhr** [react-spring/react-spring#829]
Hello, 
in: 
react-spring.io/docs/props/keyframes
the source of the "panel keyframes" loads a broken link:
https://github.com/react-spring/react-spring-examples/tree/master/demos/renderprops/keyframes

I tried to search this source code everywhere. 
Please, can you provide me this source code?

Thanks
![panel-keyframes](https://user-images.githubusercontent.com/18019271/66573196-a9c5dc80-eb48-11e9-87e1-7d8af9eb582b.png)

**Comment by aleclarson** [comment]
Hmm, not sure why it disappeared from the `master` branch, but you can find it here:
https://github.com/react-spring/react-spring-examples/tree/v9/demos/renderprops/keyframes
