### ISSUE TITLE
TypeError: Cannot set property 'parallax' of undefined

### ISSUE THREAD

**Issue by sungle3737** [react-spring/react-spring#842]
## 🐛 Bug Report
![image](https://user-images.githubusercontent.com/27716524/67634621-ce200800-f901-11e9-9564-ea3f6f5d6b47.png)
While testing react-spring parallax example in my `index.js`
[example url](https://www.react-spring.io/docs/props/parallax)
I copy and paste like that and just ran `gatsby develop` then

![image](https://user-images.githubusercontent.com/27716524/67634626-d6784300-f901-11e9-9a98-3c656bc96ee8.png)
this happens!

Other Render-props api - Spring is working in same condition
[example url](https://www.react-spring.io/docs/props/spring)
but in parallax
`TypeError: Cannot set property 'parallax' of undefined`

## Environment
- `react-spring` v8.0.27
- `react` v16.11.0
- `gatsby-starter-default`

**Comment by aleclarson** [comment]
`this` is undefined in function components

**Comment by JulienHe** [comment]
@sungle3737 Did you find any solutions?? Running the sam issue :(.

**Comment by sungle3737** [comment]
my solution was
```jsx
React.parallax = ref
```

**Comment by aleclarson** [comment]
Don't pollute the React namespace.

Function components are where React hooks are used. You need `React.useRef`.
