### ISSUE TITLE
useSpring/three stale state

### ISSUE THREAD

**Issue by antegulin** [react-spring/react-spring#844]
## 🐛 Bug Report

When `set` from `useSpring` gets called twice in a short time period, the latter state does not apply to the animated object. This causes the object to be stuck in the state provided in the first invocation of `set`.

[![Demo](https://i.gyazo.com/129a388325305aaf759d796e552e5ebf.gif)](https://gyazo.com/129a388325305aaf759d796e552e5ebf)

## To Reproduce

```jsx
    const [spring, set] = useSpring(() => ({
        scale: [1, 1, 1],
        config: { mass: 3, friction: 40, tension: 800 }
    }));

    const bindHover = useHover(({ hovering }) => {
        set({ scale: hovering ? [3, 3, 3] : [1, 1, 1] })
    }, {
        pointerEvents: true
    });

    return <a.mesh position={new Vector3(0,0,0)} {...spring} {...bindHover()} >
        <sphereGeometry attach="geometry" args={[1, 32, 32]} />
        <pointsMaterial attach="material" color={"blue"}/>
    </a.mesh>
};
```

## Expected behavior
I expected the sphere to spring back to initial scale `[1, 1, 1]` as described in
```jsx
 set({ scale: hovering ? [3, 3, 3] : [1, 1, 1] }))
```

## Link to repro (highly encouraged)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-spring` v8.0.27
- `react-use-gesture` v6.0.14
- `three` v0.109.0
- `react` v16.8.6

**Comment by aleclarson** [comment]
Please try with v9: `npm install react-spring@next`

**Comment by antegulin** [comment]
> Please try with v9: `npm install react-spring@next`

It doesn't happen in v9.
Well, that was quick. Thanks 😄!
