### ISSUE TITLE
Animation randomly restarting mid animation during setState calls

### ISSUE THREAD

**Issue by mkralla11** [react-spring/react-spring#848]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

When any kind of state change or render-pass occurs with useSpring (or any of the use[func] modules from react-spring) causes random restarts of the animation.

## To Reproduce

Using a single useSpring, the animation has progressed to any point during it's frames, the given animation randomly restarts to another point in the animation as if it cannot keep track of where it was. For reference, I've spend multiple days debugging this issue and have boiled down the occurrence of the issue to a single, extreme simple codesandbox example. (see below) This happens with a single `to` value, an array `to` value, as well as an async `to` value, with or without delay, and seems to be a distinct timing related issue with when a render pass occurs and what react-spring's underline controller is trying to do. The example below simply calls set[State] every 1000ms, and demonstrates how the *simple* useSpring animation randomly begins restarting mid-animation.

## Expected behavior

Complete the given useSpring animation when irrelevant state changes / render-passes occur.

## Link to repro (highly encouraged)
In the codesandbox, click the 'middle' button, to see what the animation is supposed to look like (setState interval loop is turned off). Click the 'Run 1000ms Ticker` button and watch the animation randomly begin restarting mid animation.
https://codesandbox.io/s/unruffled-bas-nrbmz?fontsize=14

## Environment

Tested on every minor/major version combination from (spent 3 days tracking down the underlying cause of this bug):
- `react-spring` 8.0.1 THROUGH LATEST 9.X.X Beta
- `react` v16.8.0 - v16.8.3

**Comment by aleclarson** [comment]
When the `to` prop is an array, the animation is updated even if the array has the *exact* same "instructions" as the previous render. This is by design, but luckily there's an easy workaround.

I recommend using `const [values, update] = useSpring(() => props)` syntax. It lets you decide when the animation is updated, instead of updating the animation on every render.

**Comment by mkralla11** [comment]
Can you point to where it says this in the docs? I apologize if I missed it.

**Comment by aleclarson** [comment]
3rd example on [this page](https://www.react-spring.io/docs/hooks/use-spring)

**Comment by mkralla11** [comment]
Excellent, is there also this option for useTransition? or should I avoid that function all-together for similar situations but where I want to handle entering and leaving items.

**Comment by AnweshGangula** [comment]
I was facing the same issue, and switching the `useSpring` to [function & deps](https://www.react-spring.dev/docs/components/use-spring#with-a-function--deps) worked for some reason. I don't fully understand why though!!

**Comment by AnweshGangula** [comment]
found a related issue here: #1111
