### ISSUE TITLE
Links to examples' source are broken

### ISSUE THREAD

**Issue by mlsteele** [react-spring/react-spring#853]
## 🐛 Bug Report

On the documentation site, the links to examples' source code 404.
https://www.react-spring.io/docs/props/spring

![image](https://user-images.githubusercontent.com/705646/68495013-5e711d80-021d-11ea-8c88-e088b8392d6a.png)

Some example broken links:
https://github.com/react-spring/react-spring-examples/tree/master/demos/renderprops/nativespring
https://github.com/react-spring/react-spring-examples/tree/master/demos/renderprops/gestures
https://github.com/react-spring/react-spring-examples/tree/master/demos/renderprops/simple-spring

**Comment by aleclarson** [comment]
Should be fixed now. Thanks 👍
