### ISSUE TITLE
useChain takes an array of any length

### ISSUE THREAD

**Issue by ChanceTheHacker** [react-spring/react-spring#855]
## 🚀 Feature Proposal

I think it would be nice if useChain could be made to take any array length rather than only a [0, 1]

## Motivation

It seems counter intuitive to me that it can not.  

## Example

useChain([springRef1, springRef2, springRef3], [0, .25, 1])

I apologize if I have made any mistakes in my proposal here. I have never participated in an opensource project before. I have currently forked react-spring and am looking through your contributing guidelines hoping I can find some way to help this project. Have already joined your patreon, and hope to do more in the future.

**Comment by aleclarson** [comment]
This is already supported. Were you having trouble when you tried it, or did the docs neglect to mention it?

**Comment by ChanceTheHacker** [comment]
I tri d to implement it in a project, and it did not work so I went to the
docs to figure out what I was doing wrong, and I could not find any
information on the docs, so I guess it was a bit of both.

**Comment by ChanceTheHacker** [comment]
Speaking of docs, while I am not the best coder around, I'm fairly good at
teaching and writing. I have been looking for a way to help react spring,
as it has provided me with an immeasurable amount of help. Would you be
adverse to me rewriting and rewording docs? There are some things I've
found confusing, and I was hoping I could help clear them up. Obviously, if
you do not like the changes I would not be offended in the least if you did
not accept them, but I'm really looking for a way to help the project.

**Comment by aleclarson** [comment]
I'll be writing the docs from scratch before v9 is released, but I haven't started on that yet. Since it'll be a few months at least, any help with the current docs would be great.

You can find them here: https://github.com/react-spring/react-spring.io/tree/master/src/pages/md

**Comment by ChanceTheHacker** [comment]
Thanks, I will certainly spend some time looking over it. I deleted my comment before you replied because I did not know that replying to the email would automatically post it here, and my request to help with the docs was meant to be a personal communication lol.
