### ISSUE TITLE
Missing decay prop in typescript definitions

### ISSUE THREAD

**Issue by ootes** [react-spring/react-spring#856]
## 🐛 Bug Report

Typescript gives an error when using **decay** key inside the **useSpring** config

## To Reproduce
I more or less copied the following example https://codesandbox.io/s/zq19y1xr9m?from-embed in Typescript. When using the decay in config it trows an error. 

`Error:(51, 59) TS2322: Type '{ velocity: number[]; decay: boolean; }' is not assignable to type 'SpringConfig | ((key: string) => SpringConfig) | undefined'.
  Object literal may only specify known properties, and 'decay' does not exist in type 'SpringConfig | ((key: string) => SpringConfig)'.`

## Environment

- `react-spring` v8.0.27
- `react-use-gesture` v6.0.1
- `react` v16.10.2
- `typescript` v3.5.3

**Comment by aleclarson** [comment]
This is fixed in v9 beta

```
npm install react-spring@next
```
