### ISSUE TITLE
Typescript error in `useSpring` with chain

### ISSUE THREAD

**Issue by burtek** [react-spring/react-spring#857]
## 🐛 Bug Report

While using [`useSpring` with chain (as per docs)](https://www.react-spring.io/docs/hooks/use-spring#async-chainsscripts), typescript does not recognise `to` being an array and throws error.

Ofc, I'm talking about `useSpring`, but the same may apply to other hooks and/or other APIs - I haven't checked that

## To Reproduce

Create spring with chain (use array in `to` property)

## Expected behavior

Typings should work

## Link to repro (highly encouraged)

https://codesandbox.io/s/strange-snow-svsd8

## Discussion

I guess the problem is because of this:
https://github.com/react-spring/react-spring/blob/66087e18b64d6c6d5fd75f6d84e85ed59714769d/types/web.d.ts#L65-L68
it does not count in possibility of an array.

I guess that I could be fixed by this (I haven't fully tested it though, I only know it fixes this case):

```ts
type InferFrom<T extends object> = T extends { to: Array<infer TTo> }
  ? Partial<TTo>
  : T extends { to: infer TTo }
  ? Partial<TTo>
  : Partial<ForwardedProps<T>>
```

## Environment

- `react-spring` v8.0.27
- `react` v16.11.0
- `typescript` v3.7.2

**Comment by burtek** [comment]
I guess the problem lies here:
https://github.com/react-spring/react-spring/blob/66087e18b64d6c6d5fd75f6d84e85ed59714769d/types/web.d.ts#L65-L68
it does not count in possibility of an array.

I guess that I could be fixed by this (I haven't fully tested it though, I only know it fixes this case):

```ts
type InferFrom<T extends object> = T extends { to: Array<infer TTo> }
  ? Partial<TTo>
  : T extends { to: infer TTo }
  ? Partial<TTo>
  : Partial<ForwardedProps<T>>
```

**Comment by aleclarson** [comment]
v9 fixes this

```ts
npm install react-spring@next
```

**Comment by itayganor** [comment]
@aleclarson 
Is it safe to use the unreleased version in production? and if it isn't, maybe we should fix this for v8 too.
