### ISSUE TITLE
v9.0.0-beta.34: Typescript: `SpringValues` type is not exported

### ISSUE THREAD

**Issue by burtek** [react-spring/react-spring#862]
## 🐛 Bug Report

`SpringValues` type is not exported.

This type is declared in `@react-spring/core`, but is not exported and thus cannot be used as param type for function passed as `<Spring />` child.

```tsx
class A extends Component {
  ...
  render() {
    return <Spring {...params}>this.func</Spring>;
  }

  func(props: any /* SpringValues<{ width: number, height: number }> */) {
    return ...;
  }
}
```

## Expected behavior

`SpringValues` type should be exported.
## Environment

- `react-spring` v9.0.0-beta.34
- `react` v16.11.0

**Comment by burtek** [comment]
Sorry, this should have been reported as feature suggestion rather than bug :/ My bad

**Comment by aleclarson** [comment]
Your example doesn't make it clear why you need `SpringValues`. Can you update it so I can understand your use case?

**Comment by burtek** [comment]
Sorry, I've been on vacation since then.

I want to be able to have a method outside of my render() function. To be able to do that, I need to be able to specify type of this method's arguments.

When providing callback inside `<Spring>` component, argument get typed out of the box:

```tsx
<Spring {...params}>{(data /* no need to specify type here */) => { ... }}</Spring>
```

But when I want to have a callback for `<Spring>` somewhere else (see first post), I need to be able to specify argument's type. According to source files, the correct argument type is `SpringValues<...>`, but it's not exported.

**Comment by aleclarson** [comment]
I just realized `SpringValues` is already exported in the [latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). :)

**Comment by burtek** [comment]
Great! I'll give it a try a little bit later!
