### ISSUE TITLE
Staggering of transitions doesn't look to be working

### ISSUE THREAD

**Issue by andyrichardson** [react-spring/react-spring#869]
## 🐛 Bug Report

When using `useTransition`, trail does not apply to list additions.

## To Reproduce

Create a list and proxy it via useTransition specifying a trail.

```
  const transitionEvents = useTransition(events, e => e.timestamp, {
    config: { duration: 200 },
    from: { transform: `translateY(100%)`, opacity: 0 },
    enter: { transform: `translateY(0%)`, opacity: 1 },
    trail: 200
  });
```

Trigger an addition to the list after initial render (setTimeout, handler, etc)

```
setEvents(e => [newEvent1, newEvent2, ...e]);
```

## Expected behavior

As new items are added to the list, they are staggered in.

```
0ms      [item1]
200ms [item2, item1]
400ms [item3, item2, item1]
```

## Actual behaviour

Any new items added to the list animate in at the same time.

## Link to repro (highly encouraged)

![Kapture 2019-11-22 at 12 11 02](https://user-images.githubusercontent.com/10779424/69424702-32779100-0d21-11ea-8853-0aeba7fca199.gif)

- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by aleclarson** [comment]
Please provide a minimal [CodeSandbox](https://codesandbox.io/s/) or git url that shows the issue. 👍

**Comment by aleclarson** [comment]
Also, please try with v9:

```
npm install react-spring@next
```
