### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Baron-ha** [react-spring/react-spring#870]
## 🐛 Bug Report

I try hard used to useSprings like in demo : https://codesandbox.io/embed/n9vo1my91p
but not could.
I use useSprings in nextjs v9.1.3
Sorry for my bad English skills.
this is my issue: 
<img src="https://uphinh.org/images/2019/11/26/Screen-Shot-2019-11-26-at-11.41.48.png" alt="Screen-Shot-2019-11-26-at-11.41.48.png" border="0" />
it's working in reactjs
## Environment

- `react-spring` v8.0.19
- `react` v16.12.0
- `nextjs` v9.1.3

###my code
https://github.com/Baron-ha/bug-react-spring/blob/master/my-code

**Comment by aleclarson** [comment]
Please create a repro that demonstrates the error.

**Comment by aleclarson** [comment]
1. The `window` global doesn't exist in NextJS environments.
2. The props callback passed to `useSprings` is called during render.

### Workaround

```ts
const [style, animate] = useSprings(i => ({ x: 0 }))
React.useEffect(() => {
  const width = window.innerWidth
  animate(i => ({ x: i * width }))
}, [])
```

**Comment by Baron-ha** [comment]
Thank you. but I still have an error regarding your code

**Comment by aleclarson** [comment]
Fixed. It was missing the `pages` argument.
