### ISSUE TITLE
Ref callback on animated component is called twice

### ISSUE THREAD

**Issue by yachaka** [react-spring/react-spring#873]
## 🐛 Bug Report

The `ref` callback prop on an animated component is called twice with the same DOM node.
The lines that seem to be causing the bug are those ones:
https://github.com/react-spring/react-spring/blob/f1c601ab3375487f837bd2edbfc31ccbc2ef0e49/src/animated/createAnimatedComponent.tsx#L57-L59
And also those lines should probably be memoized:
https://github.com/react-spring/react-spring/blob/f1c601ab3375487f837bd2edbfc31ccbc2ef0e49/src/animated/createAnimatedComponent.tsx#L70-L72

## To Reproduce

* Create an animated component
* Pass a ref callback to it, logging something
* Notice 2 console logs, whenever the component mounts

## Expected behavior

* Only one console log.

## Link to repro (highly encouraged)

https://codesandbox.io/s/sweet-breeze-smuqd

## Environment

- `react-spring` v8.0.27
- `react` v16.8.6

**Comment by aleclarson** [comment]
Already fixed in v9

```
npm install react-spring@next
```
