### ISSUE TITLE
useTransition when leave with height to zero

### ISSUE THREAD

**Issue by tdetugny** [react-spring/react-spring#880]
## 🐛 Bug Report

with useTransition, item that disappears persists despite a height at 0.

## To Reproduce
I think when we set the item with height equal to zero, on the leave event, there is an issue. The item doesn't disapear. it is still here. 
(I set height to 0 to avoid jump effect when the item closed disapear.)

go to https://codesandbox.io/s/recursing-gagarin-runmq
open your console.
wait until two notifications are displayed
close both notifications by first closing the highest one (item 2 => item1)
you see in the console the same id click twice (`{key: 2}` instead of `{key: 2}{key:1}`)
and of course the item 1 doesn't disappear

## Link to repro 
https://codesandbox.io/s/recursing-gagarin-runmq
## Environment

- `react-spring` v8.0.27
- `react` v16.8.1

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next
```

**Comment by tdetugny** [comment]
It's a css problem. overflow: hidden solve the problem.
