### ISSUE TITLE
useTransition `leave` doesn't fire when something toggles its target value

### ISSUE THREAD

**Issue by alanbuchanan** [react-spring/react-spring#881]
## 🐛 Bug Report

`useTransition` spring is using a stateful boolean to toggle. When that boolean gets set to false by another function, the `leave` animation doesn't fire and the element leaves from the DOM.

## To Reproduce

see Codesandbox example. Hit the `See matches` button. Then type something into the input. The `onChange` of the input toggles the boolean that the `useTransition` is tracking. Notice that the list of people animates in but not out.

## Expected behavior

The `leave` animation should fire when the function runs that toggles the boolean that the `useTransition` targets - fired by the input's `onChange`.

## Link to repro (highly encouraged)

https://codesandbox.io/s/search-results-count-osgii

## Environment

- `react-spring` v8.0.27
- `react` v16.12.0

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next
```

**Comment by alanbuchanan** [comment]
I've updated the codesandbox example to use v9 beta.34 (next) and the same issue occurs.

**Comment by aleclarson** [comment]
Here's your sandbox using the latest [canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404).
https://codesandbox.io/s/search-results-count-ksvl8

But the problem was you wrapped your `matchTransitions` call with `{showMatches && (...)}`.

**Comment by alanbuchanan** [comment]
@aleclarson I completely missed that, thanks for pointing it out 🙏
