### ISSUE TITLE
[v9] The immediate prop can't stop animation where it's at

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring#884]
## 🐛 Bug Report

@dbismut is using the `immediate` prop to stop an animation at its current value.

## To Reproduce

1. Click & drag the pink square away from its starting point.
2. Release it.
3. Click & hold it (without moving your mouse) before it stops animating.
4. Notice how it doesn't stop animating.

## Expected behavior

The animation should stop where it's at on step 3.

## Link to repro (highly encouraged)

https://codesandbox.io/s/exciting-poincare-jfmce

## Environment

- `react-spring` v9.0.0-canary.808.12.11b2708
- `react` v16.9.0

**Comment by aleclarson** [comment]
Fixed in `9.0.0-canary.808.13.719834d` (#808)

**Comment by dbismut** [comment]
That was fast!!
