### ISSUE TITLE
Where's "hold" or "toggle" in the render-props components?

### ISSUE THREAD

**Issue by xe4me** [react-spring/react-spring#891]
## 🤓 Question

Hi 
First of all, your library is just amazing, thank you.
I've been trying to hold a `Spring` animation and trigger it manually, but I can't find anything on the docs.

There's a lot of examples that use "hold" or "toggle" ( in your own repo), but it seems like it's been removed ? 

How do I hold the animation and trigger it by clicking on a button?

```
         <Spring
              hold={startAnimation} /// =>>>>> How ? 
              from={{opacity: 0}}
              to={{opacity: 1}}>
              {props => <div style={{...props}} >
               some text
              </div>}
            </Spring>

```

Appreciate it in advance

**Comment by aleclarson** [comment]
You can do this:
```tsx
<Spring opacity={startAnimation ? 1 : 0}>{props => {...}}</Spring>
```
And in v9 (`react-spring@next`) you can use the `cancel` prop:
```tsx
<Spring cancel={!startAnimation} to={{ opacity: 1 }} from={{ opacity: 0 }}>{props => {...}}</Spring>
```

**Comment by xe4me** [comment]
@aleclarson  thank you, it would be nice if this is added to the docs, I think in most use cases you want to be able to cancel the animation easily.
