### ISSUE TITLE
Missing typescript definitions for react-spring/three

### ISSUE THREAD

**Issue by evilfer** [react-spring/react-spring#892]
`three.d.ts` and `three.cjs.d.ts` seem to be missing from the distributed package. Should they be included for Typescript projects using `import from "react-spring/three"`?

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next
```

**Comment by evilfer** [comment]
Thank you that worked!

**Comment by lennerd** [comment]
I'm not able to make it work without some type casting hacks (and this might be not possible at all so …). Every SpringValue I pass into the animated components needs to be casted to `any` and then to the respecting `react-three-fiber` type. Am I missing something?

See scale and color:

```
<animated.mesh
  {...props}
  ref={mesh}
  scale={(scale as any) as Vector3}
  onClick={() => setActive(!active)}
  onPointerOver={() => setHover(true)}
  onPointerOut={() => setHover(false)}
>
  <boxBufferGeometry args={[1, 1, 1]} />
  <animated.meshStandardMaterial color={(color as any) as string} />
</animated.mesh>
```

**Comment by aleclarson** [comment]
@lennerd Animating `Vector3` types is not supported yet. Can you open an issue requesting it to be implemented? Thanks
