### ISSUE TITLE
`setSprings` sets opacity wrongly

### ISSUE THREAD

**Issue by ChristopherMillon** [react-spring/react-spring#893]
## 🐛 Bug Report

`setSprings` sets the opacity of an element to `1` when it shouldn't (as its been asked to set it to `0`)

## To Reproduce

Use `setSprings` and set only one item to have an opacity of `1`. (In my example it's a carousel and the issue happens when I increment an index.)

## Expected behavior

`setSprings` should apply the proper opacity each item has been assigned.

## Link to repro (highly encouraged)

https://codesandbox.io/s/tender-hypatia-6wpqp

## Environment
- "react": "16.8.6",
- "react-dom": "16.8.6",
- "react-scripts": "3.0.0",
- "react-spring": "^9.0.0-beta.34",
- "react-use-gesture": "^7.0.0-beta.6"

**Comment by ChristopherMillon** [comment]
Weirdly enough, it doesn't happen in codesandbox.io

**Comment by aleclarson** [comment]
Please try with [the latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). 👍

**Comment by ChristopherMillon** [comment]
That fixed it, thanks a lot 👍
