### ISSUE TITLE
How to transition pages in Gatsby

### ISSUE THREAD

**Issue by JakeElder** [react-spring/react-spring#894]
I'm trying to use React Spring to transition pages in Gatsby, similar to this - http://joshdcuneo.com/gatsby-animate-page-transitions/

Here is a Code Sandbox of my implementation attempt - https://codesandbox.io/s/great-sky-3g2lo?fontsize=14&hidenavigation=1&theme=dark

It uses Gatsby's `wrapPageElement` API to add the transition in `gatsby-browser.js`

```javascript
import React from 'react'
import { animated, useTransition } from 'react-spring'

const SimpleSpring = ({ children, props }) => {
  const transitions = useTransition(props.path, null, {
    from: { opacity: 0 },
    enter: { opacity: 1 },
    leave: { opacity: 0 },
    config: { duration: 3000 }
  })

  return (
    <div style={{ display: 'flex', justifyContent: 'center' }}>
      {transitions.map(({ item, key, props }) => (
        <animated.div key={key} style={props}>
          {children}
        </animated.div>
      ))}
    </div>
  )
}

export const wrapPageElement = ({ element, props }) => {
  return <SimpleSpring props={props}>{element}</SimpleSpring>
}

```

Currently, when a page transition is triggered, React Spring is animating the origin page out and the target page in. That is to say that during the transition period, there are two pages that are animating as specified in the hook. However, the source page instantly updates to have the DOM structure of the target page. So, there are two identical pages, one transitioning out, one transitioning in.

What am I doing wrong? I've tried all sorts of things with useRef and React.cloneElement but I can't get the origin page to remain as it should

**Notes**

* I've used a long duration for the animation rather than a spring to be able to better see what's happening
* Same with layout. Once the DOM is reflecting as it should, these pages will be `position: absolute` during transition so they overlap. I currently have them side by side to debug

**Comment by nickmcmillan** [comment]
I struggled with this for a while and faced the same issues you're describing. I ended up finding a workable solution, though there's probably scope for improvement;

https://github.com/nickmcmillan/gatsby-use-react-spring-route-transitions

**Comment by DRD161** [comment]
I had issues getting the hooks to work as well. I went the render props route and everything seems to work fine now. Code below for examples. Hope you figure this out!

```
import React from "react"
import { Transition } from "react-spring/renderprops"
import DesktopNav from "../components/Nav"
import SideNav from "../components/SideNav"

import { useStaticQuery, graphql } from "gatsby"

import "../styles/styles.scss"

const Layout = ({ children }) => {
  const data = useStaticQuery(graphql`
    query SiteTitleQuery {
      site {
        siteMetadata {
          title
        }
      }
    }
  `)

  return (
    <div>
      <SideNav siteTitle={data.site.siteMetadata.title} />
      <DesktopNav siteTitle={data.site.siteMetadata.title} />
      <Transition
        config={{ duration: 500, delay: 200 }}
        from={{ opacity: 0 }}
        enter={{ opacity: 1 }}
        leave={{ opacity: 0 }}
      >
        {() => style => <main style={style}>{children}</main>}
      </Transition>
    </div>
  )
}

export default Layout
```

**Comment by grinkus** [comment]
A simple sketch to work with hooks. Wrapped in a couple of HOCs for clarity

```
import React from "react"
import PropTypes from "prop-types"
import { useStaticQuery, graphql } from "gatsby"
import { animated, useTransition } from "react-spring"
import { Location } from "@reach/router"

import Header from "./header"
import "./layout.css"

const withData = (WrappedComponent) => (props) => {
  const data = useStaticQuery(graphql`
    query SiteTitleQuery {
      site {
        siteMetadata {
          title
        }
      }
    }
  `)

  return <WrappedComponent data={data} {...props} />
}

const withLocation = (WrappedComponent) => (props) => (
  <Location>
    {({ location }) => <WrappedComponent location={location} {...props} />}
  </Location>
)

const Layout = withData(
  withLocation(({ children, data, location }) => {
    const transitions = useTransition(location.pathname, null, {
      from: { opacity: 0, transform: "scale(0.5) translateY(-50%)" },
      enter: { opacity: 1, transform: "scale(1) translateY(0)" },
      leave: { opacity: 0, transform: "scale(0.5) translateY(50%)" },
    })

    return (
      <>
        <Header siteTitle={data.site.siteMetadata.title} />
        <div
          style={{
            margin: `0 auto`,
            maxWidth: 960,
            padding: `0 1.0875rem 1.45rem`,
          }}
        >
          <main>
            {transitions.map(
              ({ item, key, props }) =>
                item && (
                  <animated.div key={key} style={props}>
                    {children}
                  </animated.div>
                )
            )}
          </main>
          <footer>
            © {new Date().getFullYear()}, Built with
            {` `}
            <a href="https://www.gatsbyjs.org">Gatsby</a>
          </footer>
        </div>
      </>
    )
  })
)

Layout.propTypes = {
  children: PropTypes.node.isRequired,
}

export default Layout
```

**Comment by tompiler** [comment]
Has anyone got this to work with anything besides opacity? tearing my hair out over this, have been struggling for about a whole week now.

**Comment by DRD161** [comment]
@tompiler I’ve managed to get it working with left and right positioning to create a slide animation. If you want to do some sort of overlay transition when exiting the page I’d imagine you could create an overlay div and have the opacity set to 0 and have it animate into view when changing pages 🤔

**Comment by tompiler** [comment]
@DRD161 Thanks for the suggestion - I'm basically trying to wrangle this with gatsby-plugin-transition-link library, and the state prop that is passed to the TransitionLink variable, but it just doesn't work properly, passes through nulls when it should be carrying state and various other issues. The documentation of that plugin is about as lacking as it is for react-spring. Not complaining, but I'd happily foot up cash for better docs or help. Its a sad situation when I spend this much time achieving nothing. Imagine a lot of people are in the same situation.

**Comment by JakeElder** [comment]
Hi guys

The answer found on Spectrum works well for me - https://spectrum.chat/react-spring/general/transitioning-pages-in-gatsby~17877b6f-56f5-40e7-ae3c-188dba64b3ca

Solution on Code Sandbox: https://s1rg4.sse.codesandbox.io/

**Comment by DRD161** [comment]
@tompiler Yeah I had a few issues myself trying to get that to work. I decided to use the render props react-spring provides. I also spoke with @aleclarson who told me that he is hoping to improve the docs in the next release so that should help with some of the confusion.

**Comment by tompiler** [comment]
@JakeElder Thanks for posting this - I'll take a look!

@DRD161 thanks again - I've finally cracked it I think, going to be writing a blog post once its all finished and will use that to try and help out with the docs.

**Comment by aleclarson** [comment]
Anyone that wants to write a guide for this, let me know. I will repost it on the official website (once v9 is released), with a link to your personal blog. 👍

**Comment by smashercosmo** [comment]
It's pretty obvious how to implement simple page transitions with react-spring. But I'm wondering, if something like this is possible with react-spring (even in this example back animations don't work smooth enough) https://codesandbox.io/s/github/smashercosmo/framer-motion-test
