### ISSUE TITLE
Incorrect Typings for useTransitions

### ISSUE THREAD

**Issue by itsrobbie** [react-spring/react-spring#896]
## 🐛 Bug Report

Hi team, 

I'm using the 9.0.0 beta ("react-spring": "^9.0.0-beta.34") version of react-spring, and there seems to be a Typing mismatch between the [react-spring:use-transition docs](https://www.react-spring.io/docs/hooks/use-transition) and the TS definition.

The docs say the 3rd argument should be something like
`{
	from: { transform: 'translate3d(0,-40px,0)' },
	enter: { transform: 'translate3d(0,0px,0)' },
	leave: { transform: 'translate3d(0,-40px,0)' },
}`

However the Typings say it should be of type `any[]`:
`declare function useTransition<Item, From, Props extends object>(data: OneOrMore<Item>, props: Props & PhaseProps<Item, From> & UseTransitionProps<Item>, deps?: any[]): TransitionFn<Item, PickAnimated<Props>>;`
![image](https://user-images.githubusercontent.com/5316572/72018063-d74b2f00-32cb-11ea-8b9e-a012435ce7eb.png)

## To Reproduce

Here is a small code snipit to reproduce (it's pulled straight from the above docs page):
`import React, { useState } from 'react';
import { animated, useTransition } from 'react-spring';

const NumberFader: React.FC = () => {
	const [items] = useState([1, 2, 3, 4]);
	const transitions = useTransition(items, (item) => item.key, {
		from: { transform: 'translate3d(0,-40px,0)' },
		enter: { transform: 'translate3d(0,0px,0)' },
		leave: { transform: 'translate3d(0,-40px,0)' },
	});
	return transitions.map(({ item, props, key }) => (
		<animated.div key={key} style={props}>
			{item.text}
		</animated.div>
	));
};

export default NumberFader;`

## Expected behavior

I would expect to be able to pass the exact same params as stated in the docs (to my understanding, this shouldn't have changed in v9?).

## Link to repro (highly encouraged)

https://codesandbox.io/s/summer-cloud-8h24u

## Environment

-`"typescript": "3.6.3"`
-`"react": "16.11.0"`
-`react-spring": "^9.0.0-beta.34"`

**Comment by aleclarson** [comment]
Don't use caret ranges for beta versions, because that ends up using a canary version where `useTransition` has a slightly different API.

```
"react-spring": "9.0.0-beta.34",
```
