### ISSUE TITLE
How do I execute a function when the animation ends with useTransition?

### ISSUE THREAD

**Issue by Sakaki-Ya** [react-spring/react-spring#898]
## 🤓 Question

Press the button to start the animation, and when the animation ends, unmount the component.

[demo](https://codesandbox.io/s/bold-haze-d6qzp?fontsize=14&hidenavigation=1&theme=dark)

The demo uses the onRest property to execute the function after the animation ends.
```javascript
const [hold, setHold] = useState(false);
const transitions = useTransition(hold, null, {
    config: config.molasses,
    from: { opacity: 0, transform: "translateY(100vh)" },
    enter: { opacity: 1, transform: "translateY(0)" },
    leave: { opacity: 0, transform: "translateY(100vh)" },
    onRest: () => {
      if (hold) setToggle(false);
    }
  });
```
`setHold (true)` is executed in `onMouseDown` and `setHold (false)` is executed in `onMouseUp`.
When `setToggle (false)` is executed, unmount the component.

However, repeated clicking without holding down the button can unmount the component before the animation ends.

Is there a way to unmount only when the animation has finished?
Or is there anything missing from the demo code?

**Comment by aleclarson** [comment]
Using the latest [v9 canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404), I've got it working:
https://codesandbox.io/s/react-spring-issue-898-5kljn

All it took was updating the `useTransition` calls to the new API. More info [here](https://github.com/react-spring/react-spring/pull/809).

> PS: You can [become my patron](https://patreon.com/aleclarson) to support my work.

**Comment by Sakaki-Ya** [comment]
Thank you very much.
Sorry for taking your time for a trivial question.
