### ISSUE TITLE
Feature request: React pixi renderer

### ISSUE THREAD

**Issue by EloB** [react-spring/react-spring#901]
## 🚀 Feature Proposal

First of all thanks for this awesome library. My main animation library!

I been using https://github.com/inlet/react-pixi for awhile. It's pretty cool implementation of react for Pixi.js (A webl/canvas library to paint 2d graphics). It would be really nice if `react-spring` had `native` support for this library.

I'm not so familiar how to extend this functionality for `react-spring`. If `react-spring` also took care of the `tint` property that is a hex value as a `Number` representing a rgb color would be insane!

## Example
```js
import React from 'react';
import { Application, Texture } from 'pixi.js';
import { Sprite, render } from '@inlet/react-pixi';
import { animated, useSpring } from 'react-spring';

const app = new Application();

const AnimatedSprite = animated(Sprite);

const Something = ({ value }) => {
  const props = useSpring(value
    ? { x: 0, tint: 0xffffff }
    : { x: 100, tint: 0xff0000 }
  );
  return (
    <AnimatedSprite
      texture={Texture.WHITE}
      {...props}
     />
  );
};

let value = true;
setInterval(() => render(
  <Something value={(value = !value)} />,
  app.stage,
), 2000);

document.body.appendChild(app.view);
```

**Comment by drcmda** [comment]
i've made it once, for react-pixi-fiber, is there a difference to react-pixi?

https://github.com/michalochman/react-pixi-fiber/issues/78

https://codesandbox.io/embed/0qkll4y5nw (click the thing)

**Comment by drcmda** [comment]
you can check out how targets are made here (v9 api): https://github.com/react-spring/react-spring/tree/v9/targets

konva is probably the easiest to study: https://github.com/react-spring/react-spring/blob/v9/targets/konva/src/index.ts

basically, define native elements, if any, take any of the interpolators you want, or none, color names (hotpink, etc), and most importantly, the applyAnimatedValues function. gives you the instance and the props, find a way to attach props to instance -> it's native.

```jsx
Globals.assign({
  defaultElement: 'Group',
  createStringInterpolator,
  colorNames,
  applyAnimatedValues(instance, props) {
    if (!instance.nodeType) return false
    instance._applyProps(instance, props)
  },
})
```

**Comment by drcmda** [comment]
as for tint, i think that's also possible, via transforms? @aleclarson

**Comment by EloB** [comment]
@drcmda Thanks for info! I think the one I talk about is bigger in stars and is really good. The founder is also really active. :)

**Comment by aleclarson** [comment]
> as for tint, i think that's also possible, via transforms?

For `tint`, you could animate an `rgb(0, 0, 0)` string and then, inside the `applyAnimatedValues` function, use [`rgb-hex`]() to do the following:

```js
import hex from 'rgb-hex'

if (typeof props.tint == 'string') {
  props.tint = Number('0x' + hex(props.tint))
}
```

**Comment by EloB** [comment]
@aleclarson When you animate rgb you can't just do animate a -> b. You need to split each color and animate each seperate. Like: r1 to r2, g1 to g2, b1 to b2.

**Comment by EloB** [comment]
@drcmda Did you solve how to use the `Ticker` instead of `requestAnimationFrame` on `injectFrame` and use the `injectNow` from `Ticker.deltaTime`?

**Comment by aleclarson** [comment]
> @aleclarson When you animate rgb you can't just do animate a -> b. You need to split each color and animate each seperate. Like: r1 to r2, g1 to g2, b1 to b2.

Yeah, but react-spring handles that for you.

**Comment by drcmda** [comment]
@EloB why would you use a Ticker?

**Comment by EloB** [comment]
@drcmda I would like to use the same ticker for everything. If I for instance use a PIXI plugin or imperative component I would like them to be in sync and also if I stop the Ticker I want everything to stop.

**Comment by EloB** [comment]
@aleclarson Yeah I see what you mean now.

I'm working on really slow devices. Smart TVs to be precisely. They can somtime be like 100x slower than a laptop. I wonder what would be the fastest implementation to use arrays or strings? Like `[255, 255, 255]` or `#ffffff`. To use `Number('0x' + rgb)` or `sumOfArray(rgb)`...

**Comment by drcmda** [comment]
you should be able to drop your ticker in there, all you need is a subscribe and unsub. dont know about the delta, but raf will insert one, so the ticker could, too.

**Comment by EloB** [comment]
@drcmda Did you solve it? I've tried so many things now. The closest I get is that it works except for initial values...

**Comment by EloB** [comment]
It might get solved by this PR (https://github.com/inlet/react-pixi/pull/186) or at least you can solve it by modifying `DisplayObject.prototype._reactSetValue`.

**Comment by isBatak** [comment]
@EloB do you have codesanbox or some example of react-spring target for inlet/react-pixi. Have you managed to use `Ticker` and how? Thx!

**Comment by EloB** [comment]
@isBatak I never used the Ticker if you found a solution I'm happy to see it :) Sorry for late reply.
