### ISSUE TITLE
useTransition causes rerender loop when array has fewer items

### ISSUE THREAD

**Issue by BertCh** [react-spring/react-spring#905]
## 🐛 Bug Report

Each re-render useTransition is passed an array from state. This works fine when adding objects, but when objects are removed from the array it triggers a rerender loop.
possibly related: #636

## To Reproduce

press the buttons in the sandbox

## Expected behavior

The animation seems to get run properly, but the rerender loop is unexpected.

## Link to repro (highly encouraged)
bug with useState hook: https://codesandbox.io/s/usetransition-bug-state-v49uq

bug with useReducer hook (slightly more complex): https://codesandbox.io/s/usetransition-bug-25xbr

## Environment

- `react-spring` v8.x.x or 9.x beta
- `react` v16.8

**Comment by aleclarson** [comment]
Please try with the [latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404).

Note: You'll need to update your `useTransition` calls. See #809.

**Comment by BertCh** [comment]
woo it works!
Thanks for responding so quickly & for maintaining a good library 👍

**Comment by arackaf** [comment]
The new useTransition api looks amazing - really looking forward to react-spring 9. 

I found this issue after some maddening debugging, trying to figure out why my expired items were not unmounted. Do you think a quick note in your docs warning of this might be useful?

Also, no pressure of course, but can I ask when you hope to have the current canary released? Very eager to get my hands on it. Thanks for all the hard work - truly appreciated
