### ISSUE TITLE
Canary 808.14 - importing animated from both /three and /web breaks

### ISSUE THREAD

**Issue by dbismut** [react-spring/react-spring#907]
## 🐛 Bug Report

For some reason, importing `animated` from `react-spring/web` and `react-spring/three` in the same project seems to break the `animated` component.

## Link to repro

The following sandbox should make the content move when scrolling, which doesn't happen when line 3 of the sandbox is uncommented.

```jsx
import { animated } from 'react-spring/three'
```

When looking at the style of the `main` element in the inspector it shows like the style property is reset to `""` as soon as the user starts scrolling (ie modifying the spring).

Commenting / uncommenting line 3 activates / removes the bug.

https://codesandbox.io/s/polished-violet-0yzsm

## Environment

- `react-spring` v9 Canary 808.17
- `react` v16.12.x

**Comment by IngoValente** [comment]
Same problem here, title should maybe be updated to reflect that it's still broken in 808.17?

**Comment by beeglebug** [comment]
Also happens in `9.0.0-beta.34`, can't animate dom and three in the same project, whichever is imported first is the only one which works

**Comment by aleclarson** [comment]
Fixed by #979

**Comment by aleclarson** [comment]
Now available in v9.0.0-rc.2 #985

**Comment by dbismut** [comment]
Indeed fixed!
