### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Batatos** [react-spring/react-spring#914]
## 🤓 Question

Hi guys,
I new to spring library, your efforts are much appreciated :)

I'm receiving error mentioned in the title, while trying to use the following piece of code:

import React from 'react'
import ReactDOM from 'react-dom'
import { useSpring, animated } from 'react-spring/renderprops-universal'
import '../App.css'

const calc = (x, y) => [-(y - window.innerHeight / 2) / 20, (x - window.innerWidth / 2) / 20, 1.1]
const trans = (x, y, s) => `perspective(600px) rotateX(${x}deg) rotateY(${y}deg) scale(${s})`

export default function Springcard() {
  const [props, set] = useSpring(() => ({ xys: [0, 0, 1], config: { mass: 5, tension: 350, friction: 40 } }))
  return (
    <animated.div
      class="card"
      onMouseMove={({ clientX: x, clientY: y }) => set({ xys: calc(x, y) })}
      onMouseLeave={() => set({ xys: [0, 0, 1] })}
      style={{ transform: props.xys.interpolate(trans) }}
    />
  )
}

it is the exact code that is provided in the sandbox tutorials:
https://codesandbox.io/embed/rj998k4vmm

All solutions for this error suggest to upgrade react to certain version, however i am on the latest version of react.
can you assist please, what is causing the issue?

my package.json:

{
  "name": "portfolio",
  "version": "0.1.0",
  "private": true,
  "homepage": "https://batatos.github.io/portfolio",
  "dependencies": {
    "@material-ui/core": "^4.8.3",
    "@material-ui/icons": "^4.5.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.2.1",
    "bootstrap": "^4.4.1",
    "particles-bg": "^2.4.7",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.12.0",
    "react-headroom": "^3.0.0",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-router-native": "^5.1.2",
    "react-scripts": "3.3.0",
    "react-scroll": "^1.7.16",
    "react-spring": "^8.0.27",
    "react-stonecutter": "^0.3.10",
    "reactstrap": "^8.4.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "gh-pages": "^2.2.0",
    "react-social-icons": "^4.1.0"
  }
}

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next
```

**Comment by Batatos** [comment]
What does that mean?
What is the step after installation?

**Comment by aleclarson** [comment]
No other steps, or I would have said so. :)

Let me know if the same error still occurs.

**Comment by aleclarson** [comment]
Did you search the issues before creating this? 

https://github.com/react-spring/react-spring/issues/833 has a similar title.

**Comment by Batatos** [comment]
I did the installation nothing changed :(

I took a look on the mentioned issue, the suggestion is to downgrade to certain version (at least from my standing point)
i am on version 16.12.0

what might cause this while im on the latest version?
is it easier for you if i upload it to a repository?

**Comment by aleclarson** [comment]
First, try deleting your lockfile (eg: `yarn.lock`) and `node_modules`. Then reinstall your dependencies.

If that doesn't work, a repository would help me debug it, but I won't have time to look at it this week.

**Comment by Batatos** [comment]
Now it works on v9, on canary it didn't

thanks for the quick response :)
