### ISSUE TITLE
Crashing with `useTrail` on SVG circles

### ISSUE THREAD

**Issue by joshwcomeau** [react-spring/react-spring#916]
## 🐛 Bug Report

When working on an SVG animation, I used `useTrail` to chain 6 moving circles together. It works most of the time, but occasionally crashes with the following error:

<img width="624" alt="Screen Shot 2020-01-28 at 8 33 23 AM" src="https://user-images.githubusercontent.com/6692932/73274143-0d851b80-41b3-11ea-93e0-72727bd3eb3c.png">

I spoke with Paul and he had a bit more context:

> it arrives at scale(NaN) before it happens for some reason

He also found a fix, by using `interpolate`: https://codesandbox.io/s/nervous-ramanujan-e0240

This may already be fixed in v9, just sharing for context / in case it's helpful :) my usecase is solved with interpolate, so there's zero urgency here.

Thanks!

## To Reproduce

Click the button a few times, interruptingly.

## Link to repro (highly encouraged)

https://codesandbox.io/s/eloquent-montalcini-c8y4r

## Environment

- `react-spring` v8.0.27
- `react` v16.12

**Comment by aleclarson** [comment]
Fixed in `9.0.0-beta.34`
