### ISSUE TITLE
useSprings performance issues with large dataset

### ISSUE THREAD

**Issue by andrewskrebets** [react-spring/react-spring#917]
## 🤓 Question

First, I want to thank you for this great library.

Maybe it is not related to `react-spring` but when i started to play with your examples, to be more precise, with an example of a gallery [ViewPager](https://codesandbox.io/s/viewpager-k932v) it was noticeable when we have a lot of images then there are perfomance issues.

If it's not difficult for you, can you tell how to avoid them, maybe some elements may not be rendered somehow, in our case three is enough (current, previous, next).

The code is here:
[Codesandbox](https://codesandbox.io/s/viewpager-k932v)

Any help you could give would be greatly appreciated.

**Comment by aleclarson** [comment]
This isn't react-spring's fault. You'll need a lazy-loading version of the pager, which we don't have pre-made currently.

You can request such an example over here:
https://github.com/react-spring/react-spring-examples
