### ISSUE TITLE
Native prop causes animation visually to fail, but the animated items are delayed from entry/removal as if animations were working

### ISSUE THREAD

**Issue by Slapbox** [react-spring/react-spring#919]
## 🐛 Bug Report

Animations that work fine fail if passed `native`

## To Reproduce

Add `native` to an otherwise working `<Transition />` - [Repro](https://codesandbox.io/s/jovial-darkness-cz1go)

## Expected behavior

`native` prop improves performance without causing animations to fail

## Link to repro (highly encouraged)

https://codesandbox.io/s/jovial-darkness-cz1go

## Environment

- `react-spring@8.0.28`
- `react@16.12.0`

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next
```

You won't need the `native` prop. It's the default behavior now.

**Comment by Slapbox** [comment]
Seems to resolve the issue. Thank you!

**Comment by Slapbox** [comment]
@aleclarson - Upgrading to v9 is interfering with setting the background color of list items within `<Transition />` - Do you have any ideas what might cause this? Some change in memoization or something else maybe?

**Comment by aleclarson** [comment]
Please try with [the latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). 👍

You'll need a slight change to your usage of the `Transition` component. See here: #809

If you can't figure it out, please provide a sandbox or git url.

**Comment by Slapbox** [comment]
Thanks @aleclarson 

The latest canary gives me an error `items is not defined` ([See callstack separately](https://gist.github.com/Slapbox/666fd0fce5623daa794d20d42d879f4b))

----

In `beta34`,  it seems like the arguments are the reverse of what's mentioned in #809?

```js
<Transition
  items={items}
  from={{ opacity: 0 }}
  enter={{ opacity: 1 }}
  leave={{ opacity: 0 }}>
  {(item, values=> (  // ITEM SEEMS TO BE FIRST?
    <animated.div style={values}>{item}</animated.div>
  )}
</Transition>
```

Additionally, `values` appears to only contain a string `initial`? I get the error `TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Index property setter is not supported.`

It seems like `beta34` should work, but for the fact that I'm only getting a string for `values`. Any thoughts? Thanks a lot your attention and assistance with this @aleclarson.

**Comment by aleclarson** [comment]
The `Transition` API is different between `beta.34` and `canary.808.17`. #809 applies to the canary only.

Please provide a minimal [CodeSandbox](https://codesandbox.io/s/) or git url that shows the issue. 👍

**Comment by Slapbox** [comment]
@aleclarson - can you point me to any documentation/example/discussion on how to use the latest version? I can create a repro if that doesn't elucidate my issue - but right now I don't even know how to use the new version. I can't imagine the `items` prop has been removed, right?  

`<Transition items={items} />`, where `items` is an array of `React` components, I get `items is not defined`

**Comment by aleclarson** [comment]
Works fine for me: https://codesandbox.io/s/react-spring-issue-919-1rvf9

**Comment by Slapbox** [comment]
[Works fine for me too, with a closer test case to my own](https://codesandbox.io/s/nice-bouman-16quc) -_- (although it does seem that old items are not removed properly?)

But in `Electron@7.1.10`, an array of valid React children invariably fails.
![image](https://user-images.githubusercontent.com/6835891/73496728-3bbb5480-4387-11ea-9c6c-027e6e7a2ef7.png)
![image](https://user-images.githubusercontent.com/6835891/73496770-542b6f00-4387-11ea-8601-d6738a9c7ec0.png)

Any ideas? Worked fine in `8.x`. A stripped down version works on CodeSandbox. Very baffling. Latest canary never gets to the child function that renders the items though, because it insists there are no items.

**Comment by aleclarson** [comment]
Line 2210 has no reference to an `items` variable. You probably need to reinstall your dependencies.

**Comment by Slapbox** [comment]
@aleclarson - thank you so much for your responses today. I've reinstalled the package twice now, and cleared the folder out before installing the second time. 

`2210` proves not to match perfectly to the actual file on the filesystem. The actual code on at the point of failure is:

![image](https://user-images.githubusercontent.com/6835891/73498305-ed0fb980-438a-11ea-876f-6c59ccffcb5e.png)

In `node_modules/@react-spring/core/package.json`, I see:

```js
  "name": "@react-spring/core",
  "version": "9.0.0-canary.808.17.55c5691",
```

Everything seems to be in order as far as installation goes.

----

Separately, do you have any thoughts on the sandbox I linked above failing to remove items from the list? Have I overlooked something there?

Thank you again for your help @aleclarson. I really appreciate it.

**Comment by aleclarson** [comment]
Okay, there's the issue! Very strange that the sandbox works at all.. 🤔

Some kind of Babel bug. Looks like `<Spring>` is also affected.

**Comment by Slapbox** [comment]
Let me know if there's anything I can do to assist!

**Comment by Slapbox** [comment]
@aleclarson would you like me to repurpose this issue or create a new issue for this issue?

**Comment by Slapbox** [comment]
I hoped upgrading from `babel` packages from a mix of `7.6` and `7.7` all to their latest would resolve this, but no luck.

Is this something that's fixable by the maintainers of `react-spring`, or is this issue beyond your control? We're hoping to release a new version including `react-spring` soon, and we'd be fine with using a nightly since we only use `react-spring` in this one place right now. But of course, `items is not defined` is a bit of a showstopper.

Any thoughts @aleclarson?
