### ISSUE TITLE
A `useSpring` whose `to` is an async function executes its animation cycle on every rerender.

### ISSUE THREAD

**Issue by vlopp** [react-spring/react-spring#921]
# I just realized this is the intended behaviour. Please delete this issue.

## 🐛 Bug Report

A `useSpring` whose `to` is an async function executes its animation cycle on every rerender.
Please see codesandbox provided below.

```js
const Component = () => {
    const [state, setState] = useState(false);
    useEffect(() => {
        setInterval(() => {
            setState(x => !x);
        }, 1000);
    }, []);

    const props = useSpring({
        to: async (next, cancel) => {
            await next({opacity: 1, color: '#ffaaee'});
            await next({opacity: 0, color: 'rgb(14,26,19)'});
        },
        from: {opacity: 0, color: 'red'}
    });

    return <animated.div style={props}>I will fade in and out</animated.div>
};
```

## Expected behavior

The animation triggers only upon the initial component render.

## Link to repro (highly encouraged)

https://codesandbox.io/s/quizzical-browser-ozj7z

## Environment

- `react-spring` v9.0.0-beta.34
- `react` v16.12.x

**Comment by aleclarson** [comment]
Yeah, this is by design. More info here: https://github.com/react-spring/react-spring/issues/642#issuecomment-568912896
