### ISSUE TITLE
Receiving warning  'config' is defined but never used  no-unused-vars error when config is being used.

### ISSUE THREAD

**Issue by DRD161** [react-spring/react-spring#927]
## 🐛 Bug Report

I'm using react spring in Gatsby and I keep getting a warning stating that config is defined but not used. I have been using the react spring documentation and have copied it as shown. However it is being used and the config settings such as delay are being applied. Not sure why I'm getting this warning.

```
import React from "react"
import { animated } from "react-spring"
import { Spring, config } from "react-spring/renderprops"
import styled from "styled-components"

const Wrapper = styled.div`
  grid-column: 3/12;
  grid-row: 5;
`

const SubHeader = styled(animated.p)`
  font-size: 1.7rem;
  color: #959595;
  font-style: italic;
  margin-bottom: 0;
`

export default function HomeSubText() {
  return (
    <Wrapper className="home-text-wrapper">
      <Spring
        from={{
          opacity: 0,
        }}
        to={{
          opacity: 1,
        }}
        config={{ delay: 1600 }}
      >
        {props => (
          <SubHeader className="home-subtext" style={props}>
            I’m a Front End Developer & UX enthusiast specializing in using
            JavaScript
          </SubHeader>
        )}
      </Spring>
      <Spring
        from={{
          opacity: 0,
        }}
        to={{
          opacity: 1,
        }}
        config={{ delay: 1650 }}
      >
        {props => (
          <SubHeader className="home-subtext" style={props}>
            to create dynamic data driven content for the web.
          </SubHeader>
        )}
      </Spring>
    </Wrapper>
  )
}
```

## To Reproduce

Clone repo and run gatsby develop.
[](https://github.com/DRD161/portfolio2)

## Expected behavior

Since config is defined and used I should not receive this warning

## Link to repo

https://github.com/DRD161/portfolio2

## Environment
- Gatsby version: 2.18.18
- react version 16.12.0
- react spring version 8.0.27

**Comment by aleclarson** [comment]
Three issues here, all of them your fault.

- The warning is coming from [eslint](https://github.com/eslint/eslint), probably from your text editor.
- You can use the `config` prop (eg: `config={{ friction: 20 }}`) without importing `config`. They have the same name, but refer to two different things. When you import `config`, you use it like this: `config={config.stiff}`
- The `delay` prop does *not* belong in the `config` prop. Instead do this: `delay={1650}`

Hope that helps.

**Comment by DRD161** [comment]
Ok thanks. Just joined the chat! I think there needs to be a clear differentiation between the two because it is not obvious from the documentation. Especially if they use the same prop name but are two different things. The docs show:

`<Spring config={{tension: 0, friction: 2, precision: 0.1}} />`
[](https://www.react-spring.io/docs/props/spring)

when defining your own config. It also says: "Spring are configurable, **delays**, tension, friction, resets, everything can be tuned." Which leads one to believe that delays do go in config. There seems to be conflicting info. Thanks either way though! I'm pointed in the right direction now :)

**Comment by aleclarson** [comment]
Yeah, the docs need some work. I didn't write them, and I'm not maintaining them atm. I plan to rewrite them after v9 is released (which has no ETA atm).
