### ISSUE TITLE
useSpring v9 immediate regression

### ISSUE THREAD

**Issue by anton-g** [react-spring/react-spring#931]
## 🐛 Bug Report

I think I found a regression on 9.0.0-canary.809.* versions but I'm not exactly sure what is wrong, it seems that `immediate` is read as true even when it's `set` to false. See sandbox below.

## To Reproduce

- Open sandbox
- Drag & release rocket

## Expected behavior

Rocket keeps moving after dragging it and releasing.

## Link to repro (highly encouraged)

https://codesandbox.io/s/initial-rocket-j17su

## Environment

- `react-spring` v9.0.0-canary.809.5.f01ecc2
- `react` v16.12.0

**Comment by aleclarson** [comment]
I know it's confusing, but the `809` canary is older than the `808` canary, because #809 was merged into #808. Try using `canary.808.17` and it will work. 👍

**Comment by damien916** [comment]
Hi, we still have the issue with latests `rc-3` version, are you aware of it ?

**Comment by aleclarson** [comment]
@damien916 Open a new issue with a sandbox. Thanks 👍
