### ISSUE TITLE
`onRest` called once on mount (I think?) and again on transition end

### ISSUE THREAD

**Issue by dclowd9901** [react-spring/react-spring#934]
## 🐛 Bug Report

I'm observing that onRest is calling once immediately when a component is rendered and again

## To Reproduce

Steps to reproduce the behavior: https://codesandbox.io/s/gracious-rain-d2255

## Expected behavior

Considering `onRest` is a callback for after-animation resting, I would assume it would only be called when the element comes to a rest after animating.
(A clear and concise description of what you expected to happen.)

## Link to repro (highly encouraged)
https://codesandbox.io/s/gracious-rain-d2255
(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next
```

**Comment by dclowd9901** [comment]
Looks like it works; Any chance this will be released as a fix for 8?

**Comment by aleclarson** [comment]
No one is maintaining v8 currently.
