### ISSUE TITLE
useTransition not leaving asynchronously when duration is set

### ISSUE THREAD

**Issue by jakemdunn** [react-spring/react-spring#936]
## 🐛 Bug Report

If a duration is set in the config for the "leave" property on a transition, transitions stop executing asynchronously, and instead end as dictated by the last removed item.

## To Reproduce

Behavior present in official useTransition demo:
https://codesandbox.io/embed/7mqy09jyq

As each additional item is added to the notification center, all currently present items slow down their transition to instead end when the latest item will end.

Easiest way to see it in action:
- Click to add an item
- Right _before_ the first item is set to dismiss (barely any of the "life" bar remains) click to add a second item.
- The first items "life" transition is recalculated and slow significantly, counter to the duration set per each.

## Expected behavior

Example of expected behavior, by removing timeout from the official demo:
https://codesandbox.io/s/messagehub-gcc33?fontsize=14&hidenavigation=1&theme=dark

Each item dismisses based on its own life cycle, regardless of how many items were added after.

## Link to repro

https://codesandbox.io/embed/7mqy09jyq

## Environment

- `react-spring` v8.0.5
- `react` v16.8.1

**Comment by jakemdunn** [comment]
Setting a logpoint on https://github.com/react-spring/react-spring/blob/caec34387ffc28c289265f55280a5163a8fe2b8c/src/renderprops/animated/FrameLoop.js#L61 for `startTime` seems to indicate that it's a single instance of controller/animation that's being updated as each item is added? Dunno if that's in the right direction, may dig into this more later.

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next
```

**Comment by jakemdunn** [comment]
Updating to official example to v9:

https://codesandbox.io/s/messagehub-48j7z

Looks like that resolves the async issue, but presents some other problems that I'm also seeing in my own code. In the 'leave' callback, only the first animation is respected, it appears to ignore the height and animation animations that are chained.

**Comment by aleclarson** [comment]
That one is probably fixed in [the latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). 👍

The `useTransition` API is slightly different, so you'll need to refactor a little. See here: #809

**Comment by jakemdunn** [comment]
Awesome, that did it. Thanks for pointing to v9, is v8 no longer supported?

**Comment by aleclarson** [comment]
Yeah, v8 isn't being maintained currently
