### ISSUE TITLE
I get the following error on build only... TypeError: b is not a function 

### ISSUE THREAD

**Issue by mgpGit** [react-spring/react-spring#947]
## 🤓 Question

Hi There!

I'm trying to use a couple different animations and it works great when I locally run this on my laptop. When I do a build and deploy it to a server I get the following error when I open the page in the browser "TypeError: b is not a function"

Is there a setting I need on build to make sure everything works as expected? I cleared out my node_modules and package-lock.json and re-installed to no avail. I have also tried to modify settings in my tsconfig.app.json which also didn't help.

Here is a simplified version of one of my animations...

  const traverseTransitions    = useTransition(toggle, p => p, {
    from:  { opacity: 0, width:"100%" },
    enter: { opacity: 1, width:"100%", paddingRight:"10px" },
    leave: { opacity: 0, width:"100%" },
  });

   {traverseTransitions.map(({ item, key, props }) =>
       <animated.div style={props} key={key}>{menuTraverse()}</animated.div>
    )}

A twist to my configuration is I am using Angular 7, I have been converting my app to React for some time and everything has worked fine with those pieces so far. Once I add react-spring for the transitions I am getting the above error.

Note: I have React 16.13 installed with react-spring 8.0.27.

Any suggestions you could provide would be extremely helpful.

Thanks in advance!

**Comment by mpGitHub** [comment]
![image](https://user-images.githubusercontent.com/8506767/76996907-5ab67b80-6920-11ea-86fe-f16329cb1a61.png)

**Comment by aleclarson** [comment]
Please try with v9:

```
npm install react-spring@next
```

**Comment by mpGitHub** [comment]
Just installed v9. It says that "g is not a function" now

![v9](https://user-images.githubusercontent.com/8506767/77013370-f1ddfc00-693d-11ea-9ab2-df99805e202d.png)

**Comment by aleclarson** [comment]
If you can't reproduce in CodeSandbox, please provide a Github repository I can debug. 👍

**Comment by mpGitHub** [comment]
looking at this code in the bundle, shouldn't it be transpiled at this point and not using "class" and such?

**Comment by aleclarson** [comment]
Oh, you'll be interested in #601. The solution for v9 is [here](https://github.com/react-spring/react-spring/issues/601#issuecomment-560515705).

**Comment by mpGitHub** [comment]
funny I was just looking at that one. With v9 - I'm now trying to use use the 'react-spring/web.cjs'

import { Transition, animated } from 'react-spring/web.cjs'

I don't see any ES6 arrow functions any longer in the bundle which is good, but I'm getting a completely different error at runtime. 

I changed away from using the hooks version to see if that would help. I tried following this very simple example. Again this works fine except when I do a build
https://github.com/react-spring/react-spring-examples/blob/renderprops/demos/renderprops/pagetransitions/index.js

![minified react error](https://user-images.githubusercontent.com/8506767/77120930-fe2e8b80-6a07-11ea-8667-1601696c5f05.png)

**Comment by mpGitHub** [comment]
Not sure this helps but this is my current tsconfig, I've tried several variations of this>

> 
>   "compilerOptions": {
>     "sourceMap": true,
>     "declaration": false,
>     "moduleResolution": "node",
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "jsx": "react",
>     "target": "es5",
>     "lib": [
>       "es2016",
>       "dom"
>     ],
>     "outDir": "../out-tsc/app",
>     "module": "es2015",
>     "baseUrl": "",
>     "types": ["node"],
>    
> 

>  "paths": {
>       "ag-grid/*": ["../node_modules/ag-grid/*"]
>     }
>   }

**Comment by aleclarson** [comment]
Please see https://github.com/react-spring/react-spring/issues/947#issuecomment-600892282

**Comment by mpGitHub** [comment]
In the process of getting a simplified repo of the problem to share I was able to figure out what was going on...

The build optimizer for angular was somehow causing this issue. Turning this off everything works as expected. I am confused why it solely causes a problem in this library and no others to date as we have a large app with lots of dependencies...

Still digging...
