### ISSUE TITLE
lacking documentation: how to pass a spring to animated component

### ISSUE THREAD

**Issue by jutunen** [react-spring/react-spring#953]
https://www.react-spring.io/docs/hooks/basics says following:

> If you want to animate React components, styled-components, or elements on other platforms, then do this:

```javascript
// React components
const AnimatedDonut = animated(Donut)
```

Let's assume that I have a following spring definition:
```javascript
const props = useSpring({opacity: 1, from: {opacity: 0}})
```
Could you please tell me how to pass the defined spring to the animated component?

**Comment by hawk-ee** [comment]
Hey @jutunen, it's on the docs:

> Finally: distribute animated props among the view
> The return value is an object containing animated props.
> ```return <animated.div style={props}>i will fade</animated.div>```

**Comment by jutunen** [comment]
Can't see any props passing on this line:
```javascript
// React components
const AnimatedDonut = animated(Donut)
```

**Comment by IngoValente** [comment]
That's because that's only recreating your component to be ready to be animated, you still need to render it.
```javascript
const props = useSpring({opacity: 1, from: {opacity: 0}})
return (
    <AnimatedDonut style{props}/>
)
```

**Comment by jutunen** [comment]
> 
> 
> That's because that's only recreating your component to be ready to be animated, you still need to render it.
> 
> ```js
> const props = useSpring({opacity: 1, from: {opacity: 0}})
> return (
>     <AnimatedDonut style={props}/>
> )
> ```

Now this is documentation! 

Hopefully this info gets to place where it belongs to, instead of being buried here among other issues.

**Comment by hawk-ee** [comment]
> > That's because that's only recreating your component to be ready to be animated, you still need to render it.
> > ```js
> > const props = useSpring({opacity: 1, from: {opacity: 0}})
> > return (
> >     <AnimatedDonut style={props}/>
> > )
> > ```
> 
> Now this is documentation!
> 
> Hopefully this info gets to place where it belongs to, instead of being buried here among other issues.

You can submit a PR, it's open source ; )
