### ISSUE TITLE
How can one-way animation looping be implemented?

### ISSUE THREAD

**Issue by gtolarc** [react-spring/react-spring#956]
Here is my sample code. If loop is implemented as the following, 1-> 10, 10-> 1, 1-> 10, ... are repeated. But I want to repeat 1-> 10, 1-> 10, 1-> 10. Is there any way?

```
const LED = props => {
  const [spring, set] = useSpring(() => ({
    from: { number: 1 },
    to: async next => {
      while (1) {
        await next({ number: 10 });
        await next({ number: 1 });
      }
    },
    config: {
      duration: 3000
    }
  }));

  return <a.div>{spring.number}</a.div>;
};
```

**Comment by aleclarson** [comment]
In the latest canary, you can use the `loop` prop:
```ts
useSpring({
  loop: true,
  from: { n: 1 },
  to: { n: 10 },
})
```
Note: I have some bug fixes for the `loop` prop ready for the next canary, so bugs might exist in the latest canary that prevent the example above from working as expected.

**Comment by gtolarc** [comment]
Thank you and look forward to the next release :)

**Comment by aleclarson** [comment]
Now available in v9.0.0-rc.2 #985

**Comment by shubhamkes** [comment]
u can do so in v8 as well by reset flag

useSpring({
  reset: true,
  from: { n: 1 },
  to: { n: 10 },
})

**Comment by aleclarson** [comment]
@shubhamkes Sort of. That requires you to rerender for each repetition.

**Comment by shubhamkes** [comment]
oh is it?  thought they are same. is v9.0.0-rc.2 recommended for prod?
