### ISSUE TITLE
Animation crashes when using keywords for colors

### ISSUE THREAD

**Issue by fastndead** [react-spring/react-spring#958]
## 🐛 Bug Report

I guess it's an issue with 'yellowgreen' or maybe with some other, but it appears that if I use 'yellowgreen' css color keyword and bind it to props, the app crashes completely when changing props. 

## To Reproduce

1. Set up useSpring something like this: 
`const props = useSpring({ backgroundColor: toggle ? '#fff' : 'yellowgreen' });`
 2. Then try to change toggle in app

## Expected behavior
The background color of animated element changing from white to yellowgreen

## Actual behavior
So, basically, first render goes okay, here's sneak peak from my app:

![image](https://user-images.githubusercontent.com/33729448/79026208-2047a380-7b99-11ea-9124-61b012f34b06.png)

but! if i will click the button, which cause the toggle to change, I get Uncaught TypeError: Cannot read property 'push' of undefined:

![image](https://user-images.githubusercontent.com/33729448/79026272-55ec8c80-7b99-11ea-8f6a-12ed69f8ca0f.png)

Actually, I don't mind not using those keywords anyway, but I guess it should be stated somewhere, that that's an issue
## Environment

- `react-spring` v8.0.27
- `react` v16.13.1

**Comment by aleclarson** [comment]
Please reproduce in CodeSandbox. 👍 (and try `9.0.0-rc.1`)
