### ISSUE TITLE
useTransition is ignoring trail property for enter

### ISSUE THREAD

**Issue by Jhony0311** [react-spring/react-spring#960]
## 🐛 Bug Report

When using using useTransition the trail parameter is being ignored in the enter animation. Is only being applied on leave or update. I believe this has to do with a line of code in the diff props function that subtract the trail value from itself making it equal to 0, look here: https://github.com/react-spring/react-spring/blob/master/src/useTransition.js#L200.

## To Reproduce

Create any transition using useTransition and apply a visually significant trail, 5000ms for example.

## Expected behavior

The expected behavior according the docs is that trails should be added to enter, leave and update properties.

## Link to repro (highly encouraged)

https://codesandbox.io/s/messagehub-6n9bc

## Environment

- `react-spring` v8.05 and greater
- `react` v16.3.1

**Comment by aleclarson** [comment]
The `trail` property of `useTransition` only affects items that were added in the same render.
