### ISSUE TITLE
While-loop causes browser crashes

### ISSUE THREAD

**Issue by WhySoBad** [react-spring/react-spring#982]
## 🐛 Bug Report

At the react-spring website https://www.react-spring.io/ one of the examples for useSpring() is this codesandbox https://codesandbox.io/embed/8ypj5vq6m9. This code sandbox works perfectly in the sandbox but in a real project it causes browser tab crashes. I copyed the code and changed it to my use and the browser tab always crashes due to the ```while(1)``` loop. **This issue is similar to #591** which should be fixed since April 2019. I tried with the 9.0.0 beta too but nothing changed. I also tested with different browsers (Chrome, Microsoft Edge Canary, Internet Explorer, Microsoft Edge) but at every browser the site crashed.  

## To Reproduce

This is my code:
```js
const HeaderLogo = props => {
  //While testing sineHeight was 2 and waveDuration 3000
  const { sineHeight, waveDuration, className, ...rest } = props;
  const additionalParam_b = 10; //Only useful for multi objects
  const additionalParam_d = 1.7; //Only useful for multi objects
  const interp = i => r => {
    return `translate3d(0, ${
      sineHeight *
      Math.sin(r + (i * additionalParam_b * Math.PI) / additionalParam_d)
    }px, 0)`;
  };

  const { radians } = useSpring({
    to: async next => {
      while (1) await next({ radians: 2 * Math.PI });
    },
    from: { radians: 0 },
    config: { duration: waveDuration },
    reset: true,
  });
  return (
    <animated.div
      className={cx(className, style.header_logo)}
      style={{ transform: radians.interpolate(interp(0)) }}
    >
      <HeaderButton {...rest} />
    </animated.div>
  );
};
```
## Expected behavior

The while loop executes too fast what causes a browser tab crash. 

## Link to repro (highly encouraged)

https://codesandbox.io/embed/8ypj5vq6m9 (Example from https://www.react-spring.io/docs/hooks/use-spring which even causes crashes on this website)

## Environment

- `react-spring` v9.0.0-beta.34 and v8.0.27
- `react` v16.12.0

**Comment by aleclarson** [comment]
Please try with v9.0.0-rc.2

#985

**Comment by WhySoBad** [comment]
Thanks for the quick answer. 
I successfully installed this version but the site doesn't even render anything anymore. After a few seconds the site crashes.

**Comment by aleclarson** [comment]
Can you reliably reproduce this with a git repository? 👍

**Comment by aleclarson** [comment]
Can you reliably reproduce this with a git repository? So I can take a look 👍

**Comment by sad-squid** [comment]
Tried this today with rc3 and also experiencing the same, with the same example as well as the react-spring site. 

Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by aleclarson** [comment]
That code is incorrect for v9. See its latest version here: 
https://github.com/react-spring/react-spring-examples/blob/14b8219bd5e9280f29cd4624ffc60ebe97ec00b0/demos/hooks/blackflag/index.js#L11-L19

The infinite loop is triggered when the `Promise` returned by the `next` function is resolved immediately, which is what happens on every `while` tick. The `Promise` is resolved immediately each time, because its goal value `{ radians: 2 * Math.PI }` is equal to the current value.

**Comment by aleclarson** [comment]
Even better than what I linked above: In v9, you can use the `loop` prop for less boilerplate:
```js
  const props = useSpring({
    to: { radians: radians: 2 * Math.PI },
    from: { radians: 0 },
    loop: true,
    config: { duration: 3500 },
  })
```

**Comment by sad-squid** [comment]
Thanks for the clarification, this solved it! Appreciate the prompt response @aleclarson, I see I'm not the only one taking advantage of the day off 😄 ! 
I tried looking at the [v9 changelog](https://www.react-spring.io/log) for potential breakage notes on this, is there a particular section that I missed from that?

**Comment by aleclarson** [comment]
The latest v9 docs are here: https://aleclarson.github.io/react-spring/v9/

Breaking changes have their own page: https://aleclarson.github.io/react-spring/v9/breaking-changes/
