### ISSUE TITLE
[v9.0.0-rc.1] Expose React.createContext<SpringContext>({}) in order to propagate SpringContext across reconcilers

### ISSUE THREAD

**Issue by zenios** [react-spring/react-spring#988]
React context does not propagate across multiple reconcilers

1. https://github.com/inlet/react-pixi/issues/77
2. https://github.com/michalochman/react-pixi-fiber/issues/93
3. https://github.com/facebook/react/issues/13336#issuecomment-414709155

The recommended solution is to create the so called **context bridge** that you capture the values from the top context and bridge them to the context that is created on the new reconciler

In order to achieve this we need to have access to the ctx object

**Comment by aleclarson** [comment]
Sounds good. I'll expose the `SpringContext.Provider` and `SpringContext.Consumer` components.

**Comment by zenios** [comment]
If its cleaner you can only expose useSpringContext and will spread the result into a new SpringContext provider

**Comment by aleclarson** [comment]
Available in v9.0.0-rc.2+

**Comment by aleclarson** [comment]
@zenios Can you provide some example code of how you're using `SpringContext.Provider` and `SpringContext.Consumer`? I'm wondering if `<SpringContext>` and `useContext(SpringContext)` (the latter of which will be possible in the next RC) aren't good enough for your use case.
