### ISSUE TITLE
TypeScript error using react-spring interpolate

### ISSUE THREAD

**Issue by DenisDiachenko** [react-spring/react-spring#998]
**##** 🐛 Bug Report

I just tried to use the official example with Mouse-Parallax in the typescript project and receive TS error when using interpolate function.  

![image](https://user-images.githubusercontent.com/34863952/81493515-8d8a4980-92a9-11ea-9586-ba38885bbc9d.png)

https://codesandbox.io/embed/r5x34869vq

I tried to wrap **x** and **y** parameters into an array, but this didn't help

## Environment

- `react-spring` ^8.0.27
- `react` v16.9.34

**Comment by aleclarson** [comment]
The `xy` array is spread into your callback, so you need to pass `(x: number, y:number) => [number, number]`
